#!/usr/bin/expect

# Main entrance
log_file wireless_test_log
send_log "\nWireless network test is starting...\r"
send_user "Starting wireless_test.exp\n"

set user /home/test
set uclinux_path $user/checkouts/kernel/uClinux-dist
set ttydev /dev/ttyS0
set send_slow {1 0.1}

set argc [llength $argv]
if { $argc < 1} {
   puts "Usage:  $argv0 ping_ipaddr"
   puts ""
   exit
}
# grab the user specified parameters.
set ping_ipaddr             [lindex $argv 0]

proc step { message } {
  global step_sequence_number

  puts "\n*******************************************************************"
  puts "STEP $step_sequence_number: $message\n\n"
  send_log "\n************** STEP $step_sequence_number: $message\n\n"
  incr step_sequence_number
}

set step_sequence_number    1
set test_flag	0

step "Start kermit"

set kparams	[list "set line $ttydev\r"]
lappend kparams "set speed 57600\r"
lappend kparams "set carrier-watch off\r"
lappend kparams "set handshake none\r"
lappend kparams "set flow-control none\r"
lappend kparams "robust\r"
lappend kparams "set file type bin\r"
lappend kparams "set file name lit\r"
lappend kparams "set rec pack 1000\r"
lappend kparams "set send pack 1000\r"
lappend kparams "set window 5\r"
lappend kparams "set escape 255\r"
set nkparams	[llength $kparams]

set timeout 5
spawn kermit
set kermit_spawn_id $spawn_id

while { 1 } {
   expect {
      "Type ?" { }
      "ermit>" {
         break
      }
      "not found" {
         send_log "\nERROR: Failed to start Kermit\n"
      }
      timeout {
         send_log "\nERROR: Time out starting up kermit\n"
      }
   }
}

for {set i 0} {$i < $nkparams} {incr i} {
   send [lindex $kparams $i]

   while 1 {
      expect {
         "ermit>" { break }
         "\\?\[A-Z]" {
            send_log "\nERROR: Failed to set up kermit parameters\n"
         }
         timeout {
            send_log "\nERROR: Time out setting up kermit parameters\n"
         }
      }
   }
}

send "connect\r"
while 1 {
   expect {
      "ype the escape character*" {
         break
      }
      timeout {
         send_log "\nERROR: Can't connect to serial port\n"
         exit
      }
   }
}

step "Restart the board."

send_user "Try to figure out if we are in u-boot or the kernel"
set where_are_we 0
send "version\r"
set timeout 20
expect {

   "U-Boot" {
      send_user "We are in u-boot\n"
      set where_are_we "uboot"
   }

   "Linux" {
      send_user "We are in the kernel\n"
      set where_are_we "kernel"
   }

   timeout {
      send_user "Can't tell if we are in u-boot or the kernel\n"
   }
}

if { $where_are_we == "uboot" } {
   set timeout 50
   expect ">"
   send_user "sending reset\n"
   send "reset\r"
} else {
   if { $where_are_we == "kernel" } {
      set timeout 60
      expect ">"
      send_user "sending reboot\n"
      send "reboot\r"
   } else {
      set timeout 10
      expect "*"
      expect "*"
      send_user "sending control-C\n"
      send "\3"
      sleep 1
      send "\r"
   }
}

while 1 {
   expect {

      "Hit any key " {
         send "\r"
      }

      ">" {
         send_user "successful reset attemp\n"
         break
      }

      timeout {
         send_user "failed reset attemp\n"
         break
      }
   }
}

send -s "set bootargs root=/dev/mtdblock0 rw\r"
expect ">"
send -s "save\r"
expect ">"

send -s "tftpboot 0x1000000 linux\r"
while 1 {
   expect {
      "#" {
         expect ">"
            break
      }
      timeout {
         puts "Fail tftp"
         break
      }
   }
}

send -s "boote\r"

set timeout 180
while 1 {
   expect {

      -re "Kernel panic" {
         report "kernel panic detected... trying to recover from it"
         break
      }

      -re "Sash command shell.*/> " {
         puts "successful boot attempt"
         break
      }

      "root:~> " {
         puts "successful boot attempt"
         break
      }

      -re "Linux version (.*) " {
         set linux_version $expect_out(1,string)
      }

      # Look for gcc version N.N[.N[.N]]
      -re "gcc version (\[0-9](\.\[0-9]+)+)" {
         set gcc_version [lindex $expect_out(0,string) 2]
      }

      # Look for text followed by 1 or more spaces or tabs
      # followed by = followed by 1 or more spaces or tabs
      # followed by (0xNNNNNN-0xNNNNNN)
      -re "text\[\x20\t]+=\[\x20\t]+(0x\[0-9a-fA-F]+-0x.....\[0-9a-fA-F]+)" {
         set map_text $expect_out(1,string)
      }

      -re "data\[\x20\t]+=\[\x20\t]+(0x\[0-9a-fA-F]+-0x.....\[0-9a-fA-F]+)" {
         set map_data $expect_out(1,string)
      }

      -re "bss\[\x20\t]+=\[\x20\t]+(0x\[0-9a-fA-F]+-0x.....\[0-9a-fA-F]+)" {
         set map_bss $expect_out(1,string)
      }

      -re "rootfs\[\x20\t]+=\[\x20\t]+(0x\[0-9a-fA-F]+-0x.....\[0-9a-fA-F]+)" {
         set map_rootfs $expect_out(1,string)
      }

      # Note that here we're looking for zero or 1 space. Doh!
      -re "stack\[\x20\t]?=\[\x20\t]+(0x\[0-9a-fA-F]+-0x.....\[0-9a-fA-F]+)" {
         set map_stack $expect_out(1,string)
      }

      -re "\[Ii]nstruction \[Cc]ache \[Ee]nabled" {
         # set instruction_cache_boot_flag $CACHE_ENABLED
      }

      -re "\[Ii]nstruction \[Cc]ache \[Dd]isabled" {
         # set instruction_cache_boot_flag $CACHE_DISABLED
      }

      -re "\[Dd]ata \[Cc]ache \[Ee]nabled" {
         # set data_cache_boot_flag $CACHE_ENABLED
      }

      -re "\[Dd]ata \[Cc]ache \[Dd]isabled" {
         #set data_cache_boot_flag $CACHE_DISABLED
      }

      timeout {
         puts "failed boot attempt"
         break
      }
   }
}

sleep 5

step "Start Wireless Network testing"

#step "Set key"
#set timeout 2
#send "iwconfig eth1 essid dlink key s:12345\r"
#while 1 {
#   expect {
#      "root:~>" {
#         send_log "\nSet key done\n"
#         send_user "\nSet key done\n"
#         break
#      }
#      timeout {
#         send_log "\nSet key timeout\n"
#         send_user "\nSet key timeout\n"
#         incr test_flag
#         break
#      }
#   }
#}

step "dhcpcd eth1"
set timeout 30
send "dhcpcd eth1 &\r"
while 1 {
   expect {

#      -re "\[0-9]*" {
#         send_log "\nStart dhcpcd for eth1\n"
#         send_user "\nStart dhcpcd for eth1\n"
#         break
#      }

      -re ".*Connected" {
         send_log "\nNetwork is connected\n"
         send_user "\nNetwork is connected\n"
         break
      }

      timeout {
         send_log "\nStart dhcpcd timeout\n"
         send_user "\nStart dhcpcd timeout\n"
         incr test_flag
         break
      }
   }
}

step "iwconfig"
set timeout 2
send "iwconfig\r"
sleep 2
while 1 {
   expect {

#      -re ".*802\.11.*" {
#         send_log "\niwconfig done\n"
#         send_user "\niwconfig done\n"
#         break
#      }

      -re ".* ESSID:\"\".*" {
         send_log "\nNot reached WLAN\n"
         send_user "\nNot reached WLAN\n"
         incr test_flag
         break
      }
      timeout {
         break
      }
   }
}

sleep 60
send_log "\nWaiting for network up\n"
send_user "\nWaiting for network up\n"

step "ifconfig"
set timeout 10
send "ifconfig eth1\r"
while 1 {
   expect {
      -re "inet addr:\[0-9].*" {
         send_user "\nGet ipaddr for wireless link\n"
         break
      }

      timeout {
         send_log "\nifconfig timeout\n"
         send_user "\nifconfig timeout\n"
         incr test_flag
         break
      }
   }
}

step "begin test"
send "ping $ping_ipaddr\r"
sleep 1
send "\03\r"
while 1 {
   expect {
      -re ".* 0% packet loss.*" {
         send_log "\nping remote host\n"
         send_user "\nping remote host\n"
         break
      }
      timeout {
         send_log "\nping fail\n"
         send_user "\nping fail\n"
         incr test_flag
         break
      }
   }
}

if { $test_flag == 0 } {
   send_log "\nWireless network test PASS\n"
   send_user "\nWireless network test PASS\n"
} else {
   send_log "\nWireless network test FAIL\n"
   send_user "\nWireless network test FAIL\n"
}

exit
