#!/usr/bin/expect

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

set case_num 0
set timeout 2
sleep 5
send "\r"
expect -re $kernel_prompt

step "Start testing"
incr case_num
set timeout 70
send "latency -t0 -T60 -h\r"
while 1 {
    expect {
        -re "RTS.*/.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send "\3"
            expect -re $kernel_prompt
            case_fail $case_num
        }
    }
}

incr case_num
send "latency -t1 -T60 -h\r"
while 1 {
    expect {
        -re "RTS.*/.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send "\3"
            expect -re $kernel_prompt
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 70
send "latency -t2 -T60 -h\r"
while 1 {
    expect {
        -re "RTS.*/.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send "\3"
            expect -re $kernel_prompt
            case_fail $case_num
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"
send_user "Ending $argv0\n"

log_file
