#!/bin/bash
#
# RCSID $Id$
#
# This script is OBSOLETE -- rgb, May 6th, 1998
set +v
insmod ipsec.o
tncfg attach ipsec0 eth2
ifconfig ipsec0 10.2.0.143 up netmask 255.255.0.0
route del 10.2.0.0
route add -net 10.2.0.0 netmask 255.255.0.0 dev ipsec0


#
# $Log$
# Revision 1.1  2006/08/05 01:45:48  vapier
# merge from upstream uClinux
#
# Revision 1.4  2002/04/24 07:36:18  mcr
# Moved from ./klips/test/ji/ttn,v
#
# Revision 1.3  1999/04/06 04:54:36  rgb
# Fix/Add RCSID Id: and Log: bits to make PHMDs happy.  This includes
# patch shell fixes.
#
#
