/* This file is automatically generated
   from libm-test.inc with gen-libm-test.pl.
   Don't change it - change instead the master files.  */


/* Maximal error of functions.  */

/* Error of single function calls.  */
