#!/usr/bin/expect

set timeout 8
cd $uclinux_path
catch {exec cp images/$boot_image  /tftpboot}

if { $HAVE_JFFS2_IMAGE == "1" } {
    catch {exec cp images/$compressed_kernel_only_image  /tftpboot}
    catch {exec cp images/$jffs2_rootfs_image  /tftpboot}
}

if { $HAVE_KERNEL_ONLY_IMAGE == "1" } {
    catch {exec cp images/$compressed_kernel_only_image /tftpboot}
}

if { $HAVE_ROMFS_IMAGE == "1" } {
    exec cp images/$kernel_and_romfs_image /tftpboot
    exec rm -fr /tftpboot/uImage
}
