#!/bin/sh
########################################################################################################################
######### To run this script, please first set following uboot varibles properly on your target board  #################
######### set  bootargs  bootfile linux                                                                #################
######### set  bootargs  loadaddr 2000000                                                     	       #################
######### set  bootcmd   run tftpboot                                                                  #################
######### set  tftpboot  'tftp 0x2000000 linux;bootelf'                                                #################
######### set  ipaddr    10.100.4.50  (set your board ip here)                                         #################
######### set  serverip  10.100.4.174 (set your server ip here)                                        #################
########################################################################################################################

 ############### Set up the testing environment. Edit the following variables to suit your situation. ###################
 
 USER=/home/test
 BOARD_CONFIG=BF537-STAMP-STD
 CPU=BF537
 KERNEL_PATH=$USER/checkouts/kernel
 BINARY_FORMAT=flat
 ALLOCATOR=slab\(p2\)
 ICACHE=on
 DCACHE=off
 POLICY=write_through
 UART_MODE=dma
 THIS_LOG="$USER/test_scripts/kernel/logs/all_""$CPU""_""$BINARY_FORMAT""_""$ALLOCATOR""_icache(""$ICACHE"")_""dcache(""$DCACHE"",""$POLICY"")_UART(""$UART_MODE"")""/THIS_LOG"
 
 ########################################### Please don't edit anything below this line.###################################

if [ $# -lt 2 ] ; then
  echo "Please input BOARD_CONFIG CPU [ KERNEL_PATH BINARY_FORMAT ALLOCATOR ICACHE DCACHE POLICY UART_MODE THIS_LOG VCO_MULT CCLK_DIV SCLK_DIV ] values: "
  echo
  echo "The BOARD_CONFIG :  BF533-STAMP-STD, BF537-STAMP-STD, BF537-STAMP-IDE,etc."
  echo "The CPU :           BF533, BF537, BF561,etc."
  echo "The BINARY_FORMAT : flat, elf, shared-flat."
  echo "The ALLOCATOR :     slab\(p2\), slob\(p2\), slob\(np2\)."
  echo "The ICACHE,DCACHE : on, off."
  echo "The POLICY :        write_through, write_back."
  echo
  echo "For example:./kernel_test BF537-STAMP-STD bf537 /home/test/checkouts/kernel flat slab\(p2\) on on write_through dma /home/test/test_scripts/kernel/logs/all_flat_write_through/THIS_LOG."
  exit
fi

if [ $# -gt 0 ] ; then
  BOARD_CONFIG=$1
  echo  "##### Testing is done with: $BOARD_CONFIG."
fi

if [ $# -gt 1 ] ; then     
  CPU=$2
  echo "##### CPU: $CPU." 
fi

  if [ $# -gt 2 ] ; then 
  KERNEL_PATH=$3
  echo "##### KERNEL_PATH: $KERNEL_PATH."  
fi

  KERNEL_PATH_BAK="$KERNEL_PATH""_bak"  
  KERNEL_SOURCE=$KERNEL_PATH/uClinux-dist
  KERNEL_SOURCE_BAK=$KERNEL_PATH_BAK/uClinux-dist  
  KERNEL_SCRIPTS=$KERNEL_SOURCE/testsuites  
  
if [ $# -gt 3 ] ; then
  BINARY_FORMAT=$4  
  echo "##### BINARY_FORMAT: $BINARY_FORMAT."
fi

if [ $# -gt 4 ] ; then
  ALLOCATOR=$5
  echo "##### ALLOCATOR: $ALLOCATOR."
fi
  
if [ $# -gt 7 ] ; then
  ICACHE=$6
  DCACHE=$7
  POLICY=$8  
  echo "##### ICACHE: $ICACHE, DCACHE: $DCACHE, POLICY is $POLICY." 
fi
  
if [ $# -gt 8 ] ; then
  UART_MODE=$9
  echo "##### UART_MODE: $UART_MODE."
fi
  
if [ $# -gt 9 ] ; then
  THIS_LOG=${10}
  echo "##### Test results are in folder: $THIS_LOG."
fi
 
if [ $# -gt 10 ] ; then
  VCO_MULT=${11}
  CCLK_DIV=${12}
  SCLK_DIV=${13}
  echo "##### VCO_MULT: $VCO_MULT, CCLK_DIV: $CCLK_DIV, SCLK_DIV: $SCLK_DIV."
fi


###### See if kernel has been checked out.##################################################
 
if [ ! -d $KERNEL_PATH_BAK ] ; then
  echo  "##### No kernel source in $KERNEL_PATH_BAK."
  exit
fi
if [ ! -d $KERNEL_PATH ] ; then
  mkdir -p $KERNEL_PATH
  echo  "##### Testing is doing against the kernel source in $KERNEL_PATH."
fi

if [ ! -d $THIS_LOG ] ; then
  mkdir -p $THIS_LOG    
else 
  rm -rf $THIS_LOG/*  
fi
  
# KERNEL_SCRIPTS/change_clk.exp $BOARD_TYPE $VCO_MULT $CCLK_DIV $SCLK_DIV

######## Set the default value for the test cases
          reset_board=1 # set this value to 1 if your target board could be restarted from host machine parallel port.
	  
         build_policy=0
	ethernet_test=0
ethernet_in_buffer_test=0
	  stress_test=0
	  serial_test=0 
     serial_port_test=0
    serial_uart1_test=0
	  reboot_test=0	     
	  module_test=0
	    kgdb_test=0
	     rtc_test=0
	     nfs_test=0
	 pnormtd_test=0
    jffs2_reboot_test=0 
	jffs2_fs_test=0
	  strace_test=0
	     msh_test=0
	 pthread_test=0
	     dpm_test=0
	     dll_test=0
	   timer_test=0
	   pound_test=0
	  sqlite_test=0
        watchdog_test=0
module_l1_memory_test=0	  
	     ltp_test=0
     spiadc_ndso_test=0
      spiadc_awg_test=0      
    audio_ad1836_test=0
   audio_ad73311_test=0
	   pflag_test=0
        pfbutton_test=0
	  ad9960_test=0
	    dpmc_test=0
	  i2ctwi_test=0
        joystick_test=0
         snormtd_test=0
	 cf_card_test=0
    ide_harddisk_test=0
       ide_cdrom_test=0
	wireless_test=0
	   yaffs_test=0
	  ppifcd_test=0	  
	 usbhost_test=0
	  usbnet_test=0	  
	   coreb_test=0
	  l1_app_test=0
	sigqueue_test=0

     
#######  BOARD CONFIG DEFINITION      ###################################################### 

if [ $BOARD_CONFIG = "BF537-STAMP-STD" ] ; then   
   
   BOARD_TYPE=BF537-STAMP
   
         build_policy=1
	ethernet_test=1
ethernet_in_buffer_test=1
	  stress_test=1
	  serial_test=1
     serial_port_test=1
    serial_uart1_test=1
	  reboot_test=1	     
	  module_test=1
	    kgdb_test=1
	     rtc_test=1
	     nfs_test=1
	 pnormtd_test=1
    jffs2_reboot_test=1 
	jffs2_fs_test=1
	  strace_test=1
	     msh_test=1
	 pthread_test=1
	     dpm_test=1
	     dll_test=1
	   timer_test=1
	   pound_test=1
	  sqlite_test=1
        watchdog_test=1
module_l1_memory_test=1	  
	     ltp_test=1
     spiadc_ndso_test=1
      spiadc_awg_test=1      
    audio_ad1836_test=1
   audio_ad73311_test=0
	   pflag_test=0
        pfbutton_test=0
	  ad9960_test=0
	    dpmc_test=1
	  i2ctwi_test=1
        joystick_test=1
         snormtd_test=1
	 cf_card_test=0
    ide_harddisk_test=0
       ide_cdrom_test=0
	wireless_test=0
	   yaffs_test=0
	  ppifcd_test=1	   
	 usbhost_test=0
	  usbnet_test=0
	   coreb_test=0
	  l1_app_test=1
	sigqueue_test=1
fi

# Since the SW6 setting for jffs2(all on) and cf card(on on off off) are conflicting, disable jffs2 test here.

if [ $BOARD_CONFIG = "BF537-STAMP-CF" ] ; then   
   
   BOARD_TYPE=BF537-STAMP
   
         build_policy=1
	ethernet_test=1
ethernet_in_buffer_test=1
	  stress_test=1
	  serial_test=1
     serial_port_test=1
    serial_uart1_test=1
	  reboot_test=1	     
	  module_test=1
	    kgdb_test=1
	     rtc_test=1
	     nfs_test=1
	 pnormtd_test=1
    jffs2_reboot_test=0 
	jffs2_fs_test=0
	  strace_test=1
	     msh_test=1
	 pthread_test=1
	     dpm_test=1
	     dll_test=1
	   timer_test=1
	   pound_test=1
	  sqlite_test=1
        watchdog_test=1
module_l1_memory_test=1	  
	     ltp_test=1
     spiadc_ndso_test=1
      spiadc_awg_test=1      
    audio_ad1836_test=1
   audio_ad73311_test=0
	   pflag_test=0
        pfbutton_test=0
	  ad9960_test=0
	    dpmc_test=1
	  i2ctwi_test=1
        joystick_test=1
         snormtd_test=0
	 cf_card_test=1
    ide_harddisk_test=0
       ide_cdrom_test=1
	wireless_test=0
	   yaffs_test=0
	  ppifcd_test=0	   
	 usbhost_test=0
	  usbnet_test=0
	   coreb_test=0
	  l1_app_test=1
	sigqueue_test=1
fi


if [ $BOARD_CONFIG = "BF533-STAMP-STD" ] ; then   
   
   BOARD_TYPE=BF533-STAMP
   
         build_policy=1
	ethernet_test=1
ethernet_in_buffer_test=1
	  stress_test=1
	  serial_test=1
     serial_port_test=1
	  reboot_test=1	     
	  module_test=1
	    kgdb_test=1
	     rtc_test=1
	     nfs_test=1
	 pnormtd_test=1
    jffs2_reboot_test=1 
	jffs2_fs_test=1
	  strace_test=1
	     msh_test=1
	 pthread_test=1
	     dpm_test=1
	     dll_test=1
	   timer_test=1
	   pound_test=1
	  sqlite_test=1
        watchdog_test=0
module_l1_memory_test=1	  
	     ltp_test=1
     spiadc_ndso_test=1
      spiadc_awg_test=1      
    audio_ad1836_test=1
   audio_ad73311_test=0
	   pflag_test=0
        pfbutton_test=0
	  ad9960_test=0
	    dpmc_test=1
	  i2ctwi_test=1
        joystick_test=0
         snormtd_test=1
	 cf_card_test=0
    ide_harddisk_test=0
       ide_cdrom_test=0
	wireless_test=0
	   yaffs_test=0
	  ppifcd_test=1	   
	 usbhost_test=0
	  usbnet_test=0
	   coreb_test=0
	  l1_app_test=1
	sigqueue_test=1
         	
fi
 
if [ $BOARD_CONFIG = "BF561-EZKIT-STD" ] ; then  
   
   BOARD_TYPE=BF561-EZKIT
   
         build_policy=0
	ethernet_test=1
ethernet_in_buffer_test=1
	  stress_test=1
	  serial_test=1
     serial_port_test=1
	  reboot_test=1	     
	  module_test=0
	    kgdb_test=0
	     rtc_test=0
	     nfs_test=0
	 pnormtd_test=0
    jffs2_reboot_test=1 
	jffs2_fs_test=0
	  strace_test=0
	     msh_test=0
	 pthread_test=0
	     dpm_test=0
	     dll_test=1
	   timer_test=0
	   pound_test=0
	  sqlite_test=1
        watchdog_test=1
module_l1_memory_test=1	  
	     ltp_test=1
     spiadc_ndso_test=1
      spiadc_awg_test=1      
    audio_ad1836_test=1
   audio_ad73311_test=0
	   pflag_test=0
        pfbutton_test=0
	  ad9960_test=0
	    dpmc_test=1
	  i2ctwi_test=0
        joystick_test=0
         snormtd_test=0
	 cf_card_test=0
    ide_harddisk_test=0
       ide_cdrom_test=0
	wireless_test=0
	   yaffs_test=0
	  ppifcd_test=0	   
	 usbhost_test=0
	  usbnet_test=0
	   coreb_test=1
	  l1_app_test=1
	sigqueue_test=1
         	
fi


####### Build and run the tests      #######################################################

export PATH=/opt/uClinux/bfin-uclinux/bin:/opt/uClinux/bfin-elf/bin:$PATH
echo "##### The Toolchain is:" 
/opt/uClinux/bfin-uclinux/bin/bfin-uclinux-gcc -v
echo 

cd  $KERNEL_SOURCE_BAK/testsuites
chmod +x */*.exp

  #############################################################################################
  ########################## BUILD POLICY KERNEL ##############################################
  
  if [ $build_policy -eq 1  ] ; then
  echo  "Running build policy kernel... "
  
  rm -rf $KERNEL_PATH
  echo  "mv kernel source "
  mv $KERNEL_PATH_BAK $KERNEL_PATH
     
  echo  "start building policy kernel..."
  cd $KERNEL_SCRIPTS/policy
  ./build_policy_kernel.exp  $BOARD_TYPE $CPU $KERNEL_SOURCE  $BINARY_FORMAT $ALLOCATOR $ICACHE $DCACHE $POLICY $UART_MODE  >/dev/null  2>&1
                         
   
  cp $KERNEL_SCRIPTS/policy/build_policy_kernel_log  $THIS_LOG

  if [ ! -f $KERNEL_SOURCE/images/linux ] ; then
  echo  "Linux image fails to be generated.Error!"
  exit
  fi
    
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.policy
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.policy
  
  sleep 30
  
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
  
  echo  "mv kernel source back."
  mv $KERNEL_PATH $KERNEL_PATH_BAK 
  mkdir -p $KERNEL_PATH
  
  sleep 10

  fi
  #############################################################################################
  ########################## TEST ETHERNET ####################################################

  if [ $ethernet_test -eq 1  ] ; then
  echo  "Testing ethernet..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH   
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/ethernet
  ./build_ethernet_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./ethernet_test.exp  $BOARD_TYPE >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ethernet
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ethernet
  cp $KERNEL_SCRIPTS/ethernet/build_ethernet_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ethernet/ethernet_test_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ethernet/netperf_tcp_rr $THIS_LOG/
  cp $KERNEL_SCRIPTS/ethernet/netperf_tcp_stream $THIS_LOG/

  sleep 30
  
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
 
  fi
 
  #############################################################################################
  ########################## TEST ETHERNET in BUFFER ##########################################

  if [ $ethernet_in_buffer_test -eq 1  ] ; then
  echo  "Testing ethernet in buffer..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH   
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/ethernet
  ./build_ethernet_in_buffer_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./ethernet_test.exp  $BOARD_TYPE >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ethernet_in_buffer
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ethernet_in_buffer
  cp $KERNEL_SCRIPTS/ethernet/build_ethernet_in_buffer_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ethernet/ethernet_test_log  $THIS_LOG/ethernet_in_buffer_test_log
  cp $KERNEL_SCRIPTS/ethernet/netperf_tcp_rr $THIS_LOG/netperf_tcp_rr_in_buffer
  cp $KERNEL_SCRIPTS/ethernet/netperf_tcp_stream $THIS_LOG/netperf_tcp_stream_in_buffer

  sleep 30
  
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
 
  fi
  #############################################################################################
  ########################## TEST STRESS ######################################################
  
  if [ $stress_test -eq 1  ] ; then
  echo  "Testing stress ..."
 
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/stress
  ./build_stress_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./stress_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.stress
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.stress
  cp $KERNEL_SCRIPTS/stress/build_stress_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/stress/stress_test_log $THIS_LOG 
  cp $KERNEL_SCRIPTS/stress/ftp_test_log $THIS_LOG
  cp $KERNEL_SCRIPTS/stress/telnet_test_log $THIS_LOG
   
  sleep 30
    
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  #############################################################################################
  ########################## TEST SERIAL ####################################################
  
  if [ $serial_test -eq 1  ] ; then
  echo  "Testing serial..."
       
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd  $KERNEL_SCRIPTS/serial
  ./build_serial_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./serial_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.serial
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.serial
  cp $KERNEL_SCRIPTS/serial/build_serial_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/serial/serial_test_log $THIS_LOG/
  
  sleep 30
  
  
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
    
  fi
  
  if [ $serial_port_test -eq 1  ] ; then
  echo  "Testing serial port..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
    
  cd  $KERNEL_SCRIPTS/serial
  ./build_serial_port_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./serial_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.serial_port
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.serial_port
  cp $KERNEL_SCRIPTS/serial/build_serial_port_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/serial/serial_test_log $THIS_LOG/serial_port_test_log
  
  sleep 30
  
  
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
  
  fi

  #############################################################################################
  ########################## TEST SERIAL UART1 ################################################
  
  if [ $serial_uart1_test -eq 1  ] ; then
  echo  "Testing serial on uart1..."
       
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd  $KERNEL_SCRIPTS/serial
  ./build_serial_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./serial_uart1_test.exp /dev/ttyS1 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.serial_uart1
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.serial_uart1
  cp $KERNEL_SCRIPTS/serial/build_serial_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/serial/serial_uart1_test_log $THIS_LOG/
  
  sleep 30
  
  
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
    
  fi
 
  
  #############################################################################################
  ########################## TEST REBOOT ON RAMDISK ###########################################
  
  if [ $reboot_test -eq 1  ] ; then
  
  echo  "Testing reboot on RAMDISK..."
   
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd  $KERNEL_SCRIPTS/ramfs
  ./build_ramfs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./reboot_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.reboot
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.reboot
  cp $KERNEL_SCRIPTS/ramfs/build_ramfs_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ramfs/reboot_test_log $THIS_LOG  
  
  sleep 300
   
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
  
  fi
  
  #############################################################################################
  ########################## TEST KGDB #########################################################
  
   if [ $kgdb_test -eq 1  ] ; then
  
  echo  "Testing kgdb..."
 
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  
  cd $KERNEL_SCRIPTS/kgdb
  ./build_kgdb_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./kgdb_test.exp /dev/ttyS0 $KERNEL_SOURCE 10.100.4.50  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.kgdb
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.kgdb
  cp $KERNEL_SCRIPTS/kgdb/build_kgdb_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/kgdb/kgdb_test_log $THIS_LOG
  
  sleep 30
    
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  #############################################################################################
  ########################## TEST MODULE #######################################################
   
   if [ $module_test -eq 1  ] ; then
   
  echo  "Testing module..."
   
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/module
  ./build_module_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./module_test.exp $BOARD_TYPE  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.module
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.module
  cp $KERNEL_SCRIPTS/module/build_module_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/module/module_test_log $THIS_LOG  
  
  sleep 30
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  
  ########################## TEST RTC #########################################################
  
 if [ $rtc_test -eq 1  ] ; then
  echo  "Testing rtc..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/rtc
  ./build_rtc_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30  
  ./rtc_test.exp >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.rtc
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.rtc
  cp $KERNEL_SCRIPTS/rtc/build_rtc_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/rtc/rtc_test_log $THIS_LOG

  sleep 30

 if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
 
  #############################################################################################
  ########################## TEST NFS MOUNT ###################################################
  
  if [ $nfs_test -eq 1  ] ; then  
  
  echo  "Testing NFS mount ..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
   
 
  cd $KERNEL_SCRIPTS/nfs
  ./build_nfs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./nfs_test.exp >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.nfs
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.nfs
  cp $KERNEL_SCRIPTS/nfs/build_nfs_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/nfs/nfs_test_log $THIS_LOG 
 
  sleep 30

 
 if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
 fi
 
 fi
  
  #############################################################################################
  ########################## TEST MTD #########################################################
  
if [ $pnormtd_test -eq 1  ] ; then
  echo  "Testing pnormtd..."
  echo  "Switch SW6 to all on and unplug the nand flash board."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  rm -rf $KERNEL_PATH/uClinux-dist/romfs/

  cd $KERNEL_SCRIPTS/pnormtd
  ./build_pnormtd_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./pnormtd_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pnormtd
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.pnormtd
  cp $KERNEL_SCRIPTS/pnormtd/build_pnormtd_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pnormtd/pnormtd_test_log $THIS_LOG
  
  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  #############################################################################################
  ########################## TEST REBOOT ON JFFS2 FILE SYSTEM ##################################

  if [ $jffs2_reboot_test -eq 1  ] ; then
  
  echo  "Testing reboot on jffs2 file system ..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  rm -rf $KERNEL_PATH/uClinux-dist/romfs/

  cd $KERNEL_SCRIPTS/jffs2
  ./build_jffs2_kernel.exp $BOARD_TYPE $KERNEL_SOURCE   >/dev/null  2>&1
  sleep 30
  ./flash_images.exp >/dev/null  2>&1
  sleep 30
  ./jffs2_reboot_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SCRIPTS/jffs2/build_jffs2_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/jffs2/flash_images_log $THIS_LOG
  cp $KERNEL_SCRIPTS/jffs2/jffs2_reboot_test_log $THIS_LOG
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.jffs2_reboot
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.jffs2_reboot
  cp $KERNEL_SOURCE/images/vmImage $THIS_LOG/vmImage.jffs2_reboot
  cp $KERNEL_SOURCE/images/rootfs.jffs2 $THIS_LOG/rootfs.jffs2.jffs2_reboot
  
  sleep 50

  
  #############################################################################################
  ########################## TEST BOOT KERNEL-ONLY UIMAGE ######################################

  echo  "Testing boot kernel-only uImage ..."
  
  cd $KERNEL_SCRIPTS/jffs2
  ./boot_kernel_only_uimage.exp >/dev/null  2>&1
  cp $KERNEL_SCRIPTS/jffs2/boot_kernel_only_uimage_log $THIS_LOG

  sleep 300

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  #############################################################################################
  ########################## TEST JFFS2 FS #####################################################
 
 if [ $jffs2_fs_test -eq 1  ] ; then 
  echo  "Testing jffs2 fs..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  rm -rf $KERNEL_PATH/uClinux-dist/romfs/
  
  cd $KERNEL_SCRIPTS/jffs2
  ./build_jffs2_fs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./jffs2_fs_test.exp >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.jffs2_fs
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.jffs2_fs
  cp $KERNEL_SCRIPTS/jffs2/build_jffs2_fs_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/jffs2/jffs2_fs_test_log $THIS_LOG
    
  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

    ########################## TEST STRACE #########################################################
  
 if [ $strace_test -eq 1  ] ; then
  echo  "Testing strace..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/strace
  ./build_strace_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./strace_test.exp  /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.strace
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.strace
  cp $KERNEL_SCRIPTS/strace/build_strace_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/strace/strace_test_log $THIS_LOG

  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

   ########################## TEST MSH #########################################################
  
 if [ $msh_test -eq 1  ] ; then
  echo  "Testing msh..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/msh
  ./build_msh_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./msh_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.msh
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.msh
  cp $KERNEL_SCRIPTS/msh/build_msh_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/msh/msh_test_log $THIS_LOG

  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

 
   ########################## TEST PTHREAD #########################################################
  
 if [ $pthread_test -eq 1  ] ; then
  echo  "Testing pthread..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/pthread
  ./build_pthread_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./pthread_test.exp >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pthread
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.pthread
  cp $KERNEL_SCRIPTS/pthread/build_pthread_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pthread/pthread_test_log $THIS_LOG

  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

  ########################## TEST DPM #########################################################
  
 if [ $dpm_test -eq 1  ] ; then
  echo  "Testing dpm..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/dpm
  ./build_dpm_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./dpm_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.dpm
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.dpm
  cp $KERNEL_SCRIPTS/dpm/build_dpm_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/dpm/dpm_test_log $THIS_LOG

  sleep 30
 
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

#############################################################################################
########################## TEST DLL #########################################################
if [ $dll_test -eq 1 ] ; then
  echo "Testing dll..."

  if [ -z $targetip ] ; then
    targetip="10.100.4.50"
  fi

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/dll
  ./build_dll_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./dll_test.exp $targetip > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.dll
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.dll
  cp $KERNEL_SCRIPTS/dll/build_dll_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/dll/dll_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp >/dev/null  2>&1     
   sleep 10
  fi

fi


   ########################## TEST TIMER #########################################################
  
 if [ $timer_test -eq 1  ] ; then
  echo  "Testing timer..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/timer
  ./build_timer_kernel.exp $BOARD_TYPE $KERNEL_SOURCE 100  >/dev/null  2>&1
  sleep 30
  ./timer_tick_test.exp 100 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.timer100 
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.timer100
  
  ./build_timer_kernel.exp $BOARD_TYPE $KERNEL_SOURCE 250  >/dev/null  2>&1
  sleep 30
  ./timer_tick_test.exp 250 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.timer250
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.timer250
    
  ./build_timer_kernel.exp $BOARD_TYPE $KERNEL_SOURCE 1000  >/dev/null  2>&1
  sleep 30
  ./timer_tick_test.exp 1000 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.timer1000
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.timer1000
  cp $KERNEL_SCRIPTS/timer/build_timer_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/timer/timer_tick_test_log $THIS_LOG
  
  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

 
  ########################## TEST POUND #########################################################
  
 if [ $pound_test -eq 1  ] ; then
  echo  "Testing pound..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .


  cd $KERNEL_SCRIPTS/pound
  ./build_pound_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./pound_test.exp >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pound
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.pound
  cp $KERNEL_SCRIPTS/pound/build_pound_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pound/pound_test_log $THIS_LOG

  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

#############################################################################################
########################## TEST Sqlite ######################################################
if [ $sqlite_test -eq 1 ] ; then
  echo "Testing sqlite..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/sqlite
  ./build_sqlite_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./sqlite_test.exp > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.sqlite
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.sqlite
  cp $KERNEL_SCRIPTS/sqlite/build_sqlite_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/sqlite/sqlite_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi

#############################################################################################
########################## TEST Watchdog ######################################################
if [ $watchdog_test -eq 1 ] ; then
  echo "Testing watchdog..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/watchdog
  ./build_watchdog_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./watchdog_test.exp > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.watchdog
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.watchdog
  cp $KERNEL_SCRIPTS/watchdog/build_watchdog_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/watchdog/watchdog_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi

#############################################################################################
########################## TEST L1_memory ######################################################
if [ $module_l1_memory_test -eq 1 ] ; then
  echo "Testing module_l1_memory..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/l1_memory
  ./build_module_l1_memory_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./module_l1_memory_test.exp > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.module_l1_memory
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.module_l1_memory
  cp $KERNEL_SCRIPTS/l1_memory/build_module_l1_memory_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/l1_memory/module_l1_memory_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi

#############################################################################################
########################## TEST LTP #########################################################
if [ $ltp_test -eq 1 ] ; then
  echo "Testing LTP..."

  ltp_args=( [0]="1 1" [1]="1 2 0" [2]="1 2 1" [3]="2 1" [4]="2 2 0" [5]="2 2 1" )
  ltp_suf=(wb_slab wb_slob_np2 wb_slob_p2 wt_slab wt_slob_np2 wt_slob_p2)

  for i in 0 1 2 3 4 5
  do
    rm -rf $KERNEL_PATH/*
    cd $KERNEL_PATH
    echo "change dir to $KERNEL_PATH"
    cp -a  $KERNEL_PATH_BAK/*  .
  
    cd $KERNEL_SCRIPTS/ltp
    echo "change dir to $KERNEL_SCRIPTS/ltp"

    ./build_ltp_kernel.exp $BOARD_TYPE $KERNEL_SOURCE ${ltp_args[i]}> /dev/null 2>&1
  if [ $? ] ; then
    echo "ltp build kernel failed for $ltp_suf[i]"
    cp $KERNEL_SCRIPTS/ltp/build_ltp_kernel_log $THIS_LOG/build_ltp_kernel_log_${ltp_suf[i]}
    echo "ltp copy build_ltp_kernel_log done"
  else	
    # do if build kernel succeed
    echo "build_ltp_kernel.exp done"
    sleep 30
    ./ltp_auto_test.exp /dev/ttyS0 2 > /dev/null 2>&1
    echo "ltp_auto_test.exp done"
    ./ltp_compare_results_all.sh config/summary.base $KERNEL_SCRIPTS/ltp/test/logs/summary.new >> ltp_test_log
    ./ltp_decide_standard.pl config/summary.base $KERNEL_SCRIPTS/ltp/test/logs/summary.new
    if [ $? ] ; then
      echo "ltp test fail"
      echo "LTP Test ............[FAIL]" >> ltp_test_log
    else
      echo "ltp test pass"
      echo "LTP Test ............[FAIL]" >> ltp_test_log
    fi
  
    cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ltp_${ltp_suf[i]}
    echo "ltp copy linux.ltp done"
    cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ltp_${ltp_suf[i]}
    echo "ltp copy config.ltp done"
    cp $KERNEL_SCRIPTS/ltp/build_ltp_kernel_log $THIS_LOG/build_ltp_kernel_log_${ltp_suf[i]}
    echo "ltp copy build_ltp_kernel_log done"
    cp $KERNEL_SCRIPTS/ltp/test/logs/summary.new $THIS_LOG/ltp-summary_test_log_${ltp_suf[i]}
    echo "ltp copy summary done"
    cp $KERNEL_SCRIPTS/ltp/test/logs/detailed.new $THIS_LOG/ltp-detailed_test_log_${ltp_suf[i]}
    echo "ltp copy detailed done"
    cp $KERNEL_SCRIPTS/ltp/build_ltp_log $THIS_LOG/build_ltp_log_${ltp_suf[i]}
    cp $KERNEL_SCRIPTS/ltp/ltp_test_log $THIS_LOG/ltp_test_log_${ltp_suf[i]}
    echo "copy log files done"
   
    sleep 30
    
   
    if [ $reset_board -eq 1  ] ; then
     cd $KERNEL_SCRIPTS
     ./reset_board.exp   >/dev/null  2>&1       
     sleep 10
    fi
    # end, do if build kernel succeed
  fi

done

fi



  ##############################################################################################
  ####                    MANUAL TEST                                                 ############
  ################################################################################################
  
  #############################################################################################
  ########################## TEST ADSPI #########################################################
  
  if [ $spiadc_ndso_test -eq 1  ] ; then
  echo  "Testing SPIADC ndso ..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/spiadc
  ./build_ndso_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ndso 
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ndso
  cp $KERNEL_SCRIPTS/spiadc/build_ndso_kernel_log $THIS_LOG
  
  sleep 30  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  if [ $spiadc_awg_test -eq 1  ] ; then
  echo  "Testing SPIADC awg ..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/spiadc  
  ./build_awg_kernel.exp $BOARD_TYPE $KERNEL_SOURCE   >/dev/null  2>&1
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.awg  
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.awg
  cp $KERNEL_SCRIPTS/spiadc/build_awg_kernel_log $THIS_LOG
    
  sleep 30  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  #############################################################################################
  ########################## TEST PFLAGS #########################################################
 
 if [ $pflag_test -eq 1  ] ; then
 
  echo  "Testing pflags..."
  echo  "Switch SW5.1 to on."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
    
  cd $KERNEL_SCRIPTS/pflag
  ./build_pflags_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./pflags_test.exp $BOARD_TYPE >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pflags
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.pflags
  cp $KERNEL_SCRIPTS/pflag/build_pflags_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pflag/pflags_test_log $THIS_LOG 
  
  sleep 30
    
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

   #############################################################################################
  ########################## TEST PFbuttons #########################################################
 
 if [ $pfbutton_test -eq 1  ] ; then
 
  echo  "Testing pfbutton..."
  echo  "Switch SW5 to all on."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
    
  cd $KERNEL_SCRIPTS/pfbutton
  ./build_pfbutton_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./pfbutton_test.exp $BOARD_TYPE >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pfbutton
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.pfbutton
  cp $KERNEL_SCRIPTS/pfbutton/build_pfbutton_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pfbutton/pfbutton_test_log $THIS_LOG 
  
  sleep 30
    
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  #############################################################################################
  ########################## TEST AD9960 #########################################################
 
 if [ $ad9960_test -eq 1  ] ; then
 
  echo  "Testing ad9960..."
 
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
    
  cd $KERNEL_SCRIPTS/ad9960
  ./build_ad9960_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./ad9960_test.exp $BOARD_TYPE >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ad9960
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ad9960
  cp $KERNEL_SCRIPTS/ad9960/build_ad9960_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/ad9960/ad9960_test_log $THIS_LOG 
  
  sleep 30
    
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  #############################################################################################
  ########################## TEST AUDIO #########################################################
  
  if [ $audio_ad1836_test -eq 1  ] ; then
  
  echo  "Testing audio ad1836..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/audio
  ./build_ad1836_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./one_channel_audio_test.exp /dev/ttyS0 >/dev/null  2>&1
  sleep 30
  ./two_channel_audio_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ad1836   
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ad1836
  cp $KERNEL_SCRIPTS/audio/build_ad1836_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/audio/one_channel_audio_test_log $THIS_LOG/one_channel_audio_test_log.ad1836
  cp $KERNEL_SCRIPTS/audio/two_channel_audio_test_log $THIS_LOG/two_channel_audio_test_log.ad1836
    
  sleep 300

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  if [ $audio_ad73311_test -eq 1  ] ; then
  
  echo  "Testing audio ad73311..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  ./build_ad73311_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./one_channel_audio_test.exp /dev/ttyS0 >/dev/null  2>&1
  sleep 30
  ./two_channel_audio_test.exp /dev/ttyS0 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ad73311
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ad73311
  cp $KERNEL_SCRIPTS/audio/build_ad73311_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/audio/one_channel_audio_test_log $THIS_LOG/one_channel_audio_test_log.ad73311 
  cp $KERNEL_SCRIPTS/audio/two_channel_audio_test_log $THIS_LOG/one_channel_audio_test_log.ad73311
  
  sleep 300

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

  #############################################################################################
  ########################## TEST DPMC #####################################################
  if [ $dpmc_test -eq 1  ] ; then
  echo  "Testing dpmc..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/dpmc
  ./build_dpmc_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1  
  sleep 30
  ./dpmc_test.exp 200000000 80000000 850 >/dev/null  2>&1
   
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
  
  cd $KERNEL_SCRIPTS/dpmc
  sleep 30
  ./dpmc_test.exp 300000000 100000000 1000 >/dev/null  2>&1
    
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
  
  cd $KERNEL_SCRIPTS/dpmc
  sleep 30
  ./dpmc_test.exp 500000000 100000000 1200 >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.dpmc
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.dpmc
  cp $KERNEL_SCRIPTS/dpmc/build_dpmc_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/dpmc/dpmc_test_log $THIS_LOG
  
  sleep 30 
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

   #############################################################################################
  ########################## TEST JOYSTICK #####################################################
  if [ $joystick_test -eq 1  ] ; then
  echo  "Testing joystick..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/joystick
  ./build_joystick_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./joystick_test.exp >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.joystick
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.joystick
  cp $KERNEL_SCRIPTS/joystick/build_joystick_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/joystick/joystick_test_log $THIS_LOG
  
  
  sleep 30
 
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

  #############################################################################################
  ########################## TEST TWI #########################################################
  
  if [ $i2ctwi_test -eq 1  ] ; then
  echo  "Testing I2CTWI..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  
  cd $KERNEL_SCRIPTS/i2ctwi
  
  ./build_i2ctwi_lcd_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./i2ctwi_lcd_test.exp  >/dev/null  2>&1
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.i2ctwi_lcd
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.i2ctwi_lcd
  cp $KERNEL_SCRIPTS/i2ctwi/build_i2ctwi_lcd_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/i2ctwi/i2ctwi_lcd_test_log $THIS_LOG
  
  ./build_i2ctwi_keyboard_kernel.exp $BOARD_TYPE $KERNEL_SOURCE   >/dev/null  2>&1
  sleep 30
  ./i2ctwi_keyboard_test.exp  >/dev/null  2>&1
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.i2ctwi_keyboard
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.i2ctwi_keyboard
  cp $KERNEL_SCRIPTS/i2ctwi/build_i2ctwi_keyboard_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/i2ctwi/i2ctwi_keyboard_test_log $THIS_LOG
     
  sleep 30
 
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

  #############################################################################################
  ################# TEST BOOT KERNEL AND MOUNT JFFS2 FS FROM SPI FLASH ########################

  if [ $snormtd_test -eq 1  ] ; then
  echo  "Testing boot kernel and mount jffs2 file system from SPI flash ..."
 # Please set the chip selection to the 3rd one on both bf533 and bf537 board.

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  rm -rf $KERNEL_PATH/uClinux-dist/romfs/

  cd $KERNEL_SCRIPTS/snormtd
  ./build_snormtd_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./spi_flash_images.exp >/dev/null  2>&1
  sleep 30
  ./snormtd_reboot_test.exp >/dev/null  2>&1
  sleep 30

  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.snormtd
  cp $KERNEL_SCRIPTS/snormtd/build_snormtd_kernel_log $THIS_LOG
  cp $KERNEL_SOURCE/images/vmImage $THIS_LOG/vmImage.snormtd
  cp $KERNEL_SOURCE/images/rootfs.jffs2 $THIS_LOG/rootfs.jffs2.snormtd
  cp $KERNEL_SCRIPTS/snormtd/spi_flash_images_log $THIS_LOG
  cp $KERNEL_SCRIPTS/snormtd/snormtd_reboot_test_log $THIS_LOG

    
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  cd $KERNEL_SCRIPTS/snormtd
  ./build_snormtd_mount_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./snormtd_test.exp >/dev/null  2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.snormtd_mount
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.snormtd_mount  
  cp $KERNEL_SCRIPTS/snormtd/build_snormtd_mount_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/snormtd/snormtd_test_log $THIS_LOG  
  
  sleep 30
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

  #############################################################################################
  ########     Following tests are only for BF537 BOARD.         ##############################
  #############################################################################################
  
  ################# TEST CF CARD ##############################################################
  
if [ $cf_card_test -eq 1  ] ; then
  echo  "Testing CF card ..."
# Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board.

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/cfcard
  ./build_cf_card_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./cf_card_test.exp  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.cf_card
  cp $KERNEL_SOURCE/images/uImage  $THIS_LOG/uImage.cf_card
  cp $KERNEL_SOURCE/images/rootfs.ext2  $THIS_LOG/rootfs.ext2.cf_card
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.cf_card
  cp $KERNEL_SCRIPTS/cfcard/build_cf_card_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/cfcard/cf_card_test_log $THIS_LOG
  
  sleep 30

 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  ################# TEST IDE DEVICES ##############################################################
  
if [ $ide_harddisk_test -eq 1  ] ; then
  echo  "Testing ide harddisk ..."
 # Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board.

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH  
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/ide
  ./build_ide_harddisk_cdrom_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./ide_harddisk_test.exp  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ide_harddisk_cdrom
  cp $KERNEL_SOURCE/images/uImage  $THIS_LOG/uImage.ide_harddisk_cdrom
  cp $KERNEL_SOURCE/images/rootfs.ext2  $THIS_LOG/rootfs.ext2.ide_harddisk_cdrom
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ide_harddisk_cdrom
  cp $KERNEL_SCRIPTS/ide/build_ide_harddisk_cdrom_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/ide/ide_harddisk_test_log $THIS_LOG 

  sleep 30 
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi
  
  if [ $ide_cdrom_test -eq 1  ] ; then
  echo  "Testing ide cdrom ..."
 # Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board.

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH  
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/ide
  ./build_ide_harddisk_cdrom_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  
  sleep 30
  ./ide_cdrom_test.exp  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ide_harddisk_cdrom
  cp $KERNEL_SOURCE/images/uImage  $THIS_LOG/uImage.ide_harddisk_cdrom
  cp $KERNEL_SOURCE/images/rootfs.ext2  $THIS_LOG/rootfs.ext2.ide_harddisk_cdrom
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ide_harddisk_cdrom
  cp $KERNEL_SCRIPTS/ide/build_ide_harddisk_cdrom_kernel_log $THIS_LOG 
  cp $KERNEL_SCRIPTS/ide/ide_cdrom_test_log $THIS_LOG

  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
 
  fi
  #############################################################################################
  ################# TEST WIRELESS CARD ##############################################################
  
if [ $wireless_test -eq 1  ] ; then

  echo  "Testing wireless card ..."
 # Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board.

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH   
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/wireless
  ./build_wireless_network_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./wireless_test.exp  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.wireless
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.wireless
  cp $KERNEL_SCRIPTS/wireless/build_wireless_network_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/wireless/wireless_network_test_log $THIS_LOG
  
  sleep 300
   

  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi

  fi

 #############################################################################################
 ########################## TEST YAFFS #########################################################
  
if [ $yaffs_test -eq 1  ] ; then

  echo  "Testing YAFFS..."
  #Switch SW6 to on on off on, SW5 all on and plug the nand flash board.

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/yaffs
  ./build_yaffs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE >/dev/null  2>&1
  sleep 30
  ./yaffs_test.exp /dev/ttyS0  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.yaffs
  cp $KERNEL_SOURCE/images/uImage  $THIS_LOG/uImage.yaffs
  cp $KERNEL_SOURCE/images/rootfs.yaffs2  $THIS_LOG/rootfs.yaffs2.yaffs
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.yaffs
  cp $KERNEL_SCRIPTS/yaffs/build_yaffs_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/yaffs/yaffs_test_log $THIS_LOG

  sleep 30
   
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1 
   sleep 10
  fi
 

  fi
   
  #############################################################################################
  ########################## TEST PPIFCD #####################################################
  if [ $ppifcd_test -eq 1  ] ; then
  echo  "Testing ppifcd..."
  
  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .
  
  cd $KERNEL_SCRIPTS/ppifcd
  ./build_ppifcd_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  >/dev/null  2>&1
  sleep 30
  ./ppifcd_test.exp $BOARD_TYPE  >/dev/null  2>&1
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ppifcd
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.ppifcd
  cp $KERNEL_SCRIPTS/ppifcd/build_ppifcd_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/ppifcd/ppifcd_test_log $THIS_LOG
  cp $KERNEL_SCRIPTS/ppifcd/img.bmp $THIS_LOG
  
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp   >/dev/null  2>&1     
   sleep 10
  fi

  fi


#############################################################################################
########################## TEST USB Host ####################################################
if [ $usbhost_test -eq 1 ] ; then
  echo "Testing usbhost..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/usbhost
  ./build_usbhost_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./usbhost_test.exp > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.usbhost
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.usbhost
  cp $KERNEL_SCRIPTS/usbhost/build_usbhost_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/usbhost/usbhost_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi


#############################################################################################
########################## TEST USB Network #################################################
if [ $usbnet_test -eq 1 ] ; then
  echo "Testing usbnet..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/usbnet
  ./build_usbnet_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./usbnet_test.exp > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.usbnet
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.usbnet
  cp $KERNEL_SCRIPTS/usbnet/build_usbnet_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/usbnet/usbnet_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi



#############################################################################################
########################## TEST CoreB #######################################################
if [ $coreb_test -eq 1 ] ; then
  echo "Testing coreb..."

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/coreb
  ./build_coreb_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./coreb_test.exp > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.coreb
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.coreb
  cp $KERNEL_SCRIPTS/coreb/build_coreb_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/coreb/coreb_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi


#############################################################################################
########################## TEST L1 application ##############################################
if [ $l1_app -eq 1 ] ; then
  echo "Testing L1 application..."

  if [ -z $targetip ] ; then
    targetip="10.100.4.50"
  fi

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/l1_app
  ./build_l1_app_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./test_l1_app.exp $targetip > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.l1_app
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.l1_app
  cp $KERNEL_SCRIPTS/l1_app/build_l1_app_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/l1_app/l1_app_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi


#############################################################################################
########################## TEST Sigqueue ####################################################
if [ $coreb_test -eq 1 ] ; then
  echo "Testing Sigqueue..."

  if [ -z $targetip ] ; then
    targetip="10.100.4.50"
  fi

  rm -rf $KERNEL_PATH/*
  cd $KERNEL_PATH
  cp -a  $KERNEL_PATH_BAK/*  .

  cd $KERNEL_SCRIPTS/sigqueue
  ./build_sigqueue_kernel.exp $BOARD_TYPE $KERNEL_SOURCE > /dev/null 2>&1
  sleep 30
  ./test_sigqueue.exp $targetip > /dev/null 2>&1

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.sigqueue
  cp $KERNEL_SOURCE/linux-2.6.x/.config $THIS_LOG/config.sigqueue
  cp $KERNEL_SCRIPTS/sigqueue/build_sigqueue_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/sigqueue/sigqueue_test_log $THIS_LOG
    
  sleep 30
  
 
  if [ $reset_board -eq 1  ] ; then
   cd $KERNEL_SCRIPTS
   ./reset_board.exp  >/dev/null  2>&1     
   sleep 10
  fi

fi




echo  "Testing Done."
