#!/bin/sh
########################################################################################################################
######### To run this script, please first set following uboot varibles properly on your target board  #################
######### set  bootargs  bootfile linux                                                                #################
######### set  bootargs  loadaddr 2000000                                                     	       #################
######### set  bootcmd   run tftpboot                                                                  #################
######### set  tftpboot  'tftp 0x2000000 linux;bootelf'                                                #################
######### set  ipaddr    10.100.4.50  (set your board ip here)                                         #################
######### set  serverip  10.100.4.174 (set your server ip here)                                        #################
########################################################################################################################

############### Set up the testing environment. Edit the following variables to suit your situation. ###################

USER=/home/test
CHECKOUT=$USER/checkouts
KERNEL_PATH=$CHECKOUT/kernel
KERNEL_PATH_BAK=$CHECKOUT/kernel_bak
KERNEL_SOURCE=$KERNEL_PATH/uClinux-dist
KERNEL_SOURCE_BAK=$KERNEL_PATH_BAK/uClinux-dist
KERNEL_SCRIPTS=$KERNEL_SOURCE/testsuites
BASELINE=standard
LOG_DIR=$USER/test_scripts/kernel/logs/all
BOARD_CONFIG=$1

########################################### Please don't edit anything below this line.###################################

if [ $# -lt 4 ] ; then
  echo "Please input BOARD_CONFIG [KERNEL_SOURCE BINARY_FORMAT POLICY VCO_MULT CCLK_DIV SCLK_DIV] values: "
  echo "The BOARD_CONFIG should be BF533-STAMP-STD, BF537-STAMP-STD, BF537-STAMP-IDE,etc."
  echo "For example:./kernel_test BF537-STAMP-STD /home/test/checkouts/kernel/uClinux-dist flat write_through."
  exit
fi

if [ $# -gt 1 ] ; then
  KERNEL_SOURCE=$2
  echo "##### KERNEL_SOURCE is $2"
 fi
 
if [ $# -gt 2 ] ; then
  BINARY_FORMAT=$3
  LOG_DIR=($LOG_DIR)_$3
  echo "##### BINARY_FORMAT is $3"
 fi
 
 if [ $# -gt 3 ] ; then
  POLICY=$4
  LOG_DIR=($LOG_DIR)_$4
  echo "##### POLICY is $4"
 fi

if [ $# -gt 4 ] ; then
  VCO_MULT=$5
  CCLK_DIV=$6
  SCLK_DIV=$7
fi


###### See if kernel has been checked out.##################################################
 
if [ ! -d $KERNEL_PATH_BAK ] ; then
  echo  "No kernel source in $KERNEL_PATH_BAK."
  exit
fi
if [ ! -d $KERNEL_PATH ] ; then
  mkdir -p $KERNEL_PATH
  echo  "Testing is doing against the kernel source in $KERNEL_PATH."
fi

# KERNEL_SCRIPTS/change_clk.exp $BOARD_TYPE $VCO_MULT $CCLK_DIV $SCLK_DIV

######## Set the default value for the test cases

         build_policy=0
	ethernet_test=0
	  stress_test=0
	  serial_test=0
	  reboot_test=0
	     rtc_test=0
	     nfs_test=0
	    kgdb_test=0
	  module_test=0
	 pnormtd_test=0
    jffs2_reboot_test=0 
	jffs2_fs_test=0
	   adspi_test=0
	   audio_test=0
	  pflags_test=0
	    dpmc_test=0
	     twi_test=0
       spi_flash_test=0
	 cf_card_test=0
	     ide_test=0
wireless_network_test=0
	   yaffs_test=0

#######  BOARD CONFIG DEFINITION      ###################################################### 

if [ $BOARD_CONFIG = "BF537-STAMP-STD" ] ; then
 
   echo  "Testing is doing with the config $BOARD_CONFIG."
   
   BOARD_TYPE=BF537-STAMP
   
         build_policy=1
	ethernet_test=0
	  stress_test=1
	  serial_test=1
	  reboot_test=1
	     rtc_test=1
	     nfs_test=1
	    kgdb_test=0
	  module_test=1
	 pnormtd_test=1
    jffs2_reboot_test=0 
	jffs2_fs_test=0
	   adspi_test=0
	   audio_test=0
	  pflags_test=0
	    dpmc_test=0
	     twi_test=0
       spi_flash_test=0
	 cf_card_test=0
	     ide_test=0
wireless_network_test=0
	   yaffs_test=0
fi

if [ $BOARD_CONFIG = "BF533-STAMP-STD" ] ; then
 
   echo  "Testing is doing with the config $BOARD_CONFIG."
   
   BOARD_TYPE=BF533-STAMP
   
         build_policy=0
	ethernet_test=1
	  stress_test=1
	  serial_test=1
	  reboot_test=0
	     rtc_test=0
	     nfs_test=0
	    kgdb_test=0
	  module_test=0
	 pnormtd_test=0
    jffs2_reboot_test=0  
	jffs2_fs_test=0
	   adspi_test=0
	   audio_test=0
	  pflags_test=0
	    dpmc_test=0
	     twi_test=0
       spi_flash_test=0
	
fi
 
####### Build and run the tests      #######################################################

TIMESTAMP=`date +%Y_%b_%d_%H_%M`
THIS_LOG=$LOG_DIR/$TIMESTAMP
mkdir -p $THIS_LOG

export PATH=/opt/uClinux/bfin-uclinux/bin:/opt/uClinux/bfin-elf/bin:$PATH

cd  $KERNEL_SOURCE_BAK/testsuites
chmod +x */*.exp

  #############################################################################################
  ########################## BUILD POLICY KERNEL ##############################################
  
  if [ $build_policy -eq 1  ] ; then
  
  rm -rf $KERNEL_PATH
  echo  "mv kernel source "
  mv $KERNEL_PATH_BAK $KERNEL_PATH
     
  echo  "start building policy kernel..."
  cd $KERNEL_SCRIPTS/policy
  ./build_policy_kernel.exp  $BOARD_TYPE $KERNEL_SOURCE $BINARY_FORMAT $POLICY
    
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.policy
  cp $KERNEL_SCRIPTS/policy/build_policy_kernel_log  $THIS_LOG
  
  echo  "mv kernel source back."
  mv $KERNEL_PATH $KERNEL_PATH_BAK 
  mkdir -p $KERNEL_PATH
  
  fi
  #############################################################################################
  ########################## TEST ETHERNET ####################################################

  if [ $ethernet_test -eq 1  ] ; then
  echo  "Testing ethernet..."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd $KERNEL_SCRIPTS/ethernet
  ./build_ethernet_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./ethernet_test.exp
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ethernet
  cp $KERNEL_SCRIPTS/ethernet/build_ethernet_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ethernet/ethernet_test_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ethernet/netperf_tcp_rr $THIS_LOG/
  cp $KERNEL_SCRIPTS/ethernet/netperf_tcp_stream $THIS_LOG/

  sleep 30

  fi
  
  
  
  #############################################################################################
  ########################## TEST STRESS ######################################################
  
  if [ $stress_test -eq 1  ] ; then
  echo  "Testing stress ..."
 
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .

  cd $KERNEL_SCRIPTS/stress
  ./build_stress_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  
  ./stress_test.exp /dev/ttyS0 
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.stress
  cp $KERNEL_SCRIPTS/stress/build_stress_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/stress/stress_test_log $THIS_LOG 
  cp $KERNEL_SCRIPTS/stress/ftp_test_log $THIS_LOG
   cp $KERNEL_SCRIPTS/stress/telnet_test_log $THIS_LOG
   
  sleep 30
  fi
  
  #############################################################################################
  ########################## TEST SERIAL ####################################################
  
  if [ $serial_test -eq 1  ] ; then
  echo  "Testing serial..."
       
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd  $KERNEL_SCRIPTS/serial
  ./build_serial_kernel.exp $BOARD_TYPE $KERNEL_SOURCE 
  ./serial_test.exp /dev/ttyS0 
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.serial
  cp $KERNEL_SCRIPTS/serial/build_serial_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/serial/serial_test_log $THIS_LOG/
  
  sleep 30
    
  fi
  #############################################################################################
  ########################## TEST REBOOT ON RAMDISK ###########################################
  
  if [ $reboot_test -eq 1  ] ; then
  
  echo  "Testing reboot on RAMDISK..."
   
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd  $KERNEL_SCRIPTS/ramfs
  ./build_ramfs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./reboot_test.exp /dev/ttyS0 
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.reboot
  cp $KERNEL_SCRIPTS/ramfs/build_ramfs_kernel_log  $THIS_LOG
  cp $KERNEL_SCRIPTS/ramfs/reboot_test_log $THIS_LOG  
  
  sleep 30
  
  fi
  #############################################################################################
  ########################## TEST KGDB #########################################################
  
   if [ $kgdb_test -eq 1  ] ; then
  
  echo  "Testing kgdb..."
 
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  
  cd $KERNEL_SCRIPTS/kgdb
  ./build_kgdb_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./kgdb_test.exp /dev/ttyS0 $KERNEL_SOURCE 10.100.4.50  
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.kgdb
  cp $KERNEL_SCRIPTS/kgdb/build_kgdb_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/kgdb/kgdb_test_log $THIS_LOG
  
  sleep 30
  
  fi
  
  #############################################################################################
  ########################## TEST MODULE #######################################################
   
   if [ $module_test -eq 1  ] ; then
   
  echo  "Testing module..."
   
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd $KERNEL_SCRIPTS/module
  ./build_module_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./module_test.exp $BOARD_TYPE
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.module
  cp $KERNEL_SCRIPTS/module/build_module_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/module/module_test_log $THIS_LOG  
  
  sleep 30
  fi
  ########################## TEST RTC #########################################################
  
 if [ $rtc_test -eq 1  ] ; then
  echo  "Testing rtc..."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .


  cd $KERNEL_SCRIPTS/rtc
  ./build_rtc_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./rtc_test.exp
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.rtc
  cp $KERNEL_SCRIPTS/rtc/build_rtc_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/rtc/rtc_test_log $THIS_LOG

  sleep 30
 fi
  #############################################################################################
  ########################## TEST NFS MOUNT ###################################################
  
  if [ $nfs_test -eq 1  ] ; then  
  
  echo  "Testing NFS mount ..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
   
 
  cd $KERNEL_SCRIPTS/nfs
  ./build_nfs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./nfs_test.exp
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.nfs
  cp $KERNEL_SCRIPTS/nfs/build_rtc_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/nfs/nfs_test_log $THIS_LOG 
 
  sleep 30
 fi
  
  #############################################################################################
  ########################## TEST MTD #########################################################
  
if [ $pnormtd_test -eq 1  ] ; then
  echo  "Testing pnormtd..."
  echo  "Switch SW6 to all on and unplug the nand flash board."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .

  cd $KERNEL_SCRIPTS/pnormtd
  ./build_pnormtd_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./pnormtd_test.exp /dev/ttyS0 
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pnormtd
  cp $KERNEL_SCRIPTS/pnormtd/build_pnormtd_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pnormtd/test_pnormtd_log $THIS_LOG
  
  sleep 30

  fi
  
  #############################################################################################
  ########################## TEST REBOOT ON JFFS2 FILE SYSTEM ##################################

  if [ $jffs2_reboot_test -eq 1  ] ; then
  
  echo  "Testing reboot on jffs2 file system ..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .


  cd $KERNEL_SCRIPTS/jffs2
  ./build_jffs2_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./flash_images.exp
  ./jffs2_reboot_test.exp /dev/ttyS0
  
  cp $KERNEL_SCRIPTS/jffs2/build_jffs2_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/jffs2/flash_images_log $THIS_LOG
  cp $KERNEL_SCRIPTS/jffs2/jffs2_reboot_test_log $THIS_LOG
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.reboot_jffs2
  cp $KERNEL_SOURCE/images/vmImage $THIS_LOG/vmImage.reboot_jffs2
  cp $KERNEL_SOURCE/images/jffs2.img $THIS_LOG/jffs2.image.reboot_jffs2
  
  sleep 500

  
  #############################################################################################
  ########################## TEST BOOT KERNEL-ONLY UIMAGE ######################################

  echo  "Testing boot kernel-only uImage ..."
  
  cd $KERNEL_SCRIPTS/jffs2
  ./boot_kernel_only_uimage.exp
  cp $KERNEL_SCRIPTS/jffs2/boot_kernel_only_uimage_log $THIS_LOG

  sleep 30
 
 fi
 
  
  #############################################################################################
  ########################## TEST JFFS2 FS #####################################################
 
 if [ $jffs2_fs_test -eq 1  ] ; then 
  echo  "Testing jffs2 fs..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd $KERNEL_SCRIPTS/jffs2
  ./build_jffs2_fs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./jffs2_fs_test.exp
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.jffs2_fs
  cp $KERNEL_SCRIPTS/jffs2/build_jffs2_fs_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/jffs2/jffs2_fs_test_log $THIS_LOG
    
  sleep 30
  fi
  ##############################################################################################
  ####                    MANUAL TEST                                                 ############
  ################################################################################################
  
  #############################################################################################
  ########################## TEST ADSPI #########################################################
  
  if [ $adspi_test -eq 1  ] ; then
  echo  "Testing ADSPI..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd $KERNEL_SCRIPTS/adspi
  ./build_adspi_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./adspi_test.exp
    
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.adspi 
  cp $KERNEL_SCRIPTS/adspi/build_adspi_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/adspi/adspi_test_log $THIS_LOG
  
   sleep 30
   
   fi
  
  #############################################################################################
  ########################## TEST PFLAGS #########################################################
 
 if [ $pflags_test -eq 1  ] ; then
 
  echo  "Testing pflags..."
  echo  "Switch SW5.1 to on."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
    
  cd $KERNEL_SCRIPTS/pflags
  ./build_pflags_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./pflags_test.exp $BOARD_TYPE
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.pflags
  cp $KERNEL_SCRIPTS/pflags/build_pflags_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/pflags/pflags_test_log $THIS_LOG 
  
  sleep 30
    
  fi
 
  #############################################################################################
  ########################## TEST AUDIO #########################################################
  
  if [ $audio_test -eq 1  ] ; then
  
  echo  "Testing audio..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd $KERNEL_SCRIPTS/audio
  ./build_audio_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./test_audio /dev/ttyS0 
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.audio
  cp $KERNEL_SCRIPTS/audio/build_audio_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/audio/test_audio_log $THIS_LOG 
  
  sleep 30

  fi
  #############################################################################################
  ########################## TEST DPMC #####################################################
  if [ $dpmc_test -eq 1  ] ; then
  echo  "Testing dpmc..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  cd $KERNEL_SCRIPTS/dpmc
  ./build_dpmc_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./dpmc_test.exp
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.dpmc
  cp $KERNEL_SCRIPTS/dpmc/build_dpmc_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/dpmc/dpmc_test_log $THIS_LOG
  
  
  sleep 30
  fi
  #############################################################################################
  ########################## TEST TWI #########################################################
  
  if [ $twi_test -eq 1  ] ; then
  echo  "Testing TWI..."
  
  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .
  
  
  cd $KERNEL_SCRIPTS/twi
  ./build_twi_keyboard_kernel.exp $BOARD_TYPE $KERNEL_SOURCE  
  ./build_twi_lcd_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./twi_lcd_test.exp > test_twi_lcd_log

  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.twi_keyboard
  cp $KERNEL_SCRIPTS/twi/build_twi_keyboard_kernel_log $THIS_LOG
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.twi_lcd
  cp $KERNEL_SCRIPTS/twi/build_twi_lcd_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/twi/test_twi_lcd_log $THIS_LOG

  
  sleep 30
  fi
  #############################################################################################
  ################# TEST BOOT KERNEL AND MOUNT JFFS2 FS FROM SPI FLASH ########################

  if [ $spi_flash_test -eq 1  ] ; then
  echo  "Testing boot kernel and mount jffs2 file system from SPI flash ..."
  echo  "Please switch the SW16 mode to 3."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .


  cd $KERNEL_SCRIPTS/snormtd
  ./build_spi_flash_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./spi_flash_images.exp
  
  cp $KERNEL_SCRIPTS/snormtd/build_spi_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/snormtd/spi_flash_images_log $THIS_LOG
  
  cp $KERNEL_SOURCE/images/vmImage $THIS_LOG/vmImage.snormtd
  cp $KERNEL_SOURCE/images/jffs2.img $THIS_LOG/jffs2.img.snormtd
  
  sleep 30
fi

  #############################################################################################
  ########     Following tests are only for BF537 BOARD.         ##############################
  #############################################################################################
  
  ################# TEST CF CARD ##############################################################
  
if [ $cf_card_test -eq 1  ] ; then
  echo  "Testing CF card ..."
  echo  "Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board ."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .

  cd $KERNEL_SCRIPTS/cf_card
  ./build_cf_card_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./cf_card_test.exp  
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.cf_card
  cp $KERNEL_SCRIPTS/cf_card/build_cf_card_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/cf_card/cf_card_test_log $THIS_LOG
  
  sleep 30
  fi
  ################# TEST IDE DEVICES ##############################################################
  
if [ $ide_test -eq 1  ] ; then
  echo  "Testing ide harddisk and cdrom ..."
  echo  "Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board ."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .

  cd $KERNEL_SCRIPTS/ide
  $KERNEL_SCRIPTS/build_ide_harddisk_cdrom_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./ide_harddisk_test.exp 
  ./ide_cdrom_test.exp
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.ide_harddisk_cdrom
  cp $KERNEL_SCRIPTS/build_ide_harddisk_cdrom_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/ide/ide_harddisk_test_log $THIS_LOG
  cp $KERNEL_SCRIPTS/ide/ide_cdrom_test_log $THIS_LOG

  sleep 30
 fi
  #############################################################################################
  ################# TEST WIRELESS CARD ##############################################################
  
if [ $wireless_network_test -eq 1  ] ; then

  echo  "Testing wireless card ..."
  echo  "Please switch the SW5 to all off,SW6 to on on off off,and plug the add-on board ."

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .

  cd $KERNEL_SCRIPTS/wireless_network
  ./build_wireless_network_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./wireless_network_test.exp  
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.wireless
  cp $KERNEL_SCRIPTS/wireless_network/build_wireless_network_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/wireless_network/wireless_network_test_log $THIS_LOG
  
  sleep 300
   
 fi
 
 #############################################################################################
 ########################## TEST YAFFS #########################################################
  
if [ $yaffs_test -eq 1  ] ; then

  echo  "Testing YAFFS..."
  echo  "Switch SW6 to on on off on and plug the nand flash board.(128)"

  rm -rf $CHECKOUT/kernel/*
  cd $CHECKOUT/kernel
  echo  "cp kernel source "
  cp -a  $CHECKOUT/kernel_bak/*  .

  cd $KERNEL_SCRIPTS/yaffs
  ./build_yaffs_kernel.exp $BOARD_TYPE $KERNEL_SOURCE
  ./test_yaffs /dev/ttyS0 
  
  cp $KERNEL_SOURCE/images/linux $THIS_LOG/linux.yaffs
  cp $KERNEL_SCRIPTS/yaffs/build_yaffs_kernel_log $THIS_LOG
  cp $KERNEL_SCRIPTS/yaffs/test_yaffs_log $THIS_LOG

  sleep 30
 
 
 fi
   

 
 
