#!/usr/bin/expect

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 5

step "Start DLL testing"

set timeout 2

step "Clean src directory\n"
spawn make clean -C src
while 1 {
   expect {

      "*error*" {
         send_log "\nClean src/ failed\n"
         send_user "\nClean src/ failed\n"
         exit
      }

      eof {
         send_log "\nClean src/.\n"
         send_user "\nClean src/. \n"
         break
      }

      timeout {
         break
      }
   }
}

step "Build test program\n"
spawn make -C src
while 1 {
   expect {

      "*error*" {
         send_log "\nBuild test program failed\n"
         send_user "\nBuild test program failed\n"
         exit
      }

      eof {
         send_log "\nBuild test program done\n"
         send_user "\nBuild test program done\n"
         break
      }

      timeout {
         break
      }
   }
}

set spawn_id $kermit_spawn_id

send "ifconfig eth0 $ipaddr up\r"
sleep 15

set timeout 100
step "Copy testcase to target board\n"
spawn rcp src/libhelloworld.so root@$ipaddr:/lib/.
while 1 {
   expect {

      "*connect*" {
         send_log "\nCopy libhelloworld.so to target board failed\n"
         send_user "\nCopy libhelloworld.so to target board failed\n"
         exit
      }

      eof {
         send_log "\nCopy libhelloworld.so to target board done\n"
         send_user "\nCopy libhelloworld.so to target board done\n"
         break
      }

      timeout {
         break
      }
   }
}

spawn rcp src/test_dll root@$ipaddr:/.
while 1 {
   expect {

      "*connect*" {
         send_log "\nCopy test_dll to target board failed\n"
         send_user "\nCopy test_dll to target board failed\n"
         exit
      }

      eof {
         send_log "\nCopy test_dll to target board done\n"
         send_user "\nCopy test_dll to target board done\n"
         break
      }

      timeout {
         break
      }
   }
}

set spawn_id $kermit_spawn_id
set timeout 2
set testres    0
send "./test_dll\r"
while 1 {
   expect {

      "hello" {
         send_log "\nTest get hello\n"
         send_user "\nTest get hello\n"
         incr testres
         if { $testres == 2 } {
            send_log "\nDLL test pass\n"
            send_user "\nDLL test pass\n"
            break
         }
      }

      "get 2" {
         send_log "\nTest get correct return value\n"
         send_user "\nTest get correct return value\n"
         incr testres
         if { $testres == 2 } {
            send_log "\n$TITLE ............\[PASS\]\n"
            send_user "\n$TITLE ............\[PASS\]\n"
            break
         }
      }
      timeout {
         send_user "\ntest timeout\n"
         break
      }
   }
}

if { $testres != 2 } {
   send_log "\n$TITLE ............\[FAIL\]\n"
   send_user "\n$TITLE ............\[FAIL\]\n"
}

log_file
send_user "\n$TITLE is finished.\n"

exit
