#
# Makefile for m68knommu specific library files..
#

lib-y	:= ashldi3.o ashrdi3.o lshrdi3.o \
	   muldi3.o mulsi3.o divsi3.o udivsi3.o modsi3.o umodsi3.o \
	   checksum.o semaphore.o memcpy.o memset.o \
	   cmpdi2.o divdi3.o negdi2.o moddi3.o udivmoddi4.o gcc_bcmp.o
