#!/bin/sh

USER=/home/test
KERNEL_SCRIPTS=$USER/test_scripts/kernel

cd $KERNEL_SCRIPTS/
./test_runtime_control   &

QUIT=2

while [ $QUIT -gt 1 ]
do

# /home/test/tinderclient/build_shellscript  --buildcf /home/test/tinderclient/blackfin_kernel.buildcf   --build BF533-STAMP-STD   --tree uClinux_Head   --once

( echo "$KERNEL_SCRIPTS/start_kernel_test >  $KERNEL_SCRIPTS/kernel_test_log 2>&1 " ) | sh

sleep 1000

done
