#!/bin/sh

QUIT=2

while [ $QUIT -gt 1 ]
do

test_pid=`ps aux | grep .exp | head -1 | awk '{print $2}'`
test_command=`ps aux | grep .exp | head -1 | awk '{print $11}'`

if [ "$test_pid" != "" ] && test "$test_command" && [ "$test_command" == 'grep' ] ; then

 # echo "No test script is running." 
 sleep 1200 

else

 script_name=`ps aux | grep .exp | head -1 | awk '{print $12}'`
 if [ "$script_name" == "./qt_source_test.exp" ] ; then
     sleep 7200
 else
     sleep 3600
 fi

 test_name=`{ ps -p $test_pid | tail -1 | awk '{print $4}' ;}  2> /dev/null`
 if [ "$test_pid" != "" ] && [ "$test_name" != 'CMD' ] ; then
   echo "`date`. Process: $test_name, ID: $test_pid to be killed."
   kill -9 $test_pid
 fi

fi


kernel_test_pid=`ps aux | grep -w kernel_test | head -1 | awk '{print $2}'`
kernel_test_command=`ps aux | grep -w kernel_test | head -1 | awk '{print $11}'`

if [ "$kernel_test_pid" != "" ] && test "$kernel_test_command" && [ "$kernel_test_command" == 'grep' ] ; then

kill -9 $$

fi

done

