#!/bin/bash
#
# This file is aimed to test Dynamic Power Management(the official website:http://dynamicpower.sourceforge.net/)
#


#create a op
cd /sys/dpm/op
echo create test 400 4 > control

#create a policy, its name is demo
cd /sys/dpm/policy
echo create demo test test test test test test test test test test test test > control

# set a policy 
cd /sys/dpm/policy
echo set demo > control

# enable the policy
cd /sys/dpm
echo enable > control
echo "DPM policy is installed!"
