#!/usr/bin/expect

#
#Test program to test the msh patch.
#

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

set targetip 10.100.4.2
set serverip 10.100.4.174

set argc [llength $argv]
if { $argc < 1} {
   puts "Usage:  $argv0 tty-device \[srcdir targetip serverip\]"
   puts "   where tty-device is something like /dev/ttyS0"
   puts ""
   exit
}
# grab the user specified parameters.

if { $argc >= 2} {
   set srcdir             [lindex $argv 1]
}

if { $argc >= 3} {
   set targetip           [lindex $argv 2]
}
if { $argc >= 4} {
   set serverip           [lindex $argv 3]
}


step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 3
step "Start $TITLE\r"

set timeout 10
set case_num 0

spawn rcp ./dpm_testcase root@$targetip:/
set spawn_id $kermit_spawn_id

send -s "chmod +x /dpm_testcase\r"
expect ">"
incr case_num
send -s "sh /dpm_testcase\r"
while 1 {
expect {
        "DPM is now enabled" {
                expect "DPM policy is installed!"
                send_log "\rCase $case_num ...PASS\r"
                break
        }
        timeout {
                send_log "\rCase $case_num ...FAIL\r"
                send_log "$TITLE ............\[FAIL\]\r"
                exit
        }
 }
}

send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file

