#!/usr/bin/expect

#
#Test program to test the msh patch.
#

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 3
step "Start $TITLE\r"

set timeout 10
set case_num 0

send "ifconfig eth0 $targetip\r"
while 1 {
   sleep 3
   expect {
      ">" {
         puts "ifconfig set success.\n"
         break
      }

      timeout {
            puts "Fail ifconfig. "
            break
         }
     }
}

spawn rcp ./dpm_testcase root@$targetip:/
set spawn_id $kermit_spawn_id

send -s "chmod +x /dpm_testcase\r"
expect ">"
incr case_num
send -s "sh /dpm_testcase\r"
while 1 {
expect {
        "DPM is now enabled" {
                expect "DPM policy is installed!"
                case_pass $case_num
                break
        }
        timeout {
                case_fail $case_num
                exit
        }
 }
}

send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file

