/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define default host */
#define DEFAULT_HOST "localhost"

/* Define default port */
#define DEFAULT_PORT "6600"

/* Define to use iconv */
/* #undef HAVE_ICONV */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
/* #undef HAVE_LANGINFO_CODESET */

/* Define to 1 if you have the `iconv' library (-liconv). */
/* #undef HAVE_LIBICONV */

/* Define for locale */
/* #undef HAVE_LOCALE */

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Name of package */
#define PACKAGE "mpc"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "shank@mercury.chem.pitt.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mpc"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mpc 0.11.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mpc"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.11.1"

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Version number of package */
#define VERSION "0.11.1"
