#! /usr/bin/env bash
# do-build <platform> <results-dir>: This script is used to generate a binary to release.

set -e -o pipefail

print() { echo "$1" >&2; }
inform() { print "$0: $1"; }
warn() { print "Warning: $1"; }
error() { inform "Error: $1"; }
fail() { error "$1"; exit 1; }
status() { echo -n "$1" >&2; }

[ "$1" ] && PLATFORM=$1 || fail "No platform given!"
[ "$2" ] && RESULTS_DIR=$2
[ "$3" ] && fail "Too many arguments!"

if [ "$PLATFORM" == "leanXcam" ]; then
	make distclean
	make SCS/BF537_LEANXCAM_config
elif [ "$PLATFORM" == "indXcam" ]; then
	make distclean
	make SCS/BF537_INDXCAM_config
else
	fail "Unknown platform: $PLATFORM"
fi

time make
[ "$RESULTS_DIR" ] && cp "images/uImage" "HISTORY" "$RESULTS_DIR"
