#! /usr/bin/env bash
# do-release
# This script is used to bring the working directory into a shape where it can be released as a tar Archive.
# WARNING: Everything git-related is deleted from the currend directory!

set -e -o pipefail

print() { echo "$1" >&2; }
inform() { print "$0: $1"; }
warn() { print "Warning: $1"; }
error() { inform "Error: $1"; }
fail() { [ "$1" ] && error "$1"; return 1; }
usage() { print "$USAGE"; fail "$1"; }

# The usage message
USAGE='Usage: do-release'

[ "$1" ] && usage 'No arguments required.'

find . -name '.gitignore' -or -name '.cdtproject' -or -name '.project' -or -name '.gitmodules' -or -name '.git' | while IFS= read i; do
	rm -rf "$i"
done
	
rm -f 'do-build' 'do-release' 'do-tag' 'prune_dirs'
