#!/bin/sh

if [ "$1" = "-p" ] ; then
	pretend=true
	shift
else
	pretend=false
fi

MAKE=${MAKE:-make}
LOG_DIR="LOG"

arches="$@"
if [ -z "$arches" ] ; then
	all_arches=$(
		cd vendors/config
		echo */config.arch | sed 's:/config.arch::g'
	)
	arches=""
	for arch in ${all_arches} ; do
		CROSS_COMPILE=$(
			var="CROSS_COMPILE"
			makefile="vendors/config/${arch}/config.arch"
			export ROOTDIR=$PWD
			echo -e "e:\\n\\t@echo \$(${var})\\ninclude ${makefile}" | \
				${MAKE} --no-print-directory -s -f - 2>/dev/null
		)
		if [ -n "$CROSS_COMPILE" ] ; then
			if ${CROSS_COMPILE}gcc -v 2>/dev/null 1>&2 ; then
				arches="${arch} ${arches}"
				echo "Adding ${arch} to build list"
			else
				echo "Skipping ${arch}: unable to find '${CROSS_COMPILE}gcc'"
			fi
		elif [ "${arch}" != "host" -a "${arch}" != "common" ] ; then
			echo "Skipping ${arch}: does not define CROSS_COMPILE"
		fi
	done
	echo
fi

mkdir -p "${LOG_DIR}"
PASS=""
FAIL=""
for arch in ${arches} ; do
	list=$(
		cd vendors
		grep -l ${arch}/config.arch */*/config.arch | sed 's:/config.arch::g'
	)
	echo "Building boards:"
	echo " `echo ${list} | sed 's: :\n :g'`"
	echo

	for board in ${list} ; do
		sanitized=$(echo "${board}" | sed s:/:_:g)
		log="${LOG_DIR}/${sanitized}.log"
		imgs="${LOG_DIR}/${sanitized}"
		rm -rf "${log}"{,.FAIL} "${imgs}" images
		printf "#### BUILDING BOARD: ${board}: "
		if ${pretend} || ${MAKE} ${board}_default > "${log}" 2>&1 ; then
			echo PASS
			PASS="${PASS} ${board}"
			if ! ${pretend} ; then
				rsync -a --delete images/ "${imgs}"
			fi
		else
			echo FAIL
			FAIL="${FAIL} ${board}"
			printf "\n\nSingle target ...\n\n" >> "${log}"
			${MAKE} single >> "${log}" 2>&1
			${MAKE} single > "${log}".FAIL 2>&1
		fi
		${pretend} || svn st > "${log}".svn
	done
done

cat <<EOF

These boards passed:
 `echo ${PASS:-no passes here} | sed 's: :\n :g'`

These boards failed:
 `echo ${FAIL:-no failures here} | sed 's: :\n :g'`

EOF

[ -n "${FAIL}" ] && exit 1 || exit 0
