#!/usr/bin/expect
#
#Test program to test reboot.
#
#Steps:
#1.  Set up the tftp server on host. Set the root folder, such as "/tftpboot".
#2.  Set up the uboot environment variables. such as serverip, ipaddr, bootfile, bootaddr, etc.
#3.  Build the uclinux with default configuration.
#3.1 "make menuconfig"
#3.2 "make"
#3.3 "cp linux-2.6.x/linux /tftpboot/uImage
#4.  Hit the reset button on target board and start the test script.
#4.1 "cd testsuites/reboot/"
#4.2 "./test_reboot /dev/ttyS0"
#

set send_slow {1 .01}

set SERIAL_PORT_BAUD_RATE   "57600"
set TITLE "Reboot Test"
set count 30

set argc [llength $argv]
if { $argc < 1} {
   puts "Usage:  $argv0 tty-device \[reboot_count\]"
   puts "   where tty-device is something like /dev/ttyS0"
   puts ""
   exit
}
# grab the user specified parameters.
set ttydev             [lindex $argv 0]
if { $argc >=2 } {
	set count             [lindex $argv 1]
}

# Now set up the kermit parameters.
#  I want these all contained in this file to make it easier for users.
#  This just builds up a list of commands which are sent to kermit.
#
set kparams     [list "set line $ttydev\r"]
lappend kparams "set speed $SERIAL_PORT_BAUD_RATE\r"
lappend kparams "set carrier-watch off\r"
lappend kparams "set handshake none\r"
lappend kparams "set flow-control none\r"
lappend kparams "robust\r"
lappend kparams "set file type bin\r"
lappend kparams "set file name lit\r"
lappend kparams "set rec pack 1000\r"
lappend kparams "set send pack 1000\r"
lappend kparams "set window 5\r"
set nkparams [llength $kparams]

set timeout 3
spawn kermit
# We need to save the id because resetting the board will overwrite it.
set kermit_spawn_id $spawn_id

while 1 {
	expect {
	        "Type ?" { }
		"ermit>" { break }
		"not found" {
                   tee "ERROR: Failed to start up kermit"
                   exit
		}
		timeout {
                   tee "ERROR: Time out starting up kermit"
                   exit
		}
	}
}

for {set i 0} {$i < $nkparams} {incr i} {
    send -s [lindex $kparams $i]

    while 1 {
	  expect {
		 "ermit>" { break }

		 "\\?\[A-Z]" {
                    tee "ERROR: Failed to set up kermit parameters"
                    exit
		 }

		 timeout {
                    tee "ERROR: Time out setting up kermit parameters"
                    exit
		 }
	  }
    }
}

send -s "connect\r"
while 1 {
	expect {
		"ype the escape character*" {
		     break  }
		timeout {
		     puts "\nERROR: Can't connect to serial port\n"
		     exit }
	}
}
#
#  Ok, Kermit is running and connected to the board.
#


puts "*********************************\r"
puts "Start $TITLE\r"
puts "*********************************\r"

for {set reboot_num 0} {$reboot_num < $count} {incr reboot_num} {


set timeout 5
set response "\r"
expect {
	"Hit any key" {
	}
	"SPACE to stop" {
		set response " "
	}
	timeout {
	}
}

sleep 1

set timeout 2
while 1 {
   send -s $response
   expect {
      ">" {
         break
      }
	timeout {
		puts "\rReboot $reboot_num ...FAIL\r"
		puts "$TITLE ............\[FAIL\]\r"
		exit
	}
   }
}

set timeout 30
send -s "tftpboot\r"
while 1 {
   expect {
      "TFTP" {
      }
      ">" {
         break
      }
	timeout {
		puts "\rReboot $reboot_num ...FAIL\r"
		puts "$TITLE ............\[FAIL\]\r"
		exit
	}
   }
}

set timeout 5
send -s "bootelf ; bootm\r"
while 1 {
   expect {
      "Linux version" {
         break
      }
   }
}

set timeout 30
while 1 {
   expect {
	"> " {
		break
	}

         timeout {
		puts "\rReboot $reboot_num ...FAIL\r"
		puts "$TITLE ............\[FAIL\]\r"
		exit
         }
   }
}

puts "Wait for 1 minutes before reboot.\r"
sleep 60

set timeout 5
send -s "\r\r"
while 1 {
   expect {
	">" {
		puts "\rReboot $reboot_num ...PASS\r"
		break
	}

         timeout {
		puts "\rReboot $reboot_num ...FAIL\r"
		puts "$TITLE ............\[FAIL\]\r"
		exit
         }
   }
}

send -s "reboot\r"

}

puts "                                                                        \r"
puts "\r$TITLE ............\[PASS\]\r"

