#define TOOLCHAIN_VERSION "#167 Thu Jul 22 18:39:02 IST 2004"
#define TOOLCHAIN_COMPILE_TIME "18:39:02"
#define TOOLCHAIN_COMPILE_BY "root"
#define TOOLCHAIN_COMPILE_HOST "localhost.localdomain"
#define TOOLCHAIN_COMPILE_DOMAIN "localdomain"
#define TOOLCHAIN_COMPILER "gcc version 3.3.3"
