#define TOOLCHAIN_VERSION "#191 Fri Jul 30 14:00:30 IST 2004"
#define TOOLCHAIN_COMPILE_TIME "14:00:30"
#define TOOLCHAIN_COMPILE_BY "root"
#define TOOLCHAIN_COMPILE_HOST "localhost.localdomain"
#define TOOLCHAIN_COMPILE_DOMAIN "localdomain"
#define TOOLCHAIN_COMPILER "gcc version 3.3.3"
