// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef inactive_h
#define inactive_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *the_group;
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Scrollbar.H>
extern Fl_Menu_Item menu_menu[];
#endif
