// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "resize.h"

static void cb_A(Fl_Button* o, void*) {
  Fl_Window* w = o->window();
w->position(w->x()-50,w->y());
}

static void cb_2(Fl_Button* o, void*) {
  Fl_Window* w = o->window();
w->position(w->x(),w->y()+50);
}

static void cb_06(Fl_Button* o, void*) {
  Fl_Window* w = o->window();
w->position(w->x()+50,w->y());
}

static void cb_8(Fl_Button* o, void*) {
  Fl_Window* w = o->window();
w->position(w->x(),w->y()-50);
}

static void cb_grow(Fl_Button* o, void*) {
  Fl_Window* w = o->window();
w->size(w->w()+50, w->h()+50);
}

static void cb_shrink(Fl_Button* o, void*) {
  Fl_Window* w = o->window();
w->size(w->w()/2+1, w->h()/2+1);
}

int main(int argc, char **argv) {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(366, 261);
    w = o;
    { Fl_Button* o = new Fl_Button(20, 40, 40, 40, "@<-");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_A);
    }
    { Fl_Button* o = new Fl_Button(60, 80, 40, 40, "@2->");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_2);
    }
    { Fl_Button* o = new Fl_Button(100, 40, 40, 40, "@->");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_06);
    }
    { Fl_Button* o = new Fl_Button(60, 0, 40, 40, "@8->");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_8);
    }
    { Fl_Button* o = new Fl_Button(30, 130, 110, 40, "grow");
      o->labeltype(FL_SYMBOL_LABEL);
      o->labelfont(1);
      o->labelsize(18);
      o->callback((Fl_Callback*)cb_grow);
    }
    { Fl_Button* o = new Fl_Button(30, 190, 110, 40, "shrink");
      o->labeltype(FL_SYMBOL_LABEL);
      o->labelfont(1);
      o->labelsize(18);
      o->callback((Fl_Callback*)cb_shrink);
    }
    o->end();
    o->resizable(o);
  }
  w->show(argc, argv);
  return Fl::run();
}
