// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef shiny_panel_h
#define shiny_panel_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
extern Fl_Box *test_box[3];
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void which_cb(Fl_Button*, long);
extern void inside_cb(Fl_Button*, void*);
#include <FL/Fl_Value_Slider.H>
extern void color_slider_cb(Fl_Value_Slider*, long);
extern Fl_Value_Slider *color_slider[4];
#include <FL/Fl_Slider.H>
extern void thickness_cb(Fl_Slider*, void*);
extern Fl_Slider *thickness_slider;
extern void dump_cb(Fl_Button*, void*);
Fl_Window* make_panels();
#endif
