// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef tabs_h
#define tabs_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
extern Fl_Window *foo_window;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Clock.H>
#include <stdlib.h>
#include <FL/Fl_Return_Button.H>
#endif
