// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef valuators_h
#define valuators_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <stdio.h>
#include <FL/Fl_Box.H>
#include <FL/Fl_Slider.H>
extern void callback(Fl_Slider*, void*);
#include <FL/Fl_Value_Slider.H>
extern void callback(Fl_Value_Slider*, void*);
#include <FL/Fl_Adjuster.H>
extern void callback(Fl_Adjuster*, void*);
#include <FL/Fl_Counter.H>
extern void callback(Fl_Counter*, void*);
#include <FL/Fl_Dial.H>
extern void callback(Fl_Dial*, void*);
#include <FL/Fl_Roller.H>
extern void callback(Fl_Roller*, void*);
#include <FL/Fl_Value_Input.H>
extern void callback(Fl_Value_Input*, void*);
#include <FL/Fl_Value_Output.H>
extern void callback(Fl_Value_Output*, void*);
#include <FL/Fl_Scrollbar.H>
extern void callback(Fl_Scrollbar*, void*);
#endif
