.Id $Id: at.allow.5,v 1.1 1997/09/28 20:00:28 ig25 Exp $
.TH AT.ALLOW 5 "Sep 1997" "" "Linux Programmer's Manual"
.SH NAME
at.allow, at.deny \- determine who can submit jobs via at or batch
.SH DESCRIPTION
The
.I /etc/at.allow
and
.I /etc/at.deny
files determine which user can submit commands for later execution via
.BR at (1)
or
.BR batch (1) .
.PP
The format of the files is a list of usernames, one on each line.  Whitespace
is not permitted.
.PP
The superuser may always use
.BR at .
.PP
If the file
.I /etc/at.allow
exists, only usernames mentioned in it are allowed to use
.BR at .
.PP
If
.I /etc/at.allow
does not exist,
.I /etc/at.deny
is checked.
.SH "SEE ALSO"
.BR at (1),
.BR atrun (1),
.BR cron (8),
.BR crontab (1),
.BR atd (8).
