# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/audiofile
pkglibdir = $(libdir)/audiofile
pkgincludedir = $(includedir)/audiofile
top_builddir = ..

ACLOCAL = ${SHELL} /home/shivaram/sound/src/audiofile-0.2.6/missing --run aclocal
AUTOCONF = ${SHELL} /home/shivaram/sound/src/audiofile-0.2.6/missing --run autoconf
AUTOMAKE = ${SHELL} /home/shivaram/sound/src/audiofile-0.2.6/missing --run automake
AUTOHEADER = ${SHELL} /home/shivaram/sound/src/audiofile-0.2.6/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = i686-pc-linux-gnu
AMTAR = ${SHELL} /home/shivaram/sound/src/audiofile-0.2.6/missing --run tar
AS = @AS@
AUDIOFILE_MAJOR_VERSION = 0
AUDIOFILE_MICRO_VERSION = 6
AUDIOFILE_MINOR_VERSION = 2
AUDIOFILE_VERSION = 0.2.6
AUDIOFILE_VERSION_INFO = 2:6:2
AUDIO_LIB = 
AWK = gawk
CC = gcc
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
ECHO = echo
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = audiofile
RANLIB = ranlib
STRIP = strip
TEST_BIN = linuxtest
VERSION = 0.2.6
am__include = include
am__quote = 
install_sh = /home/shivaram/sound/src/audiofile-0.2.6/install-sh

INCLUDES = -I$(top_srcdir)/libaudiofile

noinst_PROGRAMS = \
	error \
	floatto24 \
	transparency \
	miscread \
	miscwrite \
	query2 \
	testaupv \
	writeaiff \
	writeircam \
	writenext \
	writewave \
	writeraw \
	writeavr \
	writeiff \
	writenist \
	writeulaw \
	writealaw \
	loop \
	instparamwrite \
	instparamtest \
	sixteen-to-eight \
	testfloat \
	twentyfour \
	twentyfour2 \
	pipe \
	testmarkers \
	testchannelmatrix \
	printmarkers \
	seek


EXTRA_DIST = transparency.sh misc.sh pipe.sh

TESTS = error writeaiff writeircam writenext writewave writeraw \
	writeavr writeiff writenist \
	writeulaw writealaw \
	misc.sh transparency.sh pipe.sh \
	query2 sixteen-to-eight twentyfour twentyfour2 floatto24 \
	testfloat testmarkers testchannelmatrix seek


LDADD = $(top_builddir)/libaudiofile/libaudiofile.la

DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
subdir = test
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
noinst_PROGRAMS = error$(EXEEXT) floatto24$(EXEEXT) \
	transparency$(EXEEXT) miscread$(EXEEXT) miscwrite$(EXEEXT) \
	query2$(EXEEXT) testaupv$(EXEEXT) writeaiff$(EXEEXT) \
	writeircam$(EXEEXT) writenext$(EXEEXT) writewave$(EXEEXT) \
	writeraw$(EXEEXT) writeavr$(EXEEXT) writeiff$(EXEEXT) \
	writenist$(EXEEXT) writeulaw$(EXEEXT) writealaw$(EXEEXT) \
	loop$(EXEEXT) instparamwrite$(EXEEXT) instparamtest$(EXEEXT) \
	sixteen-to-eight$(EXEEXT) testfloat$(EXEEXT) \
	twentyfour$(EXEEXT) twentyfour2$(EXEEXT) pipe$(EXEEXT) \
	testmarkers$(EXEEXT) testchannelmatrix$(EXEEXT) \
	printmarkers$(EXEEXT) seek$(EXEEXT)
PROGRAMS = $(noinst_PROGRAMS)

error_SOURCES = error.c
error_OBJECTS = error.$(OBJEXT)
error_LDADD = $(LDADD)
error_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
error_LDFLAGS =
floatto24_SOURCES = floatto24.c
floatto24_OBJECTS = floatto24.$(OBJEXT)
floatto24_LDADD = $(LDADD)
floatto24_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
floatto24_LDFLAGS =
instparamtest_SOURCES = instparamtest.c
instparamtest_OBJECTS = instparamtest.$(OBJEXT)
instparamtest_LDADD = $(LDADD)
instparamtest_DEPENDENCIES = \
	$(top_builddir)/libaudiofile/libaudiofile.la
instparamtest_LDFLAGS =
instparamwrite_SOURCES = instparamwrite.c
instparamwrite_OBJECTS = instparamwrite.$(OBJEXT)
instparamwrite_LDADD = $(LDADD)
instparamwrite_DEPENDENCIES = \
	$(top_builddir)/libaudiofile/libaudiofile.la
instparamwrite_LDFLAGS =
loop_SOURCES = loop.c
loop_OBJECTS = loop.$(OBJEXT)
loop_LDADD = $(LDADD)
loop_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
loop_LDFLAGS =
miscread_SOURCES = miscread.c
miscread_OBJECTS = miscread.$(OBJEXT)
miscread_LDADD = $(LDADD)
miscread_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
miscread_LDFLAGS =
miscwrite_SOURCES = miscwrite.c
miscwrite_OBJECTS = miscwrite.$(OBJEXT)
miscwrite_LDADD = $(LDADD)
miscwrite_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
miscwrite_LDFLAGS =
pipe_SOURCES = pipe.c
pipe_OBJECTS = pipe.$(OBJEXT)
pipe_LDADD = $(LDADD)
pipe_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
pipe_LDFLAGS =
printmarkers_SOURCES = printmarkers.c
printmarkers_OBJECTS = printmarkers.$(OBJEXT)
printmarkers_LDADD = $(LDADD)
printmarkers_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
printmarkers_LDFLAGS =
query2_SOURCES = query2.c
query2_OBJECTS = query2.$(OBJEXT)
query2_LDADD = $(LDADD)
query2_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
query2_LDFLAGS =
seek_SOURCES = seek.c
seek_OBJECTS = seek.$(OBJEXT)
seek_LDADD = $(LDADD)
seek_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
seek_LDFLAGS =
sixteen_to_eight_SOURCES = sixteen-to-eight.c
sixteen_to_eight_OBJECTS = sixteen-to-eight.$(OBJEXT)
sixteen_to_eight_LDADD = $(LDADD)
sixteen_to_eight_DEPENDENCIES = \
	$(top_builddir)/libaudiofile/libaudiofile.la
sixteen_to_eight_LDFLAGS =
testaupv_SOURCES = testaupv.c
testaupv_OBJECTS = testaupv.$(OBJEXT)
testaupv_LDADD = $(LDADD)
testaupv_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
testaupv_LDFLAGS =
testchannelmatrix_SOURCES = testchannelmatrix.c
testchannelmatrix_OBJECTS = testchannelmatrix.$(OBJEXT)
testchannelmatrix_LDADD = $(LDADD)
testchannelmatrix_DEPENDENCIES = \
	$(top_builddir)/libaudiofile/libaudiofile.la
testchannelmatrix_LDFLAGS =
testfloat_SOURCES = testfloat.c
testfloat_OBJECTS = testfloat.$(OBJEXT)
testfloat_LDADD = $(LDADD)
testfloat_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
testfloat_LDFLAGS =
testmarkers_SOURCES = testmarkers.c
testmarkers_OBJECTS = testmarkers.$(OBJEXT)
testmarkers_LDADD = $(LDADD)
testmarkers_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
testmarkers_LDFLAGS =
transparency_SOURCES = transparency.c
transparency_OBJECTS = transparency.$(OBJEXT)
transparency_LDADD = $(LDADD)
transparency_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
transparency_LDFLAGS =
twentyfour_SOURCES = twentyfour.c
twentyfour_OBJECTS = twentyfour.$(OBJEXT)
twentyfour_LDADD = $(LDADD)
twentyfour_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
twentyfour_LDFLAGS =
twentyfour2_SOURCES = twentyfour2.c
twentyfour2_OBJECTS = twentyfour2.$(OBJEXT)
twentyfour2_LDADD = $(LDADD)
twentyfour2_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
twentyfour2_LDFLAGS =
writeaiff_SOURCES = writeaiff.c
writeaiff_OBJECTS = writeaiff.$(OBJEXT)
writeaiff_LDADD = $(LDADD)
writeaiff_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writeaiff_LDFLAGS =
writealaw_SOURCES = writealaw.c
writealaw_OBJECTS = writealaw.$(OBJEXT)
writealaw_LDADD = $(LDADD)
writealaw_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writealaw_LDFLAGS =
writeavr_SOURCES = writeavr.c
writeavr_OBJECTS = writeavr.$(OBJEXT)
writeavr_LDADD = $(LDADD)
writeavr_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writeavr_LDFLAGS =
writeiff_SOURCES = writeiff.c
writeiff_OBJECTS = writeiff.$(OBJEXT)
writeiff_LDADD = $(LDADD)
writeiff_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writeiff_LDFLAGS =
writeircam_SOURCES = writeircam.c
writeircam_OBJECTS = writeircam.$(OBJEXT)
writeircam_LDADD = $(LDADD)
writeircam_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writeircam_LDFLAGS =
writenext_SOURCES = writenext.c
writenext_OBJECTS = writenext.$(OBJEXT)
writenext_LDADD = $(LDADD)
writenext_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writenext_LDFLAGS =
writenist_SOURCES = writenist.c
writenist_OBJECTS = writenist.$(OBJEXT)
writenist_LDADD = $(LDADD)
writenist_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writenist_LDFLAGS =
writeraw_SOURCES = writeraw.c
writeraw_OBJECTS = writeraw.$(OBJEXT)
writeraw_LDADD = $(LDADD)
writeraw_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writeraw_LDFLAGS =
writeulaw_SOURCES = writeulaw.c
writeulaw_OBJECTS = writeulaw.$(OBJEXT)
writeulaw_LDADD = $(LDADD)
writeulaw_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writeulaw_LDFLAGS =
writewave_SOURCES = writewave.c
writewave_OBJECTS = writewave.$(OBJEXT)
writewave_LDADD = $(LDADD)
writewave_DEPENDENCIES = $(top_builddir)/libaudiofile/libaudiofile.la
writewave_LDFLAGS =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = 
LIBS = -lm 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/error.Po $(DEPDIR)/floatto24.Po \
	$(DEPDIR)/instparamtest.Po \
	$(DEPDIR)/instparamwrite.Po $(DEPDIR)/loop.Po \
	$(DEPDIR)/miscread.Po $(DEPDIR)/miscwrite.Po \
	$(DEPDIR)/pipe.Po $(DEPDIR)/printmarkers.Po \
	$(DEPDIR)/query2.Po $(DEPDIR)/seek.Po \
	$(DEPDIR)/sixteen-to-eight.Po $(DEPDIR)/testaupv.Po \
	$(DEPDIR)/testchannelmatrix.Po \
	$(DEPDIR)/testfloat.Po $(DEPDIR)/testmarkers.Po \
	$(DEPDIR)/transparency.Po $(DEPDIR)/twentyfour.Po \
	$(DEPDIR)/twentyfour2.Po $(DEPDIR)/writeaiff.Po \
	$(DEPDIR)/writealaw.Po $(DEPDIR)/writeavr.Po \
	$(DEPDIR)/writeiff.Po $(DEPDIR)/writeircam.Po \
	$(DEPDIR)/writenext.Po $(DEPDIR)/writenist.Po \
	$(DEPDIR)/writeraw.Po $(DEPDIR)/writeulaw.Po \
	$(DEPDIR)/writewave.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2
DIST_SOURCES = error.c floatto24.c instparamtest.c instparamwrite.c \
	loop.c miscread.c miscwrite.c pipe.c printmarkers.c query2.c \
	seek.c sixteen-to-eight.c testaupv.c testchannelmatrix.c \
	testfloat.c testmarkers.c transparency.c twentyfour.c \
	twentyfour2.c writeaiff.c writealaw.c writeavr.c writeiff.c \
	writeircam.c writenext.c writenist.c writeraw.c writeulaw.c \
	writewave.c
DIST_COMMON = Makefile.am Makefile.in
SOURCES = error.c floatto24.c instparamtest.c instparamwrite.c loop.c miscread.c miscwrite.c pipe.c printmarkers.c query2.c seek.c sixteen-to-eight.c testaupv.c testchannelmatrix.c testfloat.c testmarkers.c transparency.c twentyfour.c twentyfour2.c writeaiff.c writealaw.c writeavr.c writeiff.c writeircam.c writenext.c writenist.c writeraw.c writeulaw.c writewave.c

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  test/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
error$(EXEEXT): $(error_OBJECTS) $(error_DEPENDENCIES) 
	@rm -f error$(EXEEXT)
	$(LINK) $(error_LDFLAGS) $(error_OBJECTS) $(error_LDADD) $(LIBS)
floatto24$(EXEEXT): $(floatto24_OBJECTS) $(floatto24_DEPENDENCIES) 
	@rm -f floatto24$(EXEEXT)
	$(LINK) $(floatto24_LDFLAGS) $(floatto24_OBJECTS) $(floatto24_LDADD) $(LIBS)
instparamtest$(EXEEXT): $(instparamtest_OBJECTS) $(instparamtest_DEPENDENCIES) 
	@rm -f instparamtest$(EXEEXT)
	$(LINK) $(instparamtest_LDFLAGS) $(instparamtest_OBJECTS) $(instparamtest_LDADD) $(LIBS)
instparamwrite$(EXEEXT): $(instparamwrite_OBJECTS) $(instparamwrite_DEPENDENCIES) 
	@rm -f instparamwrite$(EXEEXT)
	$(LINK) $(instparamwrite_LDFLAGS) $(instparamwrite_OBJECTS) $(instparamwrite_LDADD) $(LIBS)
loop$(EXEEXT): $(loop_OBJECTS) $(loop_DEPENDENCIES) 
	@rm -f loop$(EXEEXT)
	$(LINK) $(loop_LDFLAGS) $(loop_OBJECTS) $(loop_LDADD) $(LIBS)
miscread$(EXEEXT): $(miscread_OBJECTS) $(miscread_DEPENDENCIES) 
	@rm -f miscread$(EXEEXT)
	$(LINK) $(miscread_LDFLAGS) $(miscread_OBJECTS) $(miscread_LDADD) $(LIBS)
miscwrite$(EXEEXT): $(miscwrite_OBJECTS) $(miscwrite_DEPENDENCIES) 
	@rm -f miscwrite$(EXEEXT)
	$(LINK) $(miscwrite_LDFLAGS) $(miscwrite_OBJECTS) $(miscwrite_LDADD) $(LIBS)
pipe$(EXEEXT): $(pipe_OBJECTS) $(pipe_DEPENDENCIES) 
	@rm -f pipe$(EXEEXT)
	$(LINK) $(pipe_LDFLAGS) $(pipe_OBJECTS) $(pipe_LDADD) $(LIBS)
printmarkers$(EXEEXT): $(printmarkers_OBJECTS) $(printmarkers_DEPENDENCIES) 
	@rm -f printmarkers$(EXEEXT)
	$(LINK) $(printmarkers_LDFLAGS) $(printmarkers_OBJECTS) $(printmarkers_LDADD) $(LIBS)
query2$(EXEEXT): $(query2_OBJECTS) $(query2_DEPENDENCIES) 
	@rm -f query2$(EXEEXT)
	$(LINK) $(query2_LDFLAGS) $(query2_OBJECTS) $(query2_LDADD) $(LIBS)
seek$(EXEEXT): $(seek_OBJECTS) $(seek_DEPENDENCIES) 
	@rm -f seek$(EXEEXT)
	$(LINK) $(seek_LDFLAGS) $(seek_OBJECTS) $(seek_LDADD) $(LIBS)
sixteen-to-eight$(EXEEXT): $(sixteen_to_eight_OBJECTS) $(sixteen_to_eight_DEPENDENCIES) 
	@rm -f sixteen-to-eight$(EXEEXT)
	$(LINK) $(sixteen_to_eight_LDFLAGS) $(sixteen_to_eight_OBJECTS) $(sixteen_to_eight_LDADD) $(LIBS)
testaupv$(EXEEXT): $(testaupv_OBJECTS) $(testaupv_DEPENDENCIES) 
	@rm -f testaupv$(EXEEXT)
	$(LINK) $(testaupv_LDFLAGS) $(testaupv_OBJECTS) $(testaupv_LDADD) $(LIBS)
testchannelmatrix$(EXEEXT): $(testchannelmatrix_OBJECTS) $(testchannelmatrix_DEPENDENCIES) 
	@rm -f testchannelmatrix$(EXEEXT)
	$(LINK) $(testchannelmatrix_LDFLAGS) $(testchannelmatrix_OBJECTS) $(testchannelmatrix_LDADD) $(LIBS)
testfloat$(EXEEXT): $(testfloat_OBJECTS) $(testfloat_DEPENDENCIES) 
	@rm -f testfloat$(EXEEXT)
	$(LINK) $(testfloat_LDFLAGS) $(testfloat_OBJECTS) $(testfloat_LDADD) $(LIBS)
testmarkers$(EXEEXT): $(testmarkers_OBJECTS) $(testmarkers_DEPENDENCIES) 
	@rm -f testmarkers$(EXEEXT)
	$(LINK) $(testmarkers_LDFLAGS) $(testmarkers_OBJECTS) $(testmarkers_LDADD) $(LIBS)
transparency$(EXEEXT): $(transparency_OBJECTS) $(transparency_DEPENDENCIES) 
	@rm -f transparency$(EXEEXT)
	$(LINK) $(transparency_LDFLAGS) $(transparency_OBJECTS) $(transparency_LDADD) $(LIBS)
twentyfour$(EXEEXT): $(twentyfour_OBJECTS) $(twentyfour_DEPENDENCIES) 
	@rm -f twentyfour$(EXEEXT)
	$(LINK) $(twentyfour_LDFLAGS) $(twentyfour_OBJECTS) $(twentyfour_LDADD) $(LIBS)
twentyfour2$(EXEEXT): $(twentyfour2_OBJECTS) $(twentyfour2_DEPENDENCIES) 
	@rm -f twentyfour2$(EXEEXT)
	$(LINK) $(twentyfour2_LDFLAGS) $(twentyfour2_OBJECTS) $(twentyfour2_LDADD) $(LIBS)
writeaiff$(EXEEXT): $(writeaiff_OBJECTS) $(writeaiff_DEPENDENCIES) 
	@rm -f writeaiff$(EXEEXT)
	$(LINK) $(writeaiff_LDFLAGS) $(writeaiff_OBJECTS) $(writeaiff_LDADD) $(LIBS)
writealaw$(EXEEXT): $(writealaw_OBJECTS) $(writealaw_DEPENDENCIES) 
	@rm -f writealaw$(EXEEXT)
	$(LINK) $(writealaw_LDFLAGS) $(writealaw_OBJECTS) $(writealaw_LDADD) $(LIBS)
writeavr$(EXEEXT): $(writeavr_OBJECTS) $(writeavr_DEPENDENCIES) 
	@rm -f writeavr$(EXEEXT)
	$(LINK) $(writeavr_LDFLAGS) $(writeavr_OBJECTS) $(writeavr_LDADD) $(LIBS)
writeiff$(EXEEXT): $(writeiff_OBJECTS) $(writeiff_DEPENDENCIES) 
	@rm -f writeiff$(EXEEXT)
	$(LINK) $(writeiff_LDFLAGS) $(writeiff_OBJECTS) $(writeiff_LDADD) $(LIBS)
writeircam$(EXEEXT): $(writeircam_OBJECTS) $(writeircam_DEPENDENCIES) 
	@rm -f writeircam$(EXEEXT)
	$(LINK) $(writeircam_LDFLAGS) $(writeircam_OBJECTS) $(writeircam_LDADD) $(LIBS)
writenext$(EXEEXT): $(writenext_OBJECTS) $(writenext_DEPENDENCIES) 
	@rm -f writenext$(EXEEXT)
	$(LINK) $(writenext_LDFLAGS) $(writenext_OBJECTS) $(writenext_LDADD) $(LIBS)
writenist$(EXEEXT): $(writenist_OBJECTS) $(writenist_DEPENDENCIES) 
	@rm -f writenist$(EXEEXT)
	$(LINK) $(writenist_LDFLAGS) $(writenist_OBJECTS) $(writenist_LDADD) $(LIBS)
writeraw$(EXEEXT): $(writeraw_OBJECTS) $(writeraw_DEPENDENCIES) 
	@rm -f writeraw$(EXEEXT)
	$(LINK) $(writeraw_LDFLAGS) $(writeraw_OBJECTS) $(writeraw_LDADD) $(LIBS)
writeulaw$(EXEEXT): $(writeulaw_OBJECTS) $(writeulaw_DEPENDENCIES) 
	@rm -f writeulaw$(EXEEXT)
	$(LINK) $(writeulaw_LDFLAGS) $(writeulaw_OBJECTS) $(writeulaw_LDADD) $(LIBS)
writewave$(EXEEXT): $(writewave_OBJECTS) $(writewave_DEPENDENCIES) 
	@rm -f writewave$(EXEEXT)
	$(LINK) $(writewave_LDFLAGS) $(writewave_OBJECTS) $(writewave_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/error.Po
include $(DEPDIR)/floatto24.Po
include $(DEPDIR)/instparamtest.Po
include $(DEPDIR)/instparamwrite.Po
include $(DEPDIR)/loop.Po
include $(DEPDIR)/miscread.Po
include $(DEPDIR)/miscwrite.Po
include $(DEPDIR)/pipe.Po
include $(DEPDIR)/printmarkers.Po
include $(DEPDIR)/query2.Po
include $(DEPDIR)/seek.Po
include $(DEPDIR)/sixteen-to-eight.Po
include $(DEPDIR)/testaupv.Po
include $(DEPDIR)/testchannelmatrix.Po
include $(DEPDIR)/testfloat.Po
include $(DEPDIR)/testmarkers.Po
include $(DEPDIR)/transparency.Po
include $(DEPDIR)/twentyfour.Po
include $(DEPDIR)/twentyfour2.Po
include $(DEPDIR)/writeaiff.Po
include $(DEPDIR)/writealaw.Po
include $(DEPDIR)/writeavr.Po
include $(DEPDIR)/writeiff.Po
include $(DEPDIR)/writeircam.Po
include $(DEPDIR)/writenext.Po
include $(DEPDIR)/writenist.Po
include $(DEPDIR)/writeraw.Po
include $(DEPDIR)/writeulaw.Po
include $(DEPDIR)/writewave.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CCDEPMODE) $(depcomp) \
	$(LTCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CCDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; \
	srcdir=$(srcdir); export srcdir; \
	list='$(TESTS)'; \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
	        xpass=`expr $$xpass + 1`; \
	        failed=`expr $$failed + 1`; \
	        echo "XPASS: $$tst"; \
	      ;; \
	      *) \
	        echo "PASS: $$tst"; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
	        xfail=`expr $$xfail + 1`; \
	        echo "XFAIL: $$tst"; \
	      ;; \
	      *) \
	        failed=`expr $$failed + 1`; \
	        echo "FAIL: $$tst"; \
	      ;; \
	      esac; \
	    fi; \
	  done; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="All $$all tests passed"; \
	    else \
	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all tests failed"; \
	    else \
	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
	    fi; \
	  fi; \
	  dashes=`echo "$$banner" | sed s/./=/g`; \
	  echo "$$dashes"; \
	  echo "$$banner"; \
	  echo "$$dashes"; \
	  test "$$failed" -eq 0; \
	fi

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-TESTS check-am clean clean-generic \
	clean-libtool clean-noinstPROGRAMS distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	tags uninstall uninstall-am uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
