verbose "Initialising bridge on eth0/eth1/eth2"

set bridge [config new bridge]
config set $bridge index 0

set eth0dev [config ref ethernet<devname=eth0>]
set eth0elem [config new $bridge.elements interface $eth0dev]
config set $eth0elem fwclass lan
config set $eth0dev conn $eth0elem

set eth1dev [config ref ethernet<devname=eth1>]
set eth1elem [config new $bridge.elements interface $eth1dev]
config set $eth1elem fwclass lan
config set $eth1dev conn $eth1elem

catcherror {
	set eth2dev [config ref ethernet<devname=eth2>]
	set pcielem [config new $bridge.elements interface $eth2dev]
	config set $pcielem fwclass lan
	config set $eth2dev conn $pcielem
}

set brlan [config new static_ip interface $bridge]
config set $brlan name "Bridge"
config set $brlan ipaddr 192.168.0.2
config set $brlan netmask 24
config set $brlan fwclass bridge
config set $bridge conn $brlan
