#!/usr/bin/expect

#
# This usbnet test script is for BF561-EZKIT and BF537-STAMP boards
# A manual test case with Windows PC
#

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp


step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

step "Start testing."
set case_num 0
set count 5
set boardip 192.168.7.1
set hostip 192.168.7.2

sleep 2
send "\r"
expect ">"

incr case_num
set timeout 5
send "dmesg|grep net2272\r"
while 1 {
    expect {
        -re "usb0.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "ifconfig -a\r"
while 1 {
    expect {
        -re "usb0.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "ifconfig usb0 $boardip\r"
while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

puts "**Before the first time to run this case, driver is installed on Windows host PC**\r"
puts "Connect the board to Windows Host PC with a USB cable!\r"
incr case_num
set timeout 60
while 1 {
    expect {
        -re "usb0: high speed config #2: 100 mA, Ethernet Gadget, using RNDIS" {
            break
        }
        timeout {
            break
        }
    }
}

incr case_num
set timeout 20
send "ping $hostip -c $count\r"
while 1 {
    expect {
         -re "$count packets transmitted, $count packets received, 0% packet loss.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

puts "\nTry to ping from Windows host PC to the board $boardip!\n"

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending $argv0\n"

log_file
