#!/usr/bin/expect

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated, 
# for it is the default value.
# set bootargs 	$bootargs_param0   
source ../reboot_kernel.exp 

step "Start oprofile kernel test"
set case_num 0

incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --init\r"
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_user "\nInit timeout\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --start-daemon &\r"
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_log "\nStart daemon timeout\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --start\r"
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_log "\n--start timeout\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --dump\r"
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_log "\n--dump timeout\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 15
send "/usr/bin/opreport -l\r"
while 1 {
    expect {
        -re "not found|error" {
            case_fail $case_num
        }
        -re "Profiling through timer interrupt.*symbol name.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_log "\nopreport timeout\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --dump\r"
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_log "\n--dump timeout\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 15
send "/usr/bin/opreport -l\r"
while 1 {
    expect {
        -re "not found|error" {
            case_fail $case_num
        }
        -re "Profiling through timer interrupt.*symbol name.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_log "\nopreport timeout\n"
            case_fail $case_num
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"
send_user "Ending $argv0\n"

log_file
