#!/usr/bin/expect

# Main entrance

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated, 
# for it is the default value.
# set bootargs 	$bootargs_param0   
source ../reboot_kernel.exp 

step "Start testing."

set case_num 0

incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --init\r"
while 1 {
   expect {
      -re $kernel_prompt {
         send_user "\nInit ok\n"
         case_pass $case_num
         break
      }
      timeout {
         send_user "\nInit failed\n"
         case_fail $case_num
      }
   }
}

sleep 5
incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --start-daemon &\r"
while 1 {
   expect {
      -re $kernel_prompt {
         send_log "\nStart daemon ok\n"
         case_pass $case_num
         break
      }
      timeout {
         send_log "\nStart daemon failed\n"
         case_fail $case_num
      }
   }
}

sleep 5
incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --start\r"
while 1 {
   expect {
      -re $kernel_prompt {
         send_log "\nStart ok\n"
         case_pass $case_num
         break
      }
      timeout {
         send_log "\n--start timeout\n"
         case_fail $case_num
      }
   }
}

sleep 15
incr case_num
set timeout 2
send "/usr/bin/bfin_opcontrol --dump\r"
while 1 {
   expect {
      -re $kernel_prompt {
         send_log "\n--dump ok\n"
         case_pass $case_num
         break
      }
      timeout {
         send_log "\n--dump timeout\n"
         case_fail $case_num
      }
   }
}

sleep 15
incr case_num
set timeout 5
send "/usr/bin/opreport -l\r"
while 1 {
   expect {
      -re "error" {
         send_log "\nopreport error\n"
         case_fail $case_num
      }
      timeout {
         break
      }
   }
}

case_pass $case_num

all_pass

send_user "Ending $argv0\n"

log_file
