#define IMAGE_GOOD            0
#define WRONG_PRODUCT        10
#define WRONG_VENDOR         11
#define ALREADY_CURRENT      12
#define VERSION_OLDER        13
#define NO_VERSION           14
#define TF_TIMEOUT           15
#define BAD_LANGUAGE         16
#define BAD_CGI_FORMAT       17
#define BAD_CGI_DATA         18
#define FTP_CONNECT_FAIL     19
#define BAD_OPEN_FLASH       20
#define NO_MEMORY            21
#define BAD_OFFSET           22
#define NO_IMAGE             23
#define IMAGE_TOO_BIG        24
#define BAD_CHECKSUM         25
#define IMAGE_SHORT          26
#define BAD_HMAC_SIG         27
#define UNKNOWN_COMP         28
#define BAD_DECOMP           29
#define BAD_ROOTFS           30
#define VFORK_FAIL           31
#define BAD_SEG_SEEK         32
#define BAD_SEG_READ         33
#define BAD_SEG_CHECK        34
#define ERASE_FAIL           35
#define BAD_SEG_WRITE        36
#define NO_DEV_NULL          37
#define BAD_DECRYPT          38
#define BAD_PUB_KEY          39
#define BAD_CRYPT_MAGIC      40
#define NO_CRYPT             41
#define BAD_MD5_SIG          42
#define BAD_CRYPT            43
#define NOT_BOOTLOADER_IMAGE 44
#define NOT_FIRMWARE_IMAGE   45
#define BAD_CRYPT_LEN        46
#define HTTP_TIMEOUT         47
