#!/bin/sh

set -e

repository=http://svn.gna.org/svn/xenomai
tmpdir=/tmp/xenomai-documentation

USAGE="$0 [ -q | -v ] [ -d ] [ -h ] installdir dirs

Extract Xenomai documentation tree for directories "dirs". Where dirs are taken
as subdirectories of subversion repository root. Extracted documentation trees
are copied as subdirectories of "installdir".

For example:
$0 download.gna.org:/upload/xenomai/documentation branches/v2.0.x

extracts the generated documentation from the branch/v2.0.x repository
sub-directory and copy it to
download.gna.org:/upload/xenomai/documentation/branches/v2.0.x

Options:
-q, --quiet    quiet, print only error messages, suitable for cron jobs.
-v, --verbose  verbose, subversion and rsync operations print file names.
-d, --debug    debug, print every command before actually running it.
-h, --help     print usage and exit.
"

ECHO=echo
SVN="svn -q"
RSYNC="rsync"

# Parse command line arguments.
while :; do
    case "$1" in
    # Really verbose, output details
    -v|--verbose) SVN=svn
        RSYNC="rsync -v"
        ;;
    
    # Really silent, for cron jobs
    -q|--quiet) ECHO=:
        RSYNC="rsync -q"
        ;;

    # Debugging
    -d|--debug) set -x
        ;;

    -h|--help) cat <<EOF
$USAGE
EOF
        exit 0
        ;;

    *) break
       ;;
    esac
    shift
done


if test $# -lt 2; then
    cat <<EOF
$USAGE

Error: not enough arguments.
EOF
    exit 1
fi


installdir=$1; shift
if test "x$installdir" = x; then
    cat <<EOF
$USAGE

Error: empty installation directory.
EOF
    exit 1
fi

[ -d $tmpdir ] && rm -Rf $tmpdir
mkdir $tmpdir
cd $tmpdir

for dir in ${1+"$@"}; do
    $ECHO Checking out Xenomai directory $dir documentation...
    mkdir -p $dir
    $SVN export --force $repository/$dir/doc/generated $dir
    $SVN export --force $repository/$dir/doc/nodist $dir
    $ECHO done.

    $ECHO Changing files and directories modes...
    find $dir | xargs chmod u=rwX,g=rwX,o=rX
    $ECHO done.

    $ECHO Copying to $installdir/$dir...
    mkdir -p $installdir/$dir
    $RSYNC -e ssh -prltgDz --delete --delete-after $dir/ $installdir/$dir/
    $ECHO done.
done

cd ..
rm -Rf $tmpdir
