.TH bssh/bvnc 1 User Manuals
.SH NAME
bssh/bvnc \- Browse for SSH/VNC servers on the local network
.SH SYNOPSIS
\fBbssh

bvnc
\f1
.SH DESCRIPTION
bssh/bvnc browses for local SSH/VNC servers on the local network, shows them in a GUI for the user to select one and finally calls ssh/xvncviewer after a selection was made.
.SH OPTIONS
bssh/bvnc takes no command line arguments at the moment.
.SH AUTHORS
The Avahi Developers <avahi (at) lists (dot) freedesktop (dot) org>; Avahi is available from \fBhttp://avahi.org/\f1
.SH SEE ALSO
\fBavahi-browse(1)\f1, \fBssh(1)\f1, \fBxvncviewer(1)\f1
.SH COMMENTS
This man page was written using \fBxml2man(1)\f1 by Oliver Kurth.
