#!/usr/bin/expect

#
# This test case is to test the g729 lib in bfgdots
#

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

step "test preparation"
set TEST_PROG "g729ab_test g729ab_testsimgot g729ab_testfdpic g729ab_testfdpic_so"

if [ catch { exec rcp -r $uclinux_path/lib/libbfgdots/g729/test/test_data root@$targetip:/var } ] {
    send_user "FAIL: copy test_data folder to target board\n"
    case_fail $case_num
} else {
    send_user "PASS: copy test_data folder to target board\n"
}

if [ catch { exec rcp $uclinux_path/lib/libbfgdots/g729/test/alltests.sh root@$targetip:/var } ] {
    send_user "FAIL: copy test scripts to target board\n"
    case_fail $case_num
} else {
    send_user "PASS: copy test scripts to target board\n"
}

if [ catch { exec rcp $uclinux_path/lib/libbfgdots/g729/src.fdpic/libg729ab.so root@$targetip:/lib } ] {
    send_user "FAIL: copy g729 lib to target board\n"
    case_fail $case_num
} else {
    send_user "PASS: copy g729 lib to target board\n"
}

foreach element $TEST_PROG {
    if [ catch { exec rcp $uclinux_path/lib/libbfgdots/g729/test/$element root@$targetip:/var } ] {
        send_user "FAIL: copy $element to target board\n"
        case_fail $case_num
    } else {
        send_user "PASS: copy $element to target board\n"
    }
}


step "Start testing."
sleep 5
set case_num 0
send "cd /var\r"
expect -re "var>"

foreach element $TEST_PROG {
    global case_num

    incr case_num
    set timeout 20
    send "./alltests.sh $element\r"
    while 1 {
        expect {
            -re "(\[eE]rror|\[fF]ail|not found).*>" {
                case_fail $case_num
            }
            -re "G729AB Decoder.*>" {
                case_pass $case_num
                break
            }
            timeout {
                send -s "\3"
                send_log "timeout\n"
                case_fail $case_num
            }
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending $argv0\n"

log_file
