#
# arch/blackfin/lib/Makefile
#

lib-y := \
	ashldi3.o ashrdi3.o lshrdi3.o \
	muldi3.o divsi3.o udivsi3.o modsi3.o umodsi3.o \
	checksum.o memcpy.o memset.o memcmp.o memchr.o memmove.o \
	strcmp.o strcpy.o strncmp.o strncpy.o \
	ins.o outs.o
