#
# Makefile for mach-bf533/boards.
#

# Object file lists.

obj-$(CONFIG_BFIN537_STAMP) += stamp.o
obj-$(CONFIG_GENERIC_BOARD) += generic_board.o
obj-$(CONFIG_BFIN537_BLUETECHNIX_CM)      += cm_bf537.o 
