#
# arch/blackfin/mach-bf537/boards/Makefile
#

obj-$(CONFIG_GENERIC_BOARD)            += generic_board.o
obj-$(CONFIG_BFIN537_STAMP)            += stamp.o led.o
obj-$(CONFIG_BFIN537_BLUETECHNIX_CM)   += cm_bf537.o
