#!/bin/sh
if [ "$FIRMWARE" != "" ]; then
        HOTPLUG_FW_DIR=/lib/firmware/
        echo 1 > /sys/$DEVPATH/loading
        cat $HOTPLUG_FW_DIR/$FIRMWARE > /sys/$DEVPATH/data
        echo 0 > /sys/$DEVPATH/loading
fi
