#!/usr/bin/expect

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated, 
# for it is the default value.
# set bootargs 	$bootargs_param0   
source ../reboot_kernel.exp 

step "Start testing."
sleep 10
set timeout 5
send "\r"
expect -re $kernel_prompt

send "cd lmbench3/bin/blackfin-Linux\r" 
while 1 {
    expect {
        "bin*>" {         
            break
        }
        timeout { 
            case_fail $case_num
        }
    }
}

set case_num 0

set timeout 500

incr case_num
send -s  "./lat_ctx -s 0 2\r" 
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s  "./lat_ctx -s 16 2\r"
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s  "./lat_ctx -s 64 2\r"
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s  "./lat_ctx -s 16 8\r"
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
incr case_num
send -s  "./lat_ctx -s 64 8\r"
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s  "./lat_ctx -s 16 16\r"
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s  "./lat_ctx -s 64 16\r"
while 1 {
    expect {
        -re "size.* ovr.*\[\r\n]\[0-9]+ \[0-9\.]+\[\r\n]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending $argv0\n"

log_file
