#
# Makefile for the linux kernel.
#

# Object file lists.
obj-y		+= cache.o cacheinit.o cplbhdlr.o cplbmgr.o entry.o flush.o interrupt.o \
			lock.o ints-priority.o dpmc.o

obj-$(CONFIG_BLKFIN_STAMP) += stamp.o
obj-$(CONFIG_EZKIT) += ezkit.o
obj-$(CONFIG_GENERIC_BOARD) += generic_board.o
