#!/usr/bin/expect

# Main entrance
source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Start testing."
set case_num 0
sleep 2

set MST_BD_ADDR	"00:10:60:D0:8C:41"
set SLV_BD_ADDR	"11:11:11:11:11:11"

step "run hciconfig"
incr case_num
set timeout 5
send "hciconfig hci0 up\r"
while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 2

incr case_num
set timeout 5
send "hciconfig\r"
while 1 {
    expect {
        -re "DOWN|not found" {
            case_fail $case_num
        }
        -re "BD Address.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

step "scan other bluetooth device"
incr case_num
set timeout 300
send "hcitool scan\r"
while 1 {
    expect {
        -re "Inquiry failed: Success|not found" {
            case_fail $case_num
        }
        -re "$SLV_BD_ADDR.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

step "inquire other device"
incr case_num
set timeout 30
send "hcitool -i hci0 info $SLV_BD_ADDR\r"
sleep 2
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re "$SLV_BD_ADDR.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

step "ping to target device"
incr case_num
set timeout 20
send "l2ping -i hci0 -c 50 -f $SLV_BD_ADDR\r"
while 1 {
    expect {
        -re "not found|Can't connect:" {
            case_fail $case_num
        }
        -re "50 sent, 50 received, 0% loss" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
