#!/usr/bin/expect
#
#Test program to stress the system.
#

log_file stress_test_log
send_user "Starting stress_test.exp\n"

set SERIAL_PORT_BAUD_RATE   "57600"
set TITLE "Stress Test"
set PING_COUNT  1999
set targetip 10.100.4.2
set serverip 10.100.4.174
set send_slow {1 .01}

set argc [llength $argv]
if { $argc < 1} {
   puts "Usage:  $argv0 tty-device \[count\] \[targetip serverip\]"
   puts "   where tty-device is something like /dev/ttyS0, count is ping times."
   puts ""
   exit
}
# grab the user specified parameters.
set ttydev             [lindex $argv 0]

if { $argc >= 2} {
   set PING_COUNT           [lindex $argv 1]
}
if { $argc >= 3} {
   set targetip           [lindex $argv 2]
}
if { $argc >= 4} {
   set serverip           [lindex $argv 3]
}

proc step { message } {

  global step_sequence_number

  puts "\n*******************************************************************"
  puts "STEP $step_sequence_number: $message\n\n"
  send_log "\n************** STEP $step_sequence_number: $message\n\n"
  incr step_sequence_number
}

set step_sequence_number    1

step "Start kermit"

# Now set up the kermit parameters.
#  I want these all contained in this file to make it easier for users.
#  This just builds up a list of commands which are sent to kermit.
#
set kparams     [list "set line $ttydev\r"]
lappend kparams "set speed $SERIAL_PORT_BAUD_RATE\r"
lappend kparams "set carrier-watch off\r"
lappend kparams "set handshake none\r"
lappend kparams "set flow-control none\r"
lappend kparams "robust\r"
lappend kparams "set file type bin\r"
lappend kparams "set file name lit\r"
lappend kparams "set rec pack 1000\r"
lappend kparams "set send pack 1000\r"
lappend kparams "set window 5\r"
set nkparams [llength $kparams]

set timeout 3
spawn kermit
# We need to save the id because resetting the board will overwrite it.
set kermit_spawn_id $spawn_id

while 1 {
	expect {
	        "Type ?" { }
		"ermit>" { break }
		"not found" {
                   tee "ERROR: Failed to start up kermit"
                   exit
		}
		timeout {
                   tee "ERROR: Time out starting up kermit"
                   exit
		}
	}
}

for {set i 0} {$i < $nkparams} {incr i} {
    send -s [lindex $kparams $i]

    while 1 {
	  expect {
		 "ermit>" { break }

		 "\\?\[A-Z]" {
                    tee "ERROR: Failed to set up kermit parameters"
                    exit
		 }

		 timeout {
                    tee "ERROR: Time out setting up kermit parameters"
                    exit
		 }
	  }
    }
}

send -s "connect\r"
while 1 {
	expect {
		"ype the escape character*" {
		     break  }
		timeout {
		     puts "\nERROR: Can't connect to serial port\n"
		     exit }
	}
}
#
#  Ok, Kermit is running and connected to the board.
#

step "Restart the board."

send_user "Try to figure out if we are in u-boot or the kernel"
set where_are_we 0
send "version\r"
set timeout 20
expect {

    "U-Boot" {
        send_user "We are in u-boot\n"
        set where_are_we "uboot"
    }

    "Linux" {
        send_user "We are in the kernel\n"
        set where_are_we "kernel"
    }

    timeout {
        send_user "Can't tell if we are in u-boot or the kernel\n"
    }
}

if { $where_are_we == "uboot" } {
    set timeout 50
    expect ">"
    send_user "sending reset\n"
    send "reset\r"
} else {
    if { $where_are_we == "kernel" } {
        set timeout 60
        expect ">"
        send_user "sending reboot\n"
        send "reboot\r"
    } else {
        # If we don't know where we are, hit control-C and enter
        set timeout 10
        expect "*"
        expect "*"
        send_user "sending control-C\n"
        send "\3"
        sleep 1
        send "\r"
    }
}

while 1 {
       expect {
         "Hit any key " {
             send "\r"
	     break
         }
        
         timeout {
             send_user "failed reset attempt\n"
             break
         }
      }
   }

expect ">"
send -s "set bootargs root=/dev/mtdblock0 rw\r"
expect ">"
send -s "save\r"
expect ">"

set timeout 2
set flag 0
send -s "tftpboot\r"
while 1 {
   expect {
      "TFTP" {
         set flag 1
         set timeout 30
      }
      ">" {
         break
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

set timeout 1
set flag 0
send -s "bootelf\r"
while 1 {
   expect {
      "Loading .text" {
         set flag 1
         set timeout 30
      }
      "> " {
         break
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

   set timeout 3
   send -s "ifconfig eth0 down\r"
   expect {
	"> " {
	}

         timeout {
	 	puts "Fail to config eth0\r"
		exit
         }
   }
   
   send -s "ifconfig eth0 $targetip\r"
   expect {
	">" {
	}

         timeout {
	 	puts "Fail to config eth0\r"
		exit
         }
   }

   
   step "Start the stress testing."
 
   log_file
  
   set timeout 40
   spawn ./ftp_test $targetip
   set ftp_test_id $spawn_id
   expect "Ftp is tested"
 
   spawn ./telnet_test $targetip
   set telnet_test_id $spawn_id
   expect "Telnet is tested"
   
   set timeout [expr $PING_COUNT * 1.5]
    
   log_file stress_test_log
   
   set spawn_id $kermit_spawn_id
   send -s "ping $serverip\r"
   while 1 {
      expect {
	"icmp_seq=$PING_COUNT" {
		send -s "\3"
		break
	}

         timeout {
	 	puts "$TITLE ............\[FAIL\]\r"
		exit
         }
      }
   }

   set timeout 5
   while 1 {
      expect {
	 "> " {
        	break
      	}

      	timeout {
	 	puts "$TITLE ............\[FAIL\]\r"
		exit
	}
      }
   }

   set found 0
   spawn ps a
   while 1 {
      expect {
	"telnet_test" {
		incr found
	}

	"ftp_test" {
		incr found
	}
	
	"telnet_test <defunct>" {
		set found 0
		break
	}

	"ftp_test <defunct>" {
		set found 0
		break
	}
	
        eof {
	 	break
        }
      }
   }
   
   if {$found == 2} {
		set spawn_id $telnet_test_id
		send -s "\3"
		set spawn_id $ftp_test_id
		send -s "\3"
		send_log "\n$TITLE ............\[PASS\]\n"
		exit
   }

   send_log "\n$TITLE ............\[FAIL\]\n"


log_file

send_user "Ending stress_test.exp\n"

