#!/usr/bin/expect

log_file telnet_test_log

set send_slow {1 .01}

set targetip 10.100.4.2
if { $argc >= 1} {
   set targetip           [lindex $argv 0]
}

spawn /bin/sh

while 1 {
	send -s "telnet $targetip\r"
	expect {
		">" {  }
		timeout { send_user "Failed inital telnet\n"
			exit }
	}
	send -s "\r"
	expect {
	        ">" { }
	        timeout { send_user "Failed first return\n"
			exit }
	}
	send -s "ls\r"
        expect {
                ">" { }
                timeout { send_user "Failed first return\n"
                        exit }
        }
	send -s "dmesg\r"
        expect {
                ">" { }
                timeout { send_user "Failed first return\n"
                        exit }
        }
	send -s "cat /proc/slabinfo\r"
        expect {
                ">" { }
                timeout { send_user "Failed first return\n"
                        exit }
        }

	send -s "exit\r"
        expect "$"
}
log_file
