#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "$TITLE needs SW5: on on on on."

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 5
step "Starting test"
set timeout 8
set flag 0

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {
         set flag 1
         break
      }

      timeout {
                   
            break
         }
     }
}
expect "root:/bin>"

if { $board_type == "BF537-STAMP" } {

	send -s "./pflags_test bf537\r" 

} elseif { $board_type == "BF533-STAMP" } {

	send -s "./pflags_test bf533\r"
}

while 1 {
   expect {
     -re  "open success.*open success" {
         set flag 1
         puts "\nopen device success.\n"
         break
      }

      timeout {
            send_log "pflags open devices fail. "
            break
         }
     }
}

while 1 {
   expect {
     -re  "Press .* to EXIT" {
         set flag 1
         break
      }

      timeout {
            send_log "pflags test fail to toggle the led1. "
            break
         }
     }
}

set timeout 3600
while 1 {
   expect {
      "root:/bin>" {
         send_log "pflags led test done!" 
         break
      }

      timeout {
            send_log "pflags test fail to exit. "
            break
         }
     }
}

set timeout 10
send "cat /proc/driver/pflags\r" 
while 1 {
   expect {
      "root:/bin>" {
         set flag 1
         send_log "\npflags test success.\n"
         break
      }

      timeout {
            send_log "pflags test fail to cat pflags. "
            break
         }
     }
}

send_user "Ending $argv0\n"
log_file




