#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."

set case_num 0

incr case_num

set timeout 8
set flag 0

if { $board_type == "BF537-STAMP" } {

                        
			expect "root:~>"
			send -s "modprobe bfin_mac\r"
			while 1 {
			expect {
			-re ".* registered" {
                case_pass $case_num
				puts "\nmodule insert success.\n"
				break
			}
			
			timeout {
                case_fail $case_num
				exit
				}
			}
			}
			
			incr case_num
			
			expect "root:~>"
			send -s "lsmod\r"
			while 1 {
			expect {
			"bfin_mac" {
                case_pass $case_num
				puts "\nmodule ls success.\n"
				break
			}
			
			timeout {
                case_fail $case_num
				exit
				}
			}
			}


} elseif { $board_type == "BF533-STAMP" } {
                       	expect "root:~>"
						
			send -s "modprobe smc91x\r"
			while 1 {
			expect {
			"eth0: Ethernet addr" {
                case_pass $case_num
				puts "\nmodule insert success.\n"
				break
			}
			
			timeout {
                case_fail $case_num
				exit
				}
			}
			}
			
			incr case_num
			
			expect "root:~>"
			send -s "lsmod\r"
			while 1 {
			expect {
			"smc91x" {
                case_pass $case_num
				puts "\nmodule ls success.\n"
				break
			}
			
			timeout {
                case_fail $case_num
				exit
				}
			}
			}
}

incr case_num

expect "root:~>"
send -s "ifconfig eth0 $targetip\r" 
while 1 {
   sleep 3
   expect {
      "~>" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}


send -s "ifconfig\r" 
while 1 {
   expect {
      "$targetip" { 
         break
      }

      timeout {                           
         break
         }
     }
}

incr case_num

expect "root:~>"
send -s "ping $serverip\r" 
while 1 {
   expect {
      "icmp_seq" { 
       sleep 10
       send "\003"
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}

incr case_num

expect "root:~>"
set timeout 50

if { $board_type == "BF537-STAMP" } {

	send -s  "rmmod bfin_mac\r"
	while 1 {
	expect {
	"root:~>" {
                case_pass $case_num
		break
	}
	
	timeout {
                case_fail $case_num
		exit
		}
	}
	}

} elseif { $board_type == "BF533-STAMP" } {

	send -s  "rmmod smc91x\r" 
	while 1 {
	expect {
	"root:~>" {    
                case_pass $case_num
		break
	}
	
	timeout {
                case_fail $case_num
		exit
		}
	}
	}
}

incr case_num

if { $board_type == "BF537-STAMP" } {

send -s "lsmod\r" 
while 1 {
   expect {
   
      "bfin_mac" { 
                case_fail $case_num
	exit
         }
	 
      "root:~>" {
                case_pass $case_num
         break
      }
      
      timeout { 
                case_fail $case_num
	exit
         }
     }
}
} elseif { $board_type == "BF533-STAMP" } {

send -s "lsmod\r" 
while 1 {
   expect {
   
      "smc91x" { 
                case_fail $case_num
	exit
         }
	 
      "root:~>" {
                case_pass $case_num
         break
      }

      timeout { 
                case_fail $case_num
	exit
         }
     }
}
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 

