#!/usr/bin/expect

#
#Test program to test the audio driver.
#

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

send_log "*********************************\r"
send_log "Start $TITLE\r"
send_log "*********************************\r"

spawn plaympeg -l audiotest.mp3
set plaympeg_id $spawn_id

set spawn_id $kermit_spawn_id 

set case_num 0

send_log "\nPlease listen to the earphone or amplifier.\n\n"

sleep 3

set timeout 4
send "cd /var\n"
expect	"> "

while 1 {
   set timeout 15 
   incr case_num
   send -s "vrec -w -S -b 8 -s 44100 -t 6 a; vrec -w -S -b 16 -s 8000 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -S -b 16 -s 44100 -t 6 a; vrec -w -S -b 8 -s 8000 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 8 -s 8000 -t 6 a; vrec -w -S -b 16 -s 8000 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 16 -s 8000 -t 6 a; vrec -w -S -b 8 -s 8000 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 8 -s 44100 -t 6 a; vrec -w -S -b 16 -s 44100 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 16 -s 44100 -t 6 a; vrec -w -S -b 8 -s 44100 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 8 -s 44100 -t 6 a; vrec -w -b 16 -s 8000 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 16 -s 44100 -t 6 a; vrec -w -b 8 -s 8000 -t 6 b\n"
   expect "> "
   send -s "vplay a&\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
		exit
	    }
	}
   sleep 1 
   send -s "vplay b\n"
   expect {
	"> " {

		send_log "\nCase $case_num ...DONE\n"
	}
	

         timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   set timeout 10
   incr case_num
   send -s "vrec -w -b 16 -s 44100 -t 6 a\n"
   expect { 
   	"> " {}
   	    timeout {
	    	send_log "\nCase $case_num ...FAIL\n"
	    }
   }
   send -s "vplay a &\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
	}
   }

   sleep 1 
   send -s "vrec -w -b 8 -s 8000 -t 6 | vplay\n"
   expect {
	"> " {
		send_log "\nCase $case_num ...DONE\n"
	}
        timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 8 -s 8000 -t 6 a\n"
   expect { 
   	"> " {}
   	    timeout {
	    	send_log "\nCase $case_num ...FAIL\n"
	    }
   }
   send -s "vplay a &\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
	}
   }

   sleep 1 
   send -s "vrec -w -S -b 16 -s 8000 -t 6 | vplay\n"
   expect {
	"> " {
		send_log "\nCase $case_num ...DONE\n"
	}
        timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 8 -s 44100 -t 6 a\n"
   expect { 
   	"> " {}
   	    timeout {
	    	send_log "\nCase $case_num ...FAIL\n"
	    }
   }
   send -s "vplay a &\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
	}
   }

   sleep 1 
   send -s "vrec -w -S -b 16 -s 44100 -t 6 | vplay\n"
   expect {
	"> " {
		send_log "\nCase $case_num ...DONE\n"
	}
        timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 8 -s 44100 -t 6 a\n"
   expect { 
   	"> " {}
   	    timeout {
	    	send_log "\nCase $case_num ...FAIL\n"
	    }
   }
   send -s "vplay a &\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
	}
   }

   sleep 1 
   send -s "vrec -w -b 16 -s 8000 -t 6 | vplay\n"
   expect {
	"> " {
		send_log "\nCase $case_num ...DONE\n"
	}
        timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
         }
   }

   incr case_num
   send -s "vrec -w -b 16 -s 44100 -t 6 a\n"
   expect { 
   	"> " {}
   	    timeout {
	    	send_log "\nCase $case_num ...FAIL\n"
	    }
   }
   send -s "vplay a &\n"
   expect { 
   	"> " {}
	timeout {
		send_log "\nCase $case_num ...FAIL\n"
	}
   }

   sleep 1 
   send -s "vrec -w -b 8 -s 8000 -t 6 | vplay\n"
   expect {
	"> " {
		send_log "\nCase $case_num ...DONE\n"
	}
        timeout {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "\n$TITLE ............\[FAIL\]\n"
		exit
         }
   }


   sleep 5
   expect {
	"Input/output error" {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "\n$TITLE ............\[FAIL\]\n"
		exit
	}
	
	timeout {
		send_log "Finished\n"
		break;

	}
   }

}

set spawn_id $plaympeg_id
send "\3"
sleep 1

send_log "\n$TITLE ............DONE\n"

send_user "Ending $argv0\n"
log_file
 
