#!/usr/bin/expect

#
# This is bulk traffic test for Gadget FS 
#

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

set musb_mode [lindex $argv 0]
send_user "\n#### musb_mode is $musb_mode\n"

if { $argc < 1} {
    puts "Please input: musb_mode(PIO or DMA)"
    exit
}
append TITLE " ($musb_mode)"


step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

step "Start testing."
sleep 5
set case_num 0
#24 hours: set test_interval [expr 3600*24]
set test_interval 3500

if [ catch {exec make clean -f Makefile.testusb -C src} ] {
    send_user "FAIL: Make clean of testusb\n"
    case_fail $case_num
} else {
    send_user "PASS: Make clean of testusb\n"
}

if [ catch {exec make -f Makefile.testusb -C src} ] {
    send_user "FAIL: Build testusb\n"
    case_fail $case_num
} else {
    send_user "PASS: Build testusb\n"
}

if [ catch {exec make clean -f Makefile.usb -C src} ] {
    send_user "FAIL: Make clean of usb\n"
    case_fail $case_num
} else {
    send_user "PASS: Make clean of usb done\n"
}

if [ catch {exec make -f Makefile.usb -C src} ] {
    send_user "FAIL: Build testusb\n"
    case_fail $case_num
} else {
    send_user "PASS: Build usb\n"
}

if [ catch {exec rcp src/usb root@$targetip:/ } ] {
    send_user "FAIL: Copy target to board\n"
    case_fail $case_num
} else {
    send_user "PASS: Copy target to board\n"
}


spawn /bin/bash
set host_spawn_id $spawn_id

incr case_num
set timeout 15
send "su -\r"
while 1 {
    expect {
        -re "\[pP]assword" {
            send "$password\r"
            continue
        }
        -re "\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re "#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "cd $uclinux_path/testsuites/usbdev\r"
expect "#"
send "lsmod |grep usbtest\r"
while 1 {
    expect {
        -re "usbcore.*usbtest.*#" {
            case_pass $case_num
            break
        }
        -re "#" {
            send "sudo insmod ./configs/usbtest.ko\r"
            while 1 {
                expect {
                    -re "insmod:|\[eE]rror|\[fF]ail" {
                        case_fail $case_num
                    }
                    -re "#" {
                        case_pass $case_num
                        break
                    }
                    timeout {
                        send "\3"
                        expect "#"
                        case_fail $case_num
                    }
                }
            }
            break
        }
        timeout {
            send "\3"
            expect "#"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "lsmod |grep usbtest\r"
while 1 {
    expect {
        -re "usbcore.*usbtest.*#" {
            case_pass $case_num
            break
        }
        -re "#" {
            case_fail $case_num
        }
        timeout {
            send "\3"
            expect "#"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 15
send "sudo mount -t usbfs none /proc/bus/usb/\r"
while 1 {
    expect {
        -re "mount: none already mounted" {
            case_pass $case_num
            break
        }
        -re "\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re "#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 4
send "mount\r"
while 1 {
    expect {
        -re "none on /proc/bus/usb type usbfs.*#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}


set spawn_id $kermit_spawn_id

incr case_num
set timeout 3
send "mkdir /dev/gadget\r"
while 1 {
    expect {
        -re "mkdir:|\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "mount -t gadgetfs gadgetfs /dev/gadget\r"
while 1 {
    expect {
        -re "mount:|\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re "USB Gadget filesystem.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 2
incr case_num
set timeout 3
send "ls /dev/gadget/ -l\r"
while 1 {
    expect {
        -re "musb_hdrc.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "./usb -r \"1.3\" -v\r"
while 1 {
    expect {
        -re "panic|\[fF]ail|\[eE]rror" {
            case_fail $case_num
        }
        -re "gadgetfs: connected.*simple_source_thread start.*simple_sink_thread start.*SETUP.*" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}


set spawn_id $host_spawn_id

incr case_num
set timeout 5
send "cat /proc/bus/usb/devices\r"
while 1 {
    expect {
        -re "Manufacturer=Licensed to Code, LLC.*Product=My Source/Sink Product.*#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "lsusb|grep -i \"Netchip Technology\"|awk '{print \$2\" \"\$4}'\r"
while 1 {
    expect {
        -re "(\[0-9]+)( )(\[0-9]+)" {
            set gadget_bus "$expect_out(1,string)"
            set gadget_dev "$expect_out(3,string)"
            send_user "gadget_bus=$gadget_bus;gadget_dev=$gadget_dev\n"
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set fail_count_t1 0
set fail_count_t3 0
set fail_count_t5 0
set fail_count_t7 0
set fail_count_t2 0
set fail_count_t4 0
set fail_count_t6 0
set fail_count_t8 0
set fail_count_at13 0
set cur_time [timestamp]
set end_time $cur_time
incr end_time $test_interval

for {set count 1} {$cur_time <= $end_time} {incr count} {
    set cur_time [timestamp]

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t1\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t1
                send_user "FAIL: testusb t1\n"
                break
            }
            timeout {
                incr fail_count_t1
                send_user "timeout: testusb t1\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t3\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t3
                send_user "FAIL: testusb t3\n"
                break
            }
            timeout {
                incr fail_count_t3
                send_user "timeout: testusb t3\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t5\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t5
                send_user "FAIL: testusb t5\n"
                break
            }
            timeout {
                incr fail_count_t5
                send_user "timeout: testusb t5\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t7\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t7
                send_user "FAIL: testusb t7\n"
                break
            }
            timeout {
                incr fail_count_t7
                send_user "timeout: testusb t7\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t2\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t2
                send_user "FAIL: testusb t2\n"
                break
            }
            timeout {
                incr fail_count_t2
                send_user "timeout: testusb t2\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t4\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t4
                send_user "FAIL: testusb t4\n"
                break
            }
            timeout {
                incr fail_count_t4
                send_user "timeout: testusb t4\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t6\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t6
                send_user "FAIL: testusb t6\n"
                break
            }
            timeout {
                incr fail_count_t6
                send_user "timeout: testusb t6\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -t8\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_t8
                send_user "FAIL: testusb t8\n"
                break
            }
            timeout {
                incr fail_count_t8
                send_user "timeout: testusb t8\n"
                case_fail $case_num
            }
        }
    }

    incr case_num
    set timeout 10
    send "sudo ./src/testusb -D /proc/bus/usb/$gadget_bus/$gadget_dev -at13\r"
    while 1 {
        expect {
            -re "\[0-9]\\\.\[0-9]+ secs.*#" {
                case_pass $case_num
                break
            }
            -re "(error|-->).*#" {
                incr fail_count_at13
                send_user "FAIL: testusb at13\n"
                break
            }
            timeout {
                incr fail_count_at13
                send_user "timeout: testusb at13\n"
                case_fail $case_num
            }
        }
    }

    send_user "\n\ntest round $count finish\n\n"
}

incr case_num
if { $fail_count_t1 == 0 && $fail_count_t3 == 0 && $fail_count_t5 == 0 && $fail_count_t7 == 0 && $fail_count_t2 == 0 && $fail_count_t4 == 0 && $fail_count_t6 == 0 && $fail_count_t8 == 0 && $fail_count_at13 == 0} {
    send_user "No error when running testusb\n"
    case_pass $case_num
} else {
    send_user "test 1 fail $fail_count_t1 times\n"
    send_user "test 3 fail $fail_count_t3 times\n"
    send_user "test 5 fail $fail_count_t5 times\n"
    send_user "test 7 fail $fail_count_t7 times\n"
    send_user "test 2 fail $fail_count_t2 times\n"
    send_user "test 4 fail $fail_count_t4 times\n"
    send_user "test 6 fail $fail_count_t6 times\n"
    send_user "test 8 fail $fail_count_t8 times\n"
    send_user "test at13 fail $fail_count_at13 times\n"
    case_fail $case_num
}

incr case_num
set timeout 5
send "sudo rmmod ./configs/usbtest.ko\r"
while 1 {
    expect {
        -re "rmmod:|\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re "#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "sudo umount /proc/bus/usb\r"
while 1 {
    expect {
        -re "umount:|\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re "#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 4
send "mount\r"
while 1 {
    expect {
        -re "none on /proc/bus/usb type usbfs.*#" {
            case_fail $case_num
        }
        -re "#" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}


set spawn_id $kermit_spawn_id

incr case_num
set timeout 5
send "\3"
while 1 {
    expect {
        -re "disconnect.*done.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "modprobe -r gadgetfs\r"
while 1 {
    expect {
        -re "rmmod:|\[eE]rror|\[fF]ail" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "lsmod\r"
while 1 {
    expect {
        -re "gadgetfs" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"

log_file
