#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 5
step "Starting test"
set timeout 8
set flag 0

set case_num 0

incr case_num

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {
         set flag 1
         break
      }

      timeout {
                   
            break
         }
     }
}
expect "root:/bin>"

send -s "./pfbuttons_test\r"
while 1 {
   expect {
     -re  "open success /dev/input/event0" {
         
         puts "\nopen device success.\n"
         break
      }

      timeout {
                case_fail $case_num
          exit
         }
     }
}

puts "\n\nPlease enter the button 1 of the board.\n"
set timeout 3600

while 1 {
   expect {
     -re  "Event. Type.*Take a look LED_MUTE .* on.* off.*Event. Type" {
                case_pass $case_num
           break
      }

      timeout {            
                case_fail $case_num
          exit

         }
     }
}

incr case_num

puts "\n\nPlease enter the button 2 of the board.\n"
set timeout 3600

while 1 {
   expect {
     -re  "Event. Type.*Hear SND_BELL .* on.* off.*Event. Type" {
                case_pass $case_num
           break
      }

      timeout {            
                case_fail $case_num
          exit

         }
     }
}

incr case_num

puts "\n\nPlease enter the button 3 of the board.\n"
set timeout 3600

while 1 {
   expect {
     -re  "Event. Type.*Take a look LED_MISC .* on.* off.*Event. Type" {
                case_pass $case_num
           break
      }

      timeout {            
                case_fail $case_num
          exit

         }
     }
}

if { $board_type == "BF537-STAMP" } {

incr case_num

puts "\n\nPlease enter the button 4 of the board.\n"
set timeout 3600

while 1 {
   expect {
     -re  "Event. Type.*Take a look LED_SUSPEND .* on.* off.*Event. Type" {
                case_pass $case_num
           break
      }

      timeout {            
                case_fail $case_num
          exit

         }
     }
}
}
send -s "\3"

while 1 {
   expect {
      "root:/bin>" {
         send_log "pfbutton led test done!" 
         break
      }

      timeout {
            send_log "pfbutton test fail to exit. "
                case_fail $case_num
            exit
         }
     }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file




