#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test"
set timeout 8

set case_num 0

incr case_num

send -s "cd /bin\r"
while 1 {
   expect {
      "root:/bin>" {
            break
      }

      timeout {
         break
         }
     }
}

expect "root:/bin>"
send -s "event_test /dev/input/event0\r"
while 1 {
   expect {
     -re "Input device name.*gpio-keys.*Testing" {
         puts "\nPlease hit the PB1 buttons on the board...\n"
         expect {
                -re  "Event: time .* type .* code 256.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                case_pass $case_num
                        }

                timeout {
                case_fail $case_num
                        exit
                        }
                }

         incr case_num
         puts "\nPlease hit the PB2 buttons on the board...\n"
         expect {
                -re "Event: time .* type .* code 257.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                case_pass $case_num
                        }

                timeout {
                case_fail $case_num
                        exit
                        }
                }
          
         incr case_num
         puts "\nPlease hit the PB3 buttons on the board...\n"
         expect {
                -re "Event: time .* type .* code 258.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                case_pass $case_num
                        }

                timeout {
                case_fail $case_num
                        exit
                        }
                }
         
         if { $board_type == "BF537-STAMP" } {
         
         incr case_num
         puts "\nPlease hit the PB4 buttons on the board...\n"
         expect {
                -re "Event: time .* type .* code 259.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                case_pass $case_num
                        }

                timeout {
                case_fail $case_num
                        exit
                        }
                }
            }

         break
      }

      timeout {
                case_fail $case_num
      exit
         }
     }
}
sleep 3
send -s "\3"
expect -re "root.*>"
send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file




