#!/bin/sh

echo "Configuring network"

route del default 2> /dev/null

if [ -f /etc/config/netstart ]; then
	/bin/sh /etc/config/netstart
else
	/bin/sh /etc/default/netstart
fi

iptables --flush

if [ -f /etc/config/ipfilter ]; then
	/bin/sh /etc/config/ipfilter
elif [ -f /etc/default/ipfilter ]; then
	/bin/sh /etc/default/ipfilter
fi

