#!/usr/bin/expect
#
#Test program to test the msh patch.
#
log_file msh_test_log
send_user "Starting msh_test.exp\n"

set SERIAL_PORT_BAUD_RATE   "57600"
set TITLE "MSH Test"
set targetip 10.100.4.2
set serverip 10.100.4.174
set send_slow {1 .01}

set argc [llength $argv]
if { $argc < 1} {
   puts "Usage:  $argv0 tty-device \[srcdir targetip serverip\]"
   puts "   where tty-device is something like /dev/ttyS0"
   puts ""
   exit
}
# grab the user specified parameters.
set ttydev             [lindex $argv 0]

if { $argc >= 2} {
   set srcdir             [lindex $argv 1]
}

if { $argc >= 3} {
   set targetip           [lindex $argv 2]
}
if { $argc >= 4} {
   set serverip           [lindex $argv 3]
}

proc step { message } {

  global step_sequence_number

  puts "\n*******************************************************************"
  puts "STEP $step_sequence_number: $message\n\n"
  send_log "\n************** STEP $step_sequence_number: $message\n\n"
  incr step_sequence_number
}

set step_sequence_number    1

step "Start kermit"

# Now set up the kermit parameters.
#  I want these all contained in this file to make it easier for users.
#  This just builds up a list of commands which are sent to kermit.
#
set kparams     [list "set line $ttydev\r"]
lappend kparams "set speed $SERIAL_PORT_BAUD_RATE\r"
lappend kparams "set carrier-watch off\r"
lappend kparams "set handshake none\r"
lappend kparams "set flow-control none\r"
lappend kparams "robust\r"
lappend kparams "set file type bin\r"
lappend kparams "set file name lit\r"
lappend kparams "set rec pack 1000\r"
lappend kparams "set send pack 1000\r"
lappend kparams "set window 5\r"
set nkparams [llength $kparams]

set timeout 3
spawn kermit
# We need to save the id because resetting the board will overwrite it.
set kermit_spawn_id $spawn_id

while 1 {
	expect {
	        "Type ?" { }
		"ermit>" { break }
		"not found" {
                   tee "ERROR: Failed to start up kermit"
                   exit
		}
		timeout {
                   tee "ERROR: Time out starting up kermit"
                   exit
		}
	}
}

for {set i 0} {$i < $nkparams} {incr i} {
    send -s [lindex $kparams $i]

    while 1 {
	  expect {
		 "ermit>" { break }

		 "\\?\[A-Z]" {
                    tee "ERROR: Failed to set up kermit parameters"
                    exit
		 }

		 timeout {
                    tee "ERROR: Time out setting up kermit parameters"
                    exit
		 }
	  }
    }
}

send -s "connect\r"
while 1 {
	expect {
		"ype the escape character*" {
		     break  }
		timeout {
		     puts "\nERROR: Can't connect to serial port\n"
		     exit }
	}
}
#
#  Ok, Kermit is running and connected to the board.
#
step "Restart the board."

send_user "Try to figure out if we are in u-boot or the kernel"
set where_are_we 0
send "version\r"
set timeout 20
expect {

    "U-Boot" {
        send_user "We are in u-boot\n"
        set where_are_we "uboot"
    }

    "Linux" {
        send_user "We are in the kernel\n"
        set where_are_we "kernel"
    }

    timeout {
        send_user "Can't tell if we are in u-boot or the kernel\n"
    }
}

if { $where_are_we == "uboot" } {
    set timeout 50
    expect ">"
    send_user "sending reset\n"
    send "reset\r"
} else {
    if { $where_are_we == "kernel" } {
        set timeout 60
        expect ">"
        send_user "sending reboot\n"
        send "reboot\r"
    } else {
        # If we don't know where we are, hit control-C and enter
        set timeout 10
        expect "*"
        expect "*"
        send_user "sending control-C\n"
        send "\3"
        sleep 1
        send "\r"
    }
}

send -s "set bootargs root=/dev/mtdblock0 rw\r"
expect ">"
send -s "save\r"
expect ">"

set timeout 2
set flag 0
send -s "tftpboot\r"
while 1 {
   expect {
      "TFTP" {
         set flag 1
         set timeout 30
      }
      ">" {
         break
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

set timeout 1
set flag 0
send -s "bootelf\r"
while 1 {
   expect {
      "Loading .text" {
         set flag 1
         set timeout 30
      }
      "> " {
         break
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

set timeout 3
send -s "ifconfig eth0 $targetip\r"
expect {
	"> " {
	}

        timeout {
		puts "Fail to config eth0\r"
		exit
        }
}


step "Start $TITLE\r"

set timeout 10
set case_num 0

spawn rcp ./msh_testcase root@$targetip:/
send -s "chmod +x /msh_testcase"
incr case_num
send -s "sh /msh_testcase\r"
expect {
        "executed" {
                send_log "\rCase $case_num ...PASS\r"

        }
        timeout {
                send_log "\rCase $case_num ...FAIL\r"
                send_log "$TITLE ............\[FAIL\]\r"
                exit
        }
}


send_log "\r$TITLE ............\[PASS\]\r"

log_file

send_user "Ending msh_test.exp\n"
