#!/bin/sh
# the script for test msh function call
test_function1(){
	echo " $0 executed !"
}
test_function2()
{
	test_function1
}
# check if function is executed correctly
echo "before function exec"
test_function2
echo "finish exec"

