#!/usr/bin/expect

#
#Test program to test the msh patch.
#

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Start $TITLE\r"

send "ifconfig eth0 $targetip\r"
while 1 {
   sleep 3
   expect {
       -re $kernel_prompt {
         puts "ifconfig set success.\n"
         break
      }

      timeout {
            puts "Fail ifconfig. "
            break
         }
     }
}

sleep 10
set timeout 10
set case_num 0

spawn rcp ./msh_testcase root@$targetip:/

set spawn_id $kermit_spawn_id

send -s "chmod +x /msh_testcase\r"
expect  -re $kernel_prompt
incr case_num
send -s "./msh_testcase\r"
while 1 {
expect {
        "executed" {
                expect "finish exec"
                case_pass $case_num
                break

        }
        timeout {
                case_fail $case_num
                exit
        }
 }
}

send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file

send -s "reboot\r"

while 1 {
       expect {
         "Hit any key " {
             send "\r"
             expect ">"
             break
         }

         timeout {
             break
         }
      }
   }

