#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
set bootargs  $bootargs_param3
source ../reboot_kernel.exp

step "Starting test."
set timeout 8

set MemTotal_HIGH  32000
set MemTotal_LOW  28000

set case_num 0
incr case_num
                       
expect  -re $kernel_prompt
send -s "cat /proc/meminfo\r"
while 1 {
    expect {
        -re "MemTotal: +(\[0-9]+) kB" {
            set MemTotal $expect_out(1,string)
            case_pass $case_num
            break
        }

        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
if { $MemTotal < $MemTotal_HIGH  &&  $MemTotal > $MemTotal_LOW } {
    case_pass $case_num
} else {
    case_fail $case_num
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending $argv0\n"

log_file
