#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
set bootargs  $bootargs_param5
source ../reboot_kernel.exp

step "Starting test."
set timeout 8
set case_num 0

incr case_num
send "dmesg|head -n 20\r"
while 1 {
    expect {
        -re "Board Memory: 64MB.*Kernel Managed Memory: 32MB.*0x\[0-9a-f]+-0x02000000\r\n\[A-Z]" {
            expect -re $kernel_prompt
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending $argv0\n"

log_file
