#
# Automatically generated make config: don't edit
#

#
# SnapGear Apps/Libs
#
# CONFIG_USER_CGI_ETH1_BRIDGE is not set
# CONFIG_USER_CGI_NO_SERIAL is not set
CONFIG_USER_CGI_NO_COM2=y
# CONFIG_USER_CGI_NO_DIALIN is not set
CONFIG_USER_CGI_HELP=y
# CONFIG_USER_CGI_DMZ is not set
# CONFIG_USER_CGI_GUEST is not set
# CONFIG_USER_CGI_LOAD_BALANCING is not set
CONFIG_USER_CGI_HIGHAVAIL=y
# CONFIG_USER_CGI_VLAN is not set
# CONFIG_USER_CGI_BRIDGE is not set
# CONFIG_USER_CGI_LOOPBACK is not set
# CONFIG_USER_CGI_CUSTOM_HTML is not set
CONFIG_USER_CGI_FIXED_PRIMARY_MEDIA=y
CONFIG_USER_CGI_NO_AUTO_DUPLEX=y
CONFIG_USER_CGI_NO_100BASET4=y
# CONFIG_USER_CGI_ETH_GENERIC is not set
CONFIG_USER_CGI_WIZARD=y
# CONFIG_USER_CGI_NO_SUPPORT_REPORT is not set
# CONFIG_USER_CGI_NO_FW_RULES is not set
# CONFIG_USER_CGI_NO_EDIT_CONFIG is not set
# CONFIG_USER_CGI_ROOT_ONLY is not set
# CONFIG_USER_CGI_NO_TZO_AD is not set
CONFIG_USER_CGI_MAX_IPSEC_TUNNELS=0
CONFIG_USER_FIREWALL_TOOLS=y
# CONFIG_USER_FIREWALL_ACCEPT_DHCP is not set
# CONFIG_USER_FIREWALL_SCRIPT_ONLY is not set
# CONFIG_USER_AES_PERF is not set
CONFIG_USER_BR_BR=y
# CONFIG_USER_DESTEST_DESTEST is not set
# CONFIG_USER_DESTEST_DESPERF is not set
# CONFIG_USER_EMCTEST_EMCECHO is not set
# CONFIG_USER_EMCTEST_EMCTEST is not set
# CONFIG_USER_FACTORY_FACTTEST is not set
# CONFIG_USER_GDSD_GDSD_INET is not set
CONFIG_USER_GRE_GRE=y
CONFIG_USER_IDB_IDB=y
CONFIG_USER_IPSEC_CONFIGURATOR=y
CONFIG_USER_REDIALER_REDIALER=y
# CONFIG_USER_PKTDELAY_PKTDELAY is not set
# CONFIG_USER_PROTECT is not set
# CONFIG_USER_SETKEY_SETKEY is not set
# CONFIG_USER_IOD is not set
# CONFIG_USER_SWTEST_SWCONFIG is not set
# CONFIG_USER_SWTEST_SWTEST is not set
CONFIG_USER_MGMT_MGMT=y
CONFIG_USER_SGSNMPD_AGENT=y
CONFIG_USER_SGSNMPD_SNAPGEAR=y
CONFIG_USER_SGSNMPD_AGENT=y
CONFIG_USER_SGSNMPD_UDP=y
CONFIG_USER_SGSNMPD_TCP=y
CONFIG_USER_SGSNMPD_SNAPGEAR=y
# CONFIG_USER_SGSNMPD_SERVGATE is not set
# CONFIG_USER_TQRECV_TQRECV is not set
# CONFIG_USER_UPNPD is not set
# CONFIG_USER_WINSD_WS is not set
CONFIG_LIB_TINYTCL=y
CONFIG_USER_CGI_PRIMARY_ETHERNET=0

#
# Core Applications
#
CONFIG_USER_INIT_INIT=y
CONFIG_USER_INIT_CONSOLE_SH=y
CONFIG_USER_INIT_RUN_FIREWALL=y
# CONFIG_USER_INIT_CONF is not set
CONFIG_USER_SASH_SH=y
# CONFIG_USER_SH_SH is not set
# CONFIG_USER_NWSH_SH is not set
# CONFIG_USER_BASH_BASH is not set
# CONFIG_USER_MSH_SH is not set
# CONFIG_USER_OTHER_SH is not set
# CONFIG_USER_SASH_HISTORY is not set
# CONFIG_USER_SASH_PS is not set
CONFIG_USER_SASH_REBOOT=y
# CONFIG_USER_SASH_SHUTDOWN is not set
CONFIG_USER_INIT_EXPAND=y
CONFIG_USER_INIT_EXPAND_NOZEROES=y
# CONFIG_USER_VERSION_VERSION is not set
CONFIG_USER_LOGIN_LOGIN=y
CONFIG_USER_OLD_PASSWORDS=y
CONFIG_LIB_LIBCRYPT_OLD=y
# CONFIG_USER_ONLY_ROOT is not set
# CONFIG_USER_AGETTY_AGETTY is not set
CONFIG_USER_GETTYD_GETTYD=y
# CONFIG_USER_LOGIN_PASSWD is not set
# CONFIG_USER_CRON_CRON is not set

#
# Real Time Clock
#
# CONFIG_USER_HWCLOCK_HWCLOCK is not set
# CONFIG_USER_RTC_M41T11 is not set
# CONFIG_USER_RTC_DS1302 is not set

#
# Vixie-cron
#
# CONFIG_USER_VIXIECRON_CRON is not set
# CONFIG_USER_VIXIECRON_CRONTAB is not set

#
# at
#
# CONFIG_USER_AT_AT is not set
# CONFIG_USER_AT_ATD is not set
# CONFIG_USER_AT_ATRUN is not set

#
# Library Configuration
#

#
# Force build (Normally built when required)
#
# CONFIG_LIB_FLEX_FORCE is not set
# CONFIG_LIB_LIBAES_FORCE is not set
# CONFIG_LIB_LIBDES_FORCE is not set
# CONFIG_LIB_LIBSSL_FORCE is not set
# CONFIG_LIB_LIBGMP_FORCE is not set
# CONFIG_LIB_LIBG_FORCE is not set
# CONFIG_LIB_LIBLDAP_FORCE is not set
# CONFIG_LIB_LIBNET_FORCE is not set
# CONFIG_LIB_LIBPAM_FORCE is not set
# CONFIG_LIB_LIBPCAP_FORCE is not set
# CONFIG_LIB_LIBPCRE_FORCE is not set
# CONFIG_LIB_ZLIB_FORCE is not set
# CONFIG_LIB_LIBBZ2_FORCE is not set
# CONFIG_LIB_LIBATM_FORCE is not set
# CONFIG_LIB_LIBPNG_FORCE is not set
# CONFIG_LIB_LIBJPEG_FORCE is not set
# CONFIG_LIB_LIBUPNP_FORCE is not set
# CONFIG_LIB_NCURSES_FORCE is not set
# CONFIG_LIB_STLPORT is not set
# CONFIG_LIB_EXPAT_FORCE is not set
# CONFIG_LIB_ADNS_FORCE is not set
# CONFIG_LIB_ARES_FORCE is not set
# CONFIG_LIB_LIBIDN_FORCE is not set
# CONFIG_LIB_LIBCURL_FORCE is not set
# CONFIG_LIB_LIBCRYPT_OLD_FORCE is not set

#
# Library Configuration
#
# CONFIG_LIB_UC_LIBC_TIMEZONE is not set

#
# Flash Tools
#
CONFIG_USER_FLASHW_FLASHW=y
CONFIG_USER_NETFLASH_NETFLASH=y
CONFIG_USER_FLASH_FLASH=y
CONFIG_USER_NETFLASH_WITH_FTP=y
CONFIG_USER_NETFLASH_WITH_CGI=y
CONFIG_USER_NETFLASH_VERSION=y
# CONFIG_USER_NETFLASH_VERSION_ALLOW_CURRENT is not set
# CONFIG_USER_NETFLASH_VERSION_ALLOW_OLDER is not set
CONFIG_USER_NETFLASH_DECOMPRESS=y
CONFIG_LIB_ZLIB=y
# CONFIG_USER_NETFLASH_AUTODECOMPRESS is not set
# CONFIG_USER_NETFLASH_HMACMD5 is not set
# CONFIG_USER_RECOVER_BIOS is not set
# CONFIG_USER_NETFLASH_CRYPTO is not set
# CONFIG_USER_RECOVER_STATIC_TFTP is not set
# CONFIG_USER_RECOVER_RECOVER is not set
# CONFIG_USER_SETMAC_SETMAC is not set

#
# uCbootloader utils
#
# CONFIG_USER_BOOTTOOLS_LOADER is not set
# CONFIG_USER_BOOTTOOLS_HIMEMLOADER is not set
# CONFIG_USER_BOOTTOOLS_PRINTBENV is not set
# CONFIG_USER_BOOTTOOLS_SETBENV is not set
# CONFIG_USER_BOOTTOOLS_RESET is not set

#
# MTD utils
#
# CONFIG_USER_MTDUTILS is not set

#
# Filesystem Applications
#
CONFIG_USER_FLATFSD_FLATFSD=y
CONFIG_USER_FLATFSD_AUTO=y
# CONFIG_USER_FLATFSD_USE_FLASH_FS is not set
# CONFIG_USER_FLATFSD_DISKLIKE is not set
# CONFIG_USER_MOUNT_MOUNT is not set
# CONFIG_USER_MOUNT_UMOUNT is not set
# CONFIG_USER_FDISK_FDISK is not set
# CONFIG_USER_FDISK_SFDISK is not set

#
# EXT2
#
# CONFIG_USER_E2FSPROGS_E2FSCK_E2FSCK is not set
# CONFIG_USER_E2FSPROGS_MISC_MKE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_BADBLOCKS is not set
# CONFIG_USER_E2FSPROGS_MISC_CHATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_DUMPE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_E2LABEL is not set
# CONFIG_USER_E2FSPROGS_MISC_FSCK is not set
# CONFIG_USER_E2FSPROGS_MISC_LSATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_MKLOST_FOUND is not set
# CONFIG_USER_E2FSPROGS_MISC_TUNE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_UUIDGEN is not set

#
# RESIERFS
#
# CONFIG_USER_REISERFSPROGS is not set
# CONFIG_USER_REISERFSPROGS_DEBUGRESIERFS is not set
# CONFIG_USER_REISERFSPROGS_MKREISERFS is not set
# CONFIG_USER_REISERFSPROGS_REISERFSCK is not set
# CONFIG_USER_REISERFSPROGS_RESIZE_REISERFS is not set
# CONFIG_USER_REISERFSPROGS_UNPACK is not set

#
# SAMBA
#
# CONFIG_USER_SAMBA is not set
# CONFIG_USER_SAMBA_SMBD is not set
# CONFIG_USER_SAMBA_NMBD is not set
# CONFIG_USER_SAMBA_SMBMOUNT is not set
# CONFIG_USER_SAMBA_SMBUMOUNT is not set
# CONFIG_USER_SAMBA_SHARED is not set

#
# SMBFS
#
# CONFIG_USER_SMBMOUNT_SMBMOUNT is not set
# CONFIG_USER_SMBMOUNT_SMBUMOUNT is not set

#
# CRAMFS
#
# CONFIG_USER_CRAMFS_CRAMFSCK is not set
# CONFIG_USER_CRAMFS_MKCRAMFS is not set

#
# MSDOS
#
# CONFIG_USER_DOSFSTOOLS_MKDOSFS is not set
# CONFIG_USER_DOSFSTOOLS_DOSFSCK is not set

#
# Network Applications
#
# CONFIG_USER_APPWEB_APPWEB is not set
# CONFIG_USER_ASTERISK is not set
CONFIG_USER_FNORD_HTTPD=y
# CONFIG_USER_FNORD_NOAUTH is not set
CONFIG_USER_BPALOGIN_BPALOGIN=y
# CONFIG_USER_BR2684CTL_BR2684CTL is not set
# CONFIG_USER_BRCFG_BRCFG is not set
CONFIG_USER_BRCTL_BRCTL=y
# CONFIG_USER_DHCPCD_DHCPCD is not set
CONFIG_USER_DHCPCD_NEW_DHCPCD=y
# CONFIG_USER_DHCPD_DHCPD is not set
CONFIG_USER_DHCP_ISC_SERVER_DHCPD=y
# CONFIG_USER_DHCP_ISC_CLIENT_DHCLIENT is not set
CONFIG_USER_DHCP_ISC_RELAY_DHCRELAY=y
CONFIG_USER_DIALD_DIALD=y
CONFIG_USER_DISCARD_DISCARD=y
CONFIG_USER_DISCARD_NO_INSTALL=y
CONFIG_USER_DISCARD_INETD_ECHO=y
CONFIG_USER_DISCARD_ECHO_NO_INSTALL=y
CONFIG_USER_DNSMASQ_DNSMASQ=y
# CONFIG_USER_DROPBEAR_DROPBEAR is not set
# CONFIG_USER_ETHATTACH_ETHATTACH is not set
# CONFIG_USER_ETHTOOL_ETHTOOL is not set
CONFIG_USER_EZIPUPDATE_EZIPUPDATE=y
# CONFIG_USER_FAKEIDENTD_IDENTD is not set
# CONFIG_USER_DDNS3_CLIENT_DDNS3 is not set
# CONFIG_USER_FTP_FTP_FTP is not set
# CONFIG_USER_FTPD_FTPD is not set
CONFIG_USER_FREESWAN=y
# CONFIG_USER_IPSEC_KEEPALIVE is not set
CONFIG_USER_FREESWAN_PLUTO_PLUTO=y
CONFIG_LIB_LIBGMP=y
CONFIG_LIB_LIBDES=y
CONFIG_USER_FREESWAN_PLUTO_WHACK=y
CONFIG_USER_FREESWAN_UTILS_RANBITS=y
CONFIG_USER_FREESWAN_UTILS_RSASIGKEY=y
CONFIG_LIB_LIBGMP=y
CONFIG_USER_FREESWAN_KLIPS_EROUTE=y
CONFIG_USER_FREESWAN_KLIPS_KLIPSDEBUG=y
CONFIG_USER_FREESWAN_KLIPS_SPI=y
CONFIG_USER_FREESWAN_KLIPS_SPIGRP=y
CONFIG_USER_FREESWAN_KLIPS_TNCFG=y
# CONFIG_USER_FSWCERT_FSWCERT is not set
# CONFIG_USER_OPENSWAN is not set
# CONFIG_USER_HTTPD_HTTPD is not set
# CONFIG_USER_HTTPTUNNEL_CLIENT is not set
# CONFIG_USER_HTTPTUNNEL_SERVER is not set
# CONFIG_USER_IFATTACH_IFATTACH is not set
CONFIG_USER_INETD_INETD=y
# CONFIG_USER_IPCHAINS_IPCHAINS is not set
# CONFIG_USER_IPFWADM_IPFWADM is not set
# CONFIG_USER_IPMASQADM_IPMASQADM is not set
# CONFIG_USER_IPPORTFW_IPPORTFW is not set
# CONFIG_USER_IPREDIR_IPREDIR is not set
CONFIG_USER_IPROUTE2=y
CONFIG_USER_IPROUTE2_TC_TC=y
# CONFIG_USER_IPROUTE2_IP_IFCFG is not set
CONFIG_USER_IPROUTE2_IP_IP=y
CONFIG_USER_IPROUTE2_IP_ROUTEF=y
CONFIG_USER_IPROUTE2_IP_ROUTEL=y
CONFIG_USER_IPROUTE2_IP_RTACCT=y
CONFIG_USER_IPROUTE2_IP_RTMON=y
# CONFIG_USER_IPSENTINEL_IPSENTINEL is not set
CONFIG_USER_IPTABLES_IPTABLES=y
# CONFIG_USER_IPTABLES_IP6TABLES is not set
# CONFIG_USER_IPUTILS_IPUTILS is not set
# CONFIG_USER_KENDIN_CONFIG is not set
# CONFIG_USER_KLAXON_KLAXON is not set
CONFIG_USER_L2TPD_L2TPD=y
CONFIG_USER_LINUXIGD_LINUXIGD=y
CONFIG_LIB_LIBUPNP=y
# CONFIG_USER_LINUXIGD_DEFAULT is not set
# CONFIG_USER_LOATTACH_LOATTACH is not set
# CONFIG_USER_LRPSTAT_LRPSTAT is not set
CONFIG_USER_SMTP_SMTPCLIENT=y
# CONFIG_USER_MAIL_MAIL_IP is not set
# CONFIG_USER_MARADNS_MARADNS is not set
# CONFIG_USER_MINI_HTTPD_MINI_HTTPD is not set
CONFIG_USER_MSNTP_MSNTP=y
# CONFIG_USER_NESSUS_NASL is not set
# CONFIG_USER_NETCAT_NETCAT is not set
# CONFIG_USER_NETSTAT_NAT_NETSTAT_NAT is not set
# CONFIG_USER_MARADNS_ZONESERVER is not set
# CONFIG_USER_NTPCLIENT_NTPCLIENT is not set
# CONFIG_USER_NTPCLIENT_ADJTIMEX is not set
# CONFIG_USER_NTPD_NTPD is not set
# CONFIG_USER_NTPD_NTPDATE is not set
# CONFIG_USER_NTPD_NTPQ is not set
# CONFIG_USER_OPENSSL_APPS is not set
CONFIG_USER_PING_PING=y
# CONFIG_USER_PLUG_PLUG is not set
# CONFIG_USER_POP3PROXY_POP3PROXY is not set
# CONFIG_USER_PORTMAP_PORTMAP is not set
CONFIG_USER_PPPD_PPPD_PPPD=y
CONFIG_USER_PPPD_WITH_MPPE=y
CONFIG_LIB_LIBDES=y
CONFIG_USER_PPPD_WITH_TACACS=y
CONFIG_USER_PPPD_WITH_RADIUS=y
CONFIG_USER_PPPD_WITH_PPPOE=y
# CONFIG_USER_PPPD_WITH_PPPOA is not set
CONFIG_USER_PPPD_PPPOE_RETRIES=5
CONFIG_USER_PPPD_NO_AT_REDIRECTION=y
CONFIG_USER_PPTPD_PPTPCTRL=y
CONFIG_USER_PPTPD_PPTPD=y
CONFIG_USER_PPTP_CLIENT_PPTP=y
CONFIG_USER_PPTP_CLIENT_PPTP_CALLMGR=y
# CONFIG_USER_PROFTPD_PROFTPD is not set
# CONFIG_USER_RADVD_RADVD is not set
# CONFIG_USER_RDATE_RDATE is not set
# CONFIG_USER_ROUTED_ROUTED is not set
# CONFIG_USER_RP_PPPOE_PPPOE is not set
# CONFIG_USER_RSYSLOGD_RSYSLOGD is not set
# CONFIG_USER_SER_SER is not set
# CONFIG_USER_SETHDLC_SETHDLC is not set
# CONFIG_USER_SLATTACH_SLATTACH is not set
# CONFIG_USER_SMTP_SMTPFILTER is not set
# CONFIG_USER_SNMPD_SNMPD is not set
# CONFIG_USER_SNORT_SNORT is not set
# CONFIG_USER_SPEEDTOUCH_MODEM_RUN is not set
# CONFIG_USER_STUNNEL_STUNNEL is not set
# CONFIG_USER_SSLWRAP_SSLWRAP is not set
# CONFIG_USER_SQUID_SQUID is not set
# CONFIG_USER_SSH_SSH is not set
# CONFIG_USER_SSH_SSHD is not set
# CONFIG_USER_SSH_SSHKEYGEN is not set
# CONFIG_USER_STP_STP is not set
# CONFIG_USER_TCPWRAP_TCPD is not set
# CONFIG_USER_TCPBLAST_TCPBLAST is not set
CONFIG_USER_TCPDUMP_TCPDUMP=y
CONFIG_LIB_LIBPCAP=y
CONFIG_USER_TELNETD_TELNETD=y
# CONFIG_USER_TELNETD_DOES_NOT_USE_OPENPTY is not set
# CONFIG_USER_TELNET_TELNET is not set
# CONFIG_USER_TFTP_TFTP is not set
# CONFIG_USER_TFTPD_TFTPD is not set
# CONFIG_USER_THTTPD_THTTPD is not set
CONFIG_USER_TRACEROUTE_TRACEROUTE=y
# CONFIG_USER_UCDSNMP_SNMPD is not set
CONFIG_USER_VCONFIG_VCONFIG=y
# CONFIG_USER_VPNLED_VPNLED is not set
# CONFIG_USER_WGET is not set
# CONFIG_USER_ZEBRA_ZEBRA_ZEBRA is not set

#
# Net-tools
#
# CONFIG_USER_NET_TOOLS_ARP is not set
# CONFIG_USER_NET_TOOLS_HOSTNAME is not set
CONFIG_USER_NET_TOOLS_IFCONFIG=y
# CONFIG_USER_NET_TOOLS_NAMEIF is not set
# CONFIG_USER_NET_TOOLS_NETSTAT is not set
# CONFIG_USER_NET_TOOLS_PLIPCONFIG is not set
# CONFIG_USER_NET_TOOLS_RARP is not set
CONFIG_USER_NET_TOOLS_ROUTE=y
# CONFIG_USER_NET_TOOLS_SLATTACH is not set
CONFIG_USER_NET_TOOLS_MII_TOOL=y
# CONFIG_USER_NET_TOOLS_MII_TOOL_FEC is not set

#
# Wireless-tools
#
CONFIG_USER_WIRELESS_TOOLS=y
CONFIG_USER_WIRELESS_TOOLS_IWCONFIG=y
CONFIG_USER_WIRELESS_TOOLS_IWGETID=y
CONFIG_USER_WIRELESS_TOOLS_IWLIST=y
CONFIG_USER_WIRELESS_TOOLS_IWPRIV=y
CONFIG_USER_WIRELESS_TOOLS_IWSPY=y
CONFIG_USER_HOSTAP_HOSTAP=y
# CONFIG_USER_HOSTAP_PCI is not set
CONFIG_USER_HOSTAP_CS=y
# CONFIG_USER_HOSTAP_HOSTAPD is not set
# CONFIG_USER_WLAN_NG is not set

#
# Miscellaneous Applications
#
# CONFIG_USER_LANG_A60 is not set
# CONFIG_USER_ARJ_ARJ is not set
# CONFIG_USER_BZIP2_BZIP2 is not set
# CONFIG_USER_CAL_CAL is not set
CONFIG_USER_CHAT_CHAT=y
# CONFIG_USER_CHAT_CHAT_NETWORK is not set
# CONFIG_USER_CKSUM_CKSUM is not set
# CONFIG_USER_CLAMAV_CLAMAV is not set
# CONFIG_USER_CLOCK_CLOCK is not set
# CONFIG_USER_CPU_CPU is not set
# CONFIG_USER_CRYPTO_TOOLS_CRYPTOTEST is not set
# CONFIG_USER_CRYPTO_TOOLS_CRYPTOKEYTEST is not set
# CONFIG_USER_CAL_DATE is not set
# CONFIG_USER_DHRYSTONE_DHRYSTONE is not set
# CONFIG_USER_DE2TSCAL_DE2TSCAL is not set
# CONFIG_USER_EXPAT_EXAMPLES is not set
# CONFIG_USER_FROB_LED_FROB_LED is not set
# CONFIG_USER_GDB_GDBREPLAY is not set
# CONFIG_USER_GDB_GDBSERVER is not set
# CONFIG_USER_GDBSERVER_GDBREPLAY is not set
# CONFIG_USER_GDBSERVER_GDBSERVER is not set
# CONFIG_USER_GREP_GREP is not set
CONFIG_USER_HD_HD=y
# CONFIG_USER_LCD_LCD is not set
# CONFIG_USER_LEDCON_LEDCON is not set
# CONFIG_USER_LHA_LHA is not set
# CONFIG_USER_LILO_LILO is not set
# CONFIG_USER_LISSA_LISSA is not set
# CONFIG_USER_LPR is not set
# CONFIG_USER_USBCBI_USBCBI is not set
# CONFIG_USER_USBISO_USBISO is not set
# CONFIG_USER_MATH_TEST is not set
# CONFIG_USER_MAWK_AWK is not set
# CONFIG_USER_MYSQL is not set
CONFIG_USER_NULL_NULL=y
# CONFIG_USER_PALMBOT_PALMBOT is not set
CONFIG_USER_PCMCIA_CS=y
# CONFIG_USER_PERL_PERL is not set
# CONFIG_USER_PYTHON_PYTHON is not set
# CONFIG_USER_READPROFILE_READPROFILE is not set
# CONFIG_USER_ROOTLOADER_ROOTLOADER is not set
# CONFIG_USER_SETSERIAL_SETSERIAL is not set
# CONFIG_USER_TRIPWIRE_SIGGEN is not set
# CONFIG_USER_STRACE_STRACE is not set
# CONFIG_USER_STTY_STTY is not set
# CONFIG_USER_TCSH_TCSH is not set
# CONFIG_USER_TINYTCL_TCLSH is not set
# CONFIG_LIB_TINYTCL_STATIC is not set
# CONFIG_USER_THREADDEMOS_THREADDEMOS is not set
CONFIG_USER_TIP_TIP=y
# CONFIG_USER_TRIPWIRE_TRIPWIRE is not set
# CONFIG_USER_UNRAR_UNRAR is not set
# CONFIG_USER_UNZIP_UNZIP is not set
# CONFIG_USER_UNZOO_UNZOO is not set
# CONFIG_USER_LRZSZ_LRZSZ is not set

#
# LIRC
#
# CONFIG_USER_LIRC is not set

#
# QSPI
#
# CONFIG_MCF_QSPI is not set

#
# Editors
#
# CONFIG_USER_LEVEE_VI is not set
# CONFIG_USER_ELVISTINY_VI is not set

#
# Audio tools
#
# CONFIG_USER_MP3PLAY_MP3PLAY is not set
# CONFIG_USER_OGGPLAY_OGG123 is not set
# CONFIG_USER_OGGPLAY_EXAMPLE is not set
# CONFIG_USER_MUSICBOX_MUSICBOX is not set
# CONFIG_USER_PLAY_PLAY is not set
# CONFIG_USER_PLAY_TONE is not set
# CONFIG_USER_VPLAY_VPLAY is not set
# CONFIG_USER_VPLAY_VREC is not set
# CONFIG_USER_VPLAY_MIXER is not set
# CONFIG_USER_PLAYRT_PLAYRT is not set

#
# Video tools
#
# CONFIG_USER_CAMSERV is not set
# CONFIG_USER_W3CAM_VIDCAT is not set
# CONFIG_USER_W3CAM_W3CAMD is not set

#
# Fileutils tools
#
# CONFIG_USER_FILEUTILS_CAT is not set
# CONFIG_USER_FILEUTILS_CHGRP is not set
# CONFIG_USER_FILEUTILS_CHMOD is not set
# CONFIG_USER_FILEUTILS_CHOWN is not set
# CONFIG_USER_FILEUTILS_CMP is not set
# CONFIG_USER_FILEUTILS_CP is not set
# CONFIG_USER_FILEUTILS_DD is not set
# CONFIG_USER_FILEUTILS_GREP is not set
# CONFIG_USER_FILEUTILS_L is not set
# CONFIG_USER_FILEUTILS_LN is not set
# CONFIG_USER_FILEUTILS_LS is not set
# CONFIG_USER_FILEUTILS_MKDIR is not set
# CONFIG_USER_FILEUTILS_MKFIFO is not set
# CONFIG_USER_FILEUTILS_MKNOD is not set
# CONFIG_USER_FILEUTILS_MORE is not set
# CONFIG_USER_FILEUTILS_MV is not set
# CONFIG_USER_FILEUTILS_RM is not set
# CONFIG_USER_FILEUTILS_RMDIR is not set
# CONFIG_USER_FILEUTILS_SYNC is not set
# CONFIG_USER_FILEUTILS_TOUCH is not set

#
# Shutils tools
#
# CONFIG_USER_SHUTILS_BASENAME is not set
# CONFIG_USER_SHUTILS_DATE is not set
# CONFIG_USER_SHUTILS_DIRNAME is not set
# CONFIG_USER_SHUTILS_ECHO is not set
# CONFIG_USER_SHUTILS_FALSE is not set
# CONFIG_USER_SHUTILS_LOGNAME is not set
# CONFIG_USER_SHUTILS_PRINTENV is not set
# CONFIG_USER_SHUTILS_PWD is not set
# CONFIG_USER_SHUTILS_TRUE is not set
# CONFIG_USER_SHUTILS_UNAME is not set
# CONFIG_USER_SHUTILS_WHICH is not set
# CONFIG_USER_SHUTILS_WHOAMI is not set
# CONFIG_USER_SHUTILS_YES is not set

#
# Sysutils tools
#
# CONFIG_USER_SYSUTILS_REBOOT is not set
# CONFIG_USER_SYSUTILS_SHUTDOWN is not set
# CONFIG_USER_SYSUTILS_DF is not set
# CONFIG_USER_SYSUTILS_FREE is not set
# CONFIG_USER_SYSUTILS_HOSTNAME is not set
# CONFIG_USER_SYSUTILS_KILL is not set
# CONFIG_USER_SYSUTILS_PS is not set

#
# Procps tools
#
# CONFIG_USER_PROCPS_FREE is not set
# CONFIG_USER_PROCPS_KILL is not set
# CONFIG_USER_PROCPS_PGREP is not set
# CONFIG_USER_PROCPS_PKILL is not set
# CONFIG_USER_PROCPS_PS is not set
# CONFIG_USER_PROCPS_SNICE is not set
CONFIG_USER_PROCPS_SYSCTL=y
# CONFIG_USER_PROCPS_TLOAD is not set
# CONFIG_USER_PROCPS_TOP is not set
# CONFIG_USER_PROCPS_UPTIME is not set
# CONFIG_USER_PROCPS_VMSTAT is not set
# CONFIG_USER_PROCPS_W is not set
# CONFIG_USER_PROCPS_WATCH is not set

#
# PCI utilities
#
# CONFIG_USER_PCIUTILS_LSPCI is not set
# CONFIG_USER_PCIUTILS_SETPCI is not set

#
# 
#
# CONFIG_USER_CXXTEST_CXXTEST is not set

#
# BusyBox
#
CONFIG_USER_BUSYBOX_BUSYBOX=y

#
# Applets
#
# CONFIG_USER_BUSYBOX_ADDGROUP is not set
# CONFIG_USER_BUSYBOX_ADDUSER is not set
# CONFIG_USER_BUSYBOX_ADJTIMEX is not set
# CONFIG_USER_BUSYBOX_AR is not set
CONFIG_USER_BUSYBOX_ARPING=y
# CONFIG_USER_BUSYBOX_AWK is not set
# CONFIG_USER_BUSYBOX_BASENAME is not set
# CONFIG_USER_BUSYBOX_BUNZIP2 is not set
# CONFIG_USER_BUSYBOX_CAL is not set
# CONFIG_USER_BUSYBOX_CAT is not set
# CONFIG_USER_BUSYBOX_CHGRP is not set
# CONFIG_USER_BUSYBOX_CHMOD is not set
# CONFIG_USER_BUSYBOX_CHOWN is not set
# CONFIG_USER_BUSYBOX_CHROOT is not set
# CONFIG_USER_BUSYBOX_CHVT is not set
# CONFIG_USER_BUSYBOX_CLEAR is not set
# CONFIG_USER_BUSYBOX_CMP is not set
# CONFIG_USER_BUSYBOX_CP is not set
# CONFIG_USER_BUSYBOX_CPIO is not set
# CONFIG_USER_BUSYBOX_CROND is not set
# CONFIG_USER_BUSYBOX_CRONTAB is not set
# CONFIG_USER_BUSYBOX_CUT is not set
CONFIG_USER_BUSYBOX_DATE=y
# CONFIG_USER_BUSYBOX_DATE_ISOFMT is not set
# CONFIG_USER_BUSYBOX_DC is not set
# CONFIG_USER_BUSYBOX_DD is not set
# CONFIG_USER_BUSYBOX_DEALLOCVT is not set
# CONFIG_USER_BUSYBOX_DELGROUP is not set
# CONFIG_USER_BUSYBOX_DELUSER is not set
# CONFIG_USER_BUSYBOX_DEVFSD is not set
# CONFIG_USER_BUSYBOX_DF is not set
# CONFIG_USER_BUSYBOX_DIRNAME is not set
# CONFIG_USER_BUSYBOX_DMESG is not set
# CONFIG_USER_BUSYBOX_DOS2UNIX is not set
# CONFIG_USER_BUSYBOX_DPKG is not set
# CONFIG_USER_BUSYBOX_DPKG_DEB is not set
# CONFIG_USER_BUSYBOX_DUTMP is not set
# CONFIG_USER_BUSYBOX_DU is not set
# CONFIG_USER_BUSYBOX_DUMPKMAP is not set
# CONFIG_USER_BUSYBOX_ECHO is not set
# CONFIG_USER_BUSYBOX_ENV is not set
# CONFIG_USER_BUSYBOX_EXPR is not set
# CONFIG_USER_BUSYBOX_FBSET is not set
# CONFIG_USER_BUSYBOX_FDFLUSH is not set
# CONFIG_USER_BUSYBOX_FDFORMAT is not set
# CONFIG_USER_BUSYBOX_FDISK is not set
# CONFIG_USER_BUSYBOX_FIND is not set
# CONFIG_USER_BUSYBOX_FOLD is not set
# CONFIG_USER_BUSYBOX_FREE is not set
# CONFIG_USER_BUSYBOX_FREERAMDISK is not set
# CONFIG_USER_BUSYBOX_FSCK_MINIX is not set
# CONFIG_USER_BUSYBOX_FTPGET is not set
# CONFIG_USER_BUSYBOX_FTPPUT is not set
# CONFIG_USER_BUSYBOX_GETOPT is not set
# CONFIG_USER_BUSYBOX_GETTY is not set
# CONFIG_USER_BUSYBOX_GREP is not set
# CONFIG_USER_BUSYBOX_GUNZIP is not set
# CONFIG_USER_BUSYBOX_GZIP is not set
# CONFIG_USER_BUSYBOX_HALT is not set
# CONFIG_USER_BUSYBOX_HDPARM is not set
# CONFIG_USER_BUSYBOX_HEAD is not set
# CONFIG_USER_BUSYBOX_HEXDUMP is not set
# CONFIG_USER_BUSYBOX_HOSTID is not set
# CONFIG_USER_BUSYBOX_HOSTNAME is not set
# CONFIG_USER_BUSYBOX_HTTPD is not set
# CONFIG_USER_BUSYBOX_HWCLOCK is not set
# CONFIG_USER_BUSYBOX_ID is not set
# CONFIG_USER_BUSYBOX_IFCONFIG is not set
# CONFIG_USER_BUSYBOX_IFUPDOWN is not set
# CONFIG_USER_BUSYBOX_INETD is not set
# CONFIG_USER_BUSYBOX_INIT is not set
CONFIG_USER_BUSYBOX_INSMOD=y
CONFIG_USER_BUSYBOX_LSMOD=y
CONFIG_USER_BUSYBOX_MODPROBE=y
CONFIG_USER_BUSYBOX_RMMOD=y
# CONFIG_USER_BUSYBOX_2_2_MODULES is not set
CONFIG_USER_BUSYBOX_2_4_MODULES=y
# CONFIG_USER_BUSYBOX_2_6_MODULES is not set
# CONFIG_USER_BUSYBOX_INSMOD_VERSION_CHECKING is not set
# CONFIG_USER_BUSYBOX_CHECK_TAINTED_MODULE is not set
# CONFIG_USER_BUSYBOX_INSMOD_LOADINKMEM is not set
# CONFIG_USER_BUSYBOX_INSMOD_KSYMOOPS_SYMBOLS is not set
# CONFIG_USER_BUSYBOX_INSMOD_LOAD_MAP is not set
# CONFIG_USER_BUSYBOX_IPADDR is not set
# CONFIG_USER_BUSYBOX_IPCALC is not set
# CONFIG_USER_BUSYBOX_IPLINK is not set
# CONFIG_USER_BUSYBOX_IPROUTE is not set
# CONFIG_USER_BUSYBOX_IPTUNNEL is not set
# CONFIG_USER_BUSYBOX_KILL is not set
# CONFIG_USER_BUSYBOX_KILLALL is not set
CONFIG_USER_BUSYBOX_KLOGD=y
# CONFIG_USER_BUSYBOX_LENGTH is not set
# CONFIG_USER_BUSYBOX_LAST is not set
# CONFIG_USER_BUSYBOX_LN is not set
# CONFIG_USER_BUSYBOX_LOADACM is not set
# CONFIG_USER_BUSYBOX_LOADFONT is not set
# CONFIG_USER_BUSYBOX_LOADKMAP is not set
# CONFIG_USER_BUSYBOX_LOGGER is not set
# CONFIG_USER_BUSYBOX_LOGIN is not set
# CONFIG_USER_BUSYBOX_LOGNAME is not set
# CONFIG_USER_BUSYBOX_LOGREAD is not set
# CONFIG_USER_BUSYBOX_LOSETUP is not set
# CONFIG_USER_BUSYBOX_LS is not set
# CONFIG_USER_BUSYBOX_MAKEDEVS is not set
# CONFIG_USER_BUSYBOX_MD5SUM is not set
# CONFIG_USER_BUSYBOX_MESG is not set
# CONFIG_USER_BUSYBOX_MKDIR is not set
# CONFIG_USER_BUSYBOX_MKFIFO is not set
# CONFIG_USER_BUSYBOX_MKFS_MINIX is not set
# CONFIG_USER_BUSYBOX_MKNOD is not set
# CONFIG_USER_BUSYBOX_MKSWAP is not set
# CONFIG_USER_BUSYBOX_MKTEMP is not set
# CONFIG_USER_BUSYBOX_MORE is not set
# CONFIG_USER_BUSYBOX_MOUNT is not set
# CONFIG_USER_BUSYBOX_MT is not set
# CONFIG_USER_BUSYBOX_MV is not set
# CONFIG_USER_BUSYBOX_NAMEIF is not set
# CONFIG_USER_BUSYBOX_NC is not set
# CONFIG_USER_BUSYBOX_NETSTAT is not set
# CONFIG_USER_BUSYBOX_NSLOOKUP is not set
# CONFIG_USER_BUSYBOX_OD is not set
# CONFIG_USER_BUSYBOX_OPENVT is not set
# CONFIG_USER_BUSYBOX_PASSWD is not set
# CONFIG_USER_BUSYBOX_PATCH is not set
# CONFIG_USER_BUSYBOX_PIDOF is not set
# CONFIG_USER_BUSYBOX_PING is not set
# CONFIG_USER_BUSYBOX_PING6 is not set
# CONFIG_USER_BUSYBOX_PIPE_PROGRESS is not set
# CONFIG_USER_BUSYBOX_PIVOT_ROOT is not set
# CONFIG_USER_BUSYBOX_POWEROFF is not set
# CONFIG_USER_BUSYBOX_PRINTF is not set
CONFIG_USER_BUSYBOX_PS=y
# CONFIG_USER_BUSYBOX_PWD is not set
# CONFIG_USER_BUSYBOX_RDATE is not set
# CONFIG_USER_BUSYBOX_REALPATH is not set
# CONFIG_USER_BUSYBOX_READLINK is not set
# CONFIG_USER_BUSYBOX_REBOOT is not set
# CONFIG_USER_BUSYBOX_RENICE is not set
# CONFIG_USER_BUSYBOX_RESET is not set
# CONFIG_USER_BUSYBOX_RM is not set
# CONFIG_USER_BUSYBOX_RMDIR is not set
# CONFIG_USER_BUSYBOX_ROUTE is not set
# CONFIG_USER_BUSYBOX_RPM2CPIO is not set
# CONFIG_USER_BUSYBOX_RUN_PARTS is not set
# CONFIG_USER_BUSYBOX_RX is not set
# CONFIG_USER_BUSYBOX_SED is not set
# CONFIG_USER_BUSYBOX_SEQ is not set
# CONFIG_USER_BUSYBOX_SETKEYCODES is not set
# CONFIG_USER_BUSYBOX_SHELL is not set
# CONFIG_USER_BUSYBOX_SHA1SUM is not set
# CONFIG_USER_BUSYBOX_SLEEP is not set
# CONFIG_USER_BUSYBOX_SORT is not set
# CONFIG_USER_BUSYBOX_START_STOP_DAEMON is not set
# CONFIG_USER_BUSYBOX_STRINGS is not set
# CONFIG_USER_BUSYBOX_STTY is not set
# CONFIG_USER_BUSYBOX_SU is not set
# CONFIG_USER_BUSYBOX_SULOGIN is not set
# CONFIG_USER_BUSYBOX_SWAPONOFF is not set
# CONFIG_USER_BUSYBOX_SYNC is not set
# CONFIG_USER_BUSYBOX_SYSCTL is not set
CONFIG_USER_BUSYBOX_SYSLOGD=y
CONFIG_USER_BUSYBOX_ROTATE_LOGFILE=y
CONFIG_USER_BUSYBOX_REMOTE_LOG=y
# CONFIG_USER_BUSYBOX_IPC_SYSLOG is not set
# CONFIG_USER_BUSYBOX_TAIL is not set
# CONFIG_USER_BUSYBOX_TAR is not set
# CONFIG_USER_BUSYBOX_TEE is not set
CONFIG_USER_BUSYBOX_TELNET=y
# CONFIG_USER_BUSYBOX_TELNET_TTYPE is not set
# CONFIG_USER_BUSYBOX_TELNET_AUTOLOGIN is not set
# CONFIG_USER_BUSYBOX_TELNETD is not set
# CONFIG_USER_BUSYBOX_TEST is not set
# CONFIG_USER_BUSYBOX_TFTP is not set
# CONFIG_USER_BUSYBOX_TIME is not set
# CONFIG_USER_BUSYBOX_TOP is not set
# CONFIG_USER_BUSYBOX_TOUCH is not set
# CONFIG_USER_BUSYBOX_TR is not set
# CONFIG_USER_BUSYBOX_TRACEROUTE is not set
# CONFIG_USER_BUSYBOX_TRUE_FALSE is not set
# CONFIG_USER_BUSYBOX_TTY is not set
# CONFIG_USER_BUSYBOX_UDHCPC is not set
# CONFIG_USER_BUSYBOX_UDHCPD is not set
# CONFIG_USER_BUSYBOX_UMOUNT is not set
# CONFIG_USER_BUSYBOX_UNAME is not set
# CONFIG_USER_BUSYBOX_UNCOMPRESS is not set
# CONFIG_USER_BUSYBOX_UNIQ is not set
# CONFIG_USER_BUSYBOX_UNIX2DOS is not set
# CONFIG_USER_BUSYBOX_UPDATE is not set
# CONFIG_USER_BUSYBOX_UPTIME is not set
# CONFIG_USER_BUSYBOX_USLEEP is not set
# CONFIG_USER_BUSYBOX_UUDECODE is not set
# CONFIG_USER_BUSYBOX_UUENCODE is not set
# CONFIG_USER_BUSYBOX_UNZIP is not set
# CONFIG_USER_BUSYBOX_VCONFIG is not set
# CONFIG_USER_BUSYBOX_VI is not set
CONFIG_USER_BUSYBOX_WATCHDOG=y
# CONFIG_USER_BUSYBOX_WC is not set
# CONFIG_USER_BUSYBOX_WGET is not set
# CONFIG_USER_BUSYBOX_WHICH is not set
# CONFIG_USER_BUSYBOX_WHOAMI is not set
# CONFIG_USER_BUSYBOX_XARGS is not set
# CONFIG_USER_BUSYBOX_YES is not set
# CONFIG_USER_BUSYBOX_ZIP is not set

#
# other features
#
# CONFIG_USER_BUSYBOX_BUFFERS_GO_ON_STACK is not set
# CONFIG_USER_BUSYBOX_BUFFERS_GO_IN_BSS is not set
# CONFIG_USER_BUSYBOX_USE_DEVPS_PATCH is not set
# CONFIG_USER_BUSYBOX_VERBOSE_USAGE is not set
# CONFIG_USER_BUSYBOX_AUTOWIDTH is not set
# CONFIG_USER_BUSYBOX_EXTRA_QUIET is not set
# CONFIG_USER_BUSYBOX_MINIX2 is not set
# CONFIG_USER_BUSYBOX_USE_BB_PWD_GRP is not set
# CONFIG_USER_BUSYBOX_DMALLOC is not set
# CONFIG_USER_BUSYBOX_EFENCE is not set
# CONFIG_USER_BUSYBOX_BUFFERS_USE_MALLOC is not set
# CONFIG_USER_BUSYBOX_DEVFS is not set
# CONFIG_USER_BUSYBOX_DEVPTS is not set
# CONFIG_USER_BUSYBOX_SUID is not set
# CONFIG_USER_BUSYBOX_LFS is not set
# CONFIG_USER_BUSYBOX_SELINUX is not set
# CONFIG_USER_BUSYBOX_STATIC is not set
# CONFIG_USER_BUSYBOX_IPV6 is not set
# CONFIG_USER_BUSYBOX_CLEAN_UP is not set
# CONFIG_USER_BUSYBOX_HUMAN_READABLE is not set
# CONFIG_USER_BUSYBOX_LOCALE_SUPPORT is not set

#
# Tinylogin
#
# CONFIG_USER_TINYLOGIN_TINYLOGIN is not set

#
# MicroWindows
#
# CONFIG_USER_MICROWIN is not set

#
# Games
#
# CONFIG_USER_GAMES_ADVENT4 is not set
# CONFIG_USER_GAMES_DUNGEON is not set
# CONFIG_USER_GAMES_RUBIK is not set

#
# Miscellaneous Configuration
#
# CONFIG_USER_RAMIMAGE_NONE is not set
# CONFIG_USER_RAMIMAGE_RAMFS64 is not set
CONFIG_USER_RAMIMAGE_RAMFS128=y
# CONFIG_USER_RAMIMAGE_RAMFS256 is not set
# CONFIG_USER_RAMIMAGE_RAMFS512 is not set
# CONFIG_USER_RAMIMAGE_RAMFS1024 is not set
# CONFIG_USER_RAMIMAGE_RAMFS2048 is not set
# CONFIG_USER_RAMIMAGE_RAMFS8192 is not set
# CONFIG_USER_CGI_GENERIC is not set
# CONFIG_USER_CGIHTML is not set
# CONFIG_USER_DEMO_BUTTON is not set
# CONFIG_USER_DEMO_LATCH is not set
# CONFIG_USER_DEMO_MORSE is not set
# CONFIG_USER_DEMO_R2100 is not set

#
# Debug Builds
#
# CONFIG_LIB_DEBUG is not set
# CONFIG_USER_DEBUG is not set

#
# Debug tools
#
# CONFIG_USER_TIMEPEG_TPT is not set

#
# Debug libraries
#
# CONFIG_LIB_LIBCCMALLOC is not set
