#!/usr/bin/expect

# Main entrance
source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp 

step "Start testing."

set case_num 0
set sram_alloc 0

set timeout 20
send "sram_alloc\r"
while 1 {
   expect {

      -re "FAIL" {
         send_log "\nTest for sram allocation fail\n"
         case_fail $case_num
         exit
      }

      -re "PASS" {
         case_pass $case_num
         set sram_alloc 1
      }

      timeout {
      break
         
      }
   }
}
if { $sram_alloc == 1 } { 
all_pass
}
send_user "Ending $argv0\n"

log_file
