include ../../nessus.tmpl

PLUGNAME=nmap_tcp_connect

all : $(PLUGNAME).nes
$(PLUGNAME).nes : $(PLUGNAME).c
	$(CC) -bundle -undefined error $(DEFS) $(include) -c  $(PLUGNAME).c
	$(CC) -bundle -undefined error -o $(PLUGNAME).nes $(PLUGNAME).o $(LIBS)
	cp $(PLUGNAME).nes $(rootdir)/bin/
clean :
	@rm -fr *.lo *.nes *.la .libs
	@rm -fr *.o

