#!/usr/bin/expect

#
#Test program to test the KGDB patch.
#
source ../kernel_config.exp
source ../board_info.exp

set debug_port "ethernet"

if { $argc >= 2} {
set debug_port [lindex $argv 1]
}

log_file [log_file_name $argv0.$debug_port ]

send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

if { $debug_port == "uart" || $debug_port == "ethernet" } {
send_log "\n#### Debugging is through $debug_port port.\n"
} else {
send_log "\n#### This port $debug_port is not supported. Sorry.\n"
exit
}

step "Start $TITLE\r"

set timeout 10

proc clean_host_gdb { } {

global gdb_id
global sh_prompt

spawn /bin/sh
expect -re  $sh_prompt

set timeout 10
send -s "ps aux | grep bfin-uclinux-gdb\r"
while 1 {
   expect {
     -re  $sh_prompt {
         break
      }

     timeout {
            break
         }
     }
}

send -s "kill -9 `pidof  bfin-uclinux-gdb`\r"
while 1 {
   expect {
     -re  $sh_prompt {
         break
      }

     timeout {
            break
         }
     }
}
}

set case_num 0

set flag 0
send "ifconfig eth0 $targetip\r"
while 1 {
   sleep 3
   expect {
      ">" {
         set flag 1
         puts "ifconfig set success.\n"
         break
      }

      timeout {
            puts "Fail ifconfig. "
            break
         }
     }
}

if { $debug_port == "uart" } {
send -s "\x81"
send -s "b"
send -s "g"
sleep 3
while 1 {
        expect {
               -re "SysRq : GDB.*Entering KGDB" {
                send_log "Prepare KGDB through uart port debug!"
                break
            }

            timeout {
                send_user "ERROR: enter to kgdb error\n"
                break
            }
        }
}
}

incr case_num
spawn bfin-uclinux-gdb $uclinux_path/linux-2.6.x/vmlinux
set gdb_id $spawn_id
while 1 {
      expect {
	"(gdb)" {
                case_pass $case_num
	 	break;
         }
         timeout {
                case_fail $case_num
		exit
         }
      }
}

while 1 {
	incr case_num
        if { $debug_port == "ethernet" } {
	send "target remote udp:$targetip:6443\r"
	expect {
		"Remote debugging using udp*kgdb_breakpoint" {
                 case_pass $case_num
			expect { 
				"(gdb) " {
				}
			}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        } elseif { $debug_port == "uart" } {
        send "set remotebaud 57600\r"
        expect {
                "(gdb)" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                exit
                }
        }
        send "target remote $ttyUSBdev\r"
        expect {
                "Remote debugging using $ttyUSBdev*kgdb_breakpoint" {
                 case_pass $case_num
                        expect {
                                "(gdb) " {
                                }
                        }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        }
	incr case_num
	send "break kgdb_test\r"
	expect {
		"Breakpoint 1" {
                case_pass $case_num
			expect { 
				"(gdb) " {
				}
			}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Continuing." {
                case_pass $case_num
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	set spawn_id $kermit_spawn_id
	send "\r"
	expect {
		"> " {
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
###########################################################################
# First round of cat /proc/kgdbtest which is for normal DRAM.

	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 1" {
                case_pass $case_num
		expect { 
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        incr case_num
        send "hbreak 80\r"
        expect {
                "Hardware assisted breakpoint 2*(gdb) " {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        incr case_num
        send "info b\r"
        expect {
               "1   breakpoint*2   hw breakpoint" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

	incr case_num
	send "list\r"
	expect {
		"(gdb) " {
                case_pass $case_num
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "bt\r"
	expect {
		"kgdb_test" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Continuing." {
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	set spawn_id $kermit_spawn_id
    #    set timeout 5
	expect {
		"hello world!" {
		expect {
		"> " {
                clean_host_gdb
                case_fail $case_num
                        exit
		}
               timeout {
                case_pass $case_num
                }
		}
		}
	}
        incr case_num
        set spawn_id $gdb_id
        expect {
                "Breakpoint 2" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        incr case_num
        send "print z\r"
        expect {
               -re "\\\$1 = " {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        send "c\r"
        expect {
                "Continuing." {
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        set spawn_id $kermit_spawn_id
        expect {
              -re  "L1.*code function addr = 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xff80\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
######################################################################################
#Second round of running cat /proc/kgdbtest which is running in L1.

	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 1" {
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "hbreak kgdb_l1_test\r"
	expect {
	  -re	"\[Bb]reakpoint 3 at 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
		expect {
                case_pass $case_num
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        incr case_num
        send "break 57\r"
        expect {
              -re  "Breakpoint 4 at 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                expect {
                case_pass $case_num
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 2, kgdb_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

        set spawn_id $kermit_spawn_id
        expect {
                "hello world!" {
                expect {
                "> " {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
               timeout {
                case_pass $case_num
                }
                }
                }
        }
        set spawn_id $gdb_id
        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 3, kgdb_l1_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        incr case_num
        send "print num1\r"
        expect {
              -re  "\\\$2 = 10" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 4, kgdb_l1_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
       
        incr case_num
        send "print num1\r"
        expect {
              -re  "\\\$3 = 20" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
	set spawn_id $kermit_spawn_id
	expect {
              -re  "L1.*code function addr = 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xff80\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                expect {
                "> " {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
               timeout {
                case_pass $case_num
                }
                }
                }
        }

       set spawn_id $gdb_id
       incr case_num
        send " x/1xw 0xff808010\r"
        expect {
                "Cannot access memory at address" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        send "set *0xff808020 = 23\r"
        expect {
                "Cannot access memory at address" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
	incr case_num
	send "d 1\r"
	send "d 2\r"
	send "info break\r"
	expect {
		"1   breakpoint" {
                case_fail $case_num
			exit
		}
		"2   hw breakpoint" {
                case_fail $case_num
			exit
		}
		"3  *breakpoint*4  *breakpoint" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "step\r"
	expect {
		"test_proc_output" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        incr case_num
        send "step\r"
        expect {
                "test_read_proc" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

	incr case_num
	send "print len\r"
	expect {
	      -re  "\\\$4 =" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	send "c\r"
	expect {
		"Continuing." {
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
       set spawn_id $kermit_spawn_id
        expect {
              ">" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

###########################################################################################

for { set j 0 } { $j < 2 } { incr j 1 } {
        send_user "\n######## Kgdb stress test: this is the [expr $j + 3] round.#########\n "
       
        set spawn_id $kermit_spawn_id
	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 3" {
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}

        set spawn_id $kermit_spawn_id
        incr case_num
        expect {
                "hello world!" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        set spawn_id $gdb_id
        incr case_num
        send "c\r"
        expect {
        "Continuing." {
           expect {
              "Breakpoint 4, kgdb_l1_test*(gdb)" {
              }
              timeout {
              set spawn_id $kermit_spawn_id
              expect {
              -re  "L1.*code function addr = 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xff80\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*>" {
              send_user "!!!!!!!! Breakpoint 4 has been skipped. Error!"
              }
              }
              clean_host_gdb
              case_fail $case_num
              exit
              }
           }
        }

        timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
        }
        }

       set spawn_id $kermit_spawn_id
        expect {
              -re  "L1.*code function addr = 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xff80\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                expect {
                "> " {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
               timeout {
                case_pass $case_num
                }
                }
                }
        }

        set spawn_id $gdb_id
        send "c\r"
        expect {
                "Continuing." {
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

}
######################################################################################
#This round of running cat /proc/kgdbtest is for l2.
if { $board_type == "BF548-EZKIT" || $board_type == "BF561-EZKIT" } {

        set spawn_id $kermit_spawn_id
	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 3" {
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        set spawn_id $kermit_spawn_id
        expect {
                "hello world!" {
                expect {
                "> " {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
               timeout {
                case_pass $case_num
                }
                }
                }
        }
        set spawn_id $gdb_id
	incr case_num
	send "break kgdb_l2_test\r"
	expect {
	  -re	"Breakpoint 5 at 0xfeb0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
		expect {
                case_pass $case_num
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        incr case_num
        send "hbreak 71\r"
        expect {
              -re  "Hardware assisted breakpoint 6 at 0xfeb0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                expect {
                case_pass $case_num
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        incr case_num
        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 4, kgdb_l1_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        set spawn_id $kermit_spawn_id
        incr case_num
        expect {
              -re  "L1.*code function addr = 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xff80\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        set spawn_id $gdb_id
        incr case_num
        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 5, kgdb_l2_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        incr case_num
        send "print num2\r"
        expect {
              -re  "\\\$5 = 80" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 6, kgdb_l2_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

        incr case_num
        send "print num2\r"
        expect {
              -re  "\\\$6 = 100" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
	set spawn_id $kermit_spawn_id
	expect {
              -re  "L2.*code function addr = 0xfeb0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xfeb0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                expect {
                "> " {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
               timeout {
                case_pass $case_num
                }
                }
                }
        }

 	set spawn_id $gdb_id
        incr case_num
        send " x/1xw 0xfeb08010\r"
        expect {
                "Cannot access memory at address" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        send "set *0xfeb08020 = 23\r"
        expect {
                "Cannot access memory at address" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
	incr case_num
	send "d 5\r"
	send "d 6\r"
	send "info break\r"
	expect {
		"5   breakpoint" {
                case_fail $case_num
			exit
		}
		"6   hw breakpoint" {
                case_fail $case_num
			exit
		}
		"3  *breakpoint*4  *breakpoint" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "step\r"
	expect {
		"test_proc_output" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        incr case_num
        send "step\r"
        expect {
                "test_read_proc" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

	incr case_num
	send "print len\r"
	expect {
	      -re  "\\\$7 =" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 6, kgdb_l2_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }

        set spawn_id $kermit_spawn_id
        incr case_num
        expect {
                ">" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
}
###########################################################################################
# The last round.
        set spawn_id $kermit_spawn_id
	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 3" {
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}

        set spawn_id $kermit_spawn_id
        incr case_num
        expect {
                "hello world!" {
                case_pass $case_num
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        set spawn_id $gdb_id
        incr case_num
        send "c\r"
        expect {
                "Continuing." {
                 expect {
                        "Breakpoint 4, kgdb_l1_test*(gdb)" {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
        set spawn_id $kermit_spawn_id
        expect {
              -re  "L1.*code function addr = 0xffa0\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f].*data variable addr = 0xff80\[0-9a-f]\[0-9a-f]\[0-9a-f]\[0-9a-f]" {
                expect {
                "> " {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
               timeout {
                case_pass $case_num
                }
                }
                }
        }
        set spawn_id $gdb_id
        send "info break\r"
        expect {
                "1   breakpoint" {
                case_fail $case_num
                        exit
                }
                "2   hw breakpoint" {
                case_fail $case_num
                        exit
                }
                "3  *breakpoint*4  *breakpoint" {
                case_pass $case_num
                expect {
                        "(gdb) " {
                        }
                }
                }
                timeout {
                clean_host_gdb
                case_fail $case_num
                        exit
                }
        }
	incr case_num
	send "d\r"
	expect {
		"Delete all breakpoints? (y or n)" {
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	send "y\r"
	expect {
		"(gdb) " {
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	send "info break\r"
	expect {
		"No breakpoints or watchpoints." {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Continuing." {
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	set spawn_id $kermit_spawn_id
	expect {
		"> " {
		}
	}
	incr case_num
	set spawn_id $gdb_id
        sleep 3
	send "\3"
	expect {
		"breakpoint" {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	incr case_num
	send "detach\r"
	expect {
		"Ending remote debugging." {
                case_pass $case_num
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	send "q\r"
	set spawn_id $kermit_spawn_id
	incr case_num
	send "\r"
	expect {
		"> " {
                case_pass $case_num
			break
		}
		timeout {
                clean_host_gdb
                case_fail $case_num
			exit
		}
	}
	
}
   
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file

