#!/usr/bin/expect
#
#Test program to test the KGDB patch.
#
#Steps:
#1.  Set up the tftp server on host. Set the root folder, such as "/tftpboot".
#2.  Set up the uboot environment variables. such as serverip, ipaddress, filename, bootaddr, etc.
#3.  Apply the KGDB patch in folder kgdb_patch.
#3.1 "cd linux-2.6.x"
#3.2 "patch -p1 < ../kgdb_patch/kgdb_bfin_linux-2.6.x.patch"
#4.  Build the uclinux with KGDB enabled over ethernet.
#3.1 "make menuconfig"
#3.2 Select option "Customize Kernel Settings"
#3.3 In menu "Kernel hacking", select options "Kernel debugging", "KGDB: kernel debugging with remote gdb"
#    "KGDB: On ethernet", "KGDB: test".
#3.4 In menu "Kernel hacking -> Kernel Boot Parameter", add "kgdboe=@targetip/,@serverip/"
#3.5 "make"
#3.6 "cp linux-2.6.x/linux /tftpboot/uImage
#4.  Hit the reset button on target board and start the test script.
#4.1 "cd testsuites/kgdb/"
#4.2 "./test_kgdb /dev/ttyS0 source_code_dir"
#

set send_slow {1 .01}

set SERIAL_PORT_BAUD_RATE   "57600"
set TITLE "KGDB Test"
set targetip 10.100.4.2
set serverip 10.100.4.174

set argc [llength $argv]
if { $argc < 2} {
   puts "Usage:  $argv0 tty-device srcdir \[targetip serverip\]"
   puts "   where tty-device is something like /dev/ttyS0"
   puts ""
   exit
}
# grab the user specified parameters.
set ttydev             [lindex $argv 0]
set srcdir             [lindex $argv 1]

if { $argc >= 3} {
   set targetip           [lindex $argv 2]
}
if { $argc >= 4} {
   set serverip           [lindex $argv 3]
}

# Now set up the kermit parameters.
#  I want these all contained in this file to make it easier for users.
#  This just builds up a list of commands which are sent to kermit.
#
set kparams     [list "set line $ttydev\r"]
lappend kparams "set speed $SERIAL_PORT_BAUD_RATE\r"
lappend kparams "set carrier-watch off\r"
lappend kparams "set handshake none\r"
lappend kparams "set flow-control none\r"
lappend kparams "robust\r"
lappend kparams "set file type bin\r"
lappend kparams "set file name lit\r"
lappend kparams "set rec pack 1000\r"
lappend kparams "set send pack 1000\r"
lappend kparams "set window 5\r"
set nkparams [llength $kparams]

set timeout 3
spawn kermit
# We need to save the id because resetting the board will overwrite it.
set kermit_spawn_id $spawn_id

while 1 {
	expect {
	        "Type ?" { }
		"ermit>" { break }
		"not found" {
                   tee "ERROR: Failed to start up kermit"
                   exit
		}
		timeout {
                   tee "ERROR: Time out starting up kermit"
                   exit
		}
	}
}

for {set i 0} {$i < $nkparams} {incr i} {
    send -s [lindex $kparams $i]

    while 1 {
	  expect {
		 "ermit>" { break }

		 "\\?\[A-Z]" {
                    tee "ERROR: Failed to set up kermit parameters"
                    exit
		 }

		 timeout {
                    tee "ERROR: Time out setting up kermit parameters"
                    exit
		 }
	  }
    }
}

send -s "connect\r"
while 1 {
	expect {
		"ype the escape character*" {
		     break  }
		timeout {
		     puts "\nERROR: Can't connect to serial port\n"
		     exit }
	}
}
#
#  Ok, Kermit is running and connected to the board.
#

set timeout 1
set flag 0
for {set i 0} {$i<4} {incr i} {
   send -s "\r"
   expect {
      ">" {
         set flag 1
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

set timeout 2
set flag 0
send -s "tftpboot\r"
while 1 {
   expect {
      "TFTP" {
         set flag 1
         set timeout 30
      }
      ">" {
         break
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

set timeout 1
set flag 0
send -s "bootelf\r"
while 1 {
   expect {
      "Loading .text" {
         set flag 1
         set timeout 30
      }
      "> " {
         break
      }
   }
}
if {$flag==0} {
   puts "fail to communicate with uboot.\n"
   exit
}

set timeout 3
send -s "ifconfig eth0 $targetip\r"
expect {
	"> " {
	}

        timeout {
		puts "Fail to config eth0\r"
		exit
        }
}

puts "*********************************\r"
puts "Start $TITLE\r"
puts "*********************************\r"

set timeout 10
set case_num 0

incr case_num
spawn bfin-elf-gdb $srcdir/linux-2.6.x/vmlinux
set gdb_id $spawn_id
while 1 {
      expect {
	"(gdb)" {
		puts "\rCase $case_num ...PASS\r"
	 	break;
         }
         timeout {
		puts "\rCase $case_num ...FAIL\r"
		puts "$TITLE ............\[FAIL\]\r"
		exit
         }
      }
}

while 1 {
	incr case_num
	send "target remote udp:$targetip:6443\r"
	expect {
		"breakpoint () at kernel" {
			puts "\rCase $case_num ...PASS\r"
			expect { 
				"(gdb) " {
				}
			}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "break kgdb_test\r"
	expect {
		"Breakpoint 1" {
			puts "\rCase $case_num ...PASS\r"
			expect { 
				"(gdb) " {
				}
			}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Continuing." {
			puts "\rCase $case_num ...PASS\r"
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	set spawn_id $kermit_spawn_id
	send "\r"
	expect {
		"> " {
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 1" {
			puts "\rCase $case_num ...PASS\r"
		expect { 
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "list\r"
	expect {
		"(gdb) " {
			puts "\rCase $case_num ...PASS\r"
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Continuing." {
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	set spawn_id $kermit_spawn_id
	expect {
		"hello world!" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"> " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 1" {
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "break 22\r"
	expect {
		"Breakpoint 2" {
		expect {
			puts "\rCase $case_num ...PASS\r"
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "bt\r"
	expect {
		"kgdb_test" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Breakpoint 2" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "d 1\r"
	send "info break\r"
	expect {
		"1   breakpoint" {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
		"2   breakpoint" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "step\r"
	expect {
		"test_read_proc" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "print len\r"
	expect {
		"1 = 16" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send "c\r"
	expect {
		"Continuing." {
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	set spawn_id $kermit_spawn_id
	expect {
		"hello world!" {
		expect {
			"> " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send -s "cat /proc/kgdbtest\r"
	set spawn_id $gdb_id
	expect {
		"Breakpoint 2" {
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "d\r"
	expect {
		"Delete all breakpoints? (y or n)" {
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send "y\r"
	expect {
		"(gdb) " {
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send "info break\r"
	expect {
		"No breakpoints or watchpoints." {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "c\r"
	expect {
		"Continuing." {
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	set spawn_id $kermit_spawn_id
	expect {
		"hello world!" {
			puts "\rCase $case_num ...PASS\r"
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	expect {
		"> " {
		}
	}
	incr case_num
	set spawn_id $gdb_id
	send "\3"
	expect {
		"breakpoint" {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	incr case_num
	send "detach\r"
	expect {
		"Ending remote debugging." {
			puts "\rCase $case_num ...PASS\r"
		expect {
			"(gdb) " {
			}
		}
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	send "q\r"
	set spawn_id $kermit_spawn_id
	incr case_num
	send "\r"
	expect {
		"> " {
			puts "\rCase $case_num ...PASS\r"
			break
		}
		timeout {
			puts "\rCase $case_num ...FAIL\r"
			puts "$TITLE ............\[FAIL\]\r"
			exit
		}
	}
	
}
   

puts "                                                                        \r"
puts "\r$TITLE ............\[PASS\]\r"
