#!/usr/bin/expect

# Main entrance
source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 5

step "Start Sigqueue testing"

set case_num 0
set timeout 2

incr case_num
step "Clean src directory\n"
spawn make clean
while 1 {
   expect {

      "*error*" {
         send_log "\nMake clean failed\n"
         send_user "\nMake clean failed\n"
         case_fail $case_num
      }

      eof {
         send_log "\nMake clean.\n"
         send_user "\nMake clean.\n"
         break
      }

      timeout {
         break
      }
   }
}

step "Build test program\n"
spawn make
while 1 {
   expect {

      "*error*" {
         send_log "\nBuild test program failed\n"
         send_user "\nBuild test program failed\n"
         case_fail $case_num
      }

      eof {
         send_log "\nBuild test program done\n"
         send_user "\nBuild test program done\n"
         break
      }

      timeout {
         break
      }
   }
}

set spawn_id $kermit_spawn_id

send "ifconfig eth0 $targetip up\r"
sleep 15

set allcases {1-1 2-1 3-1 4-1 5-1 6-1 7-1 8-1 9-1 10-1 11-1 12-1}
set casenum [llength $allcases]
send_user "casenum=$casenum\n"

set timeout 20
step "Copy testcase to target board\n"
for {set i 0} {$i < $casenum} {incr i} {
spawn rcp [lindex $allcases $i] root@$targetip:/.
while 1 {
   expect {

      "*connect*" {
         send_log "\nCopy testcases to target board failed\n"
         send_user "\nCopy testcases to target board failed\n"
         exit
      }

      eof {
         send_log "\nCopy testcases to target board done\n"
         send_user "\nCopy testcases to target board done\n"
         break
      }

      timeout {
         break
      }
   }
}
}

set spawn_id $kermit_spawn_id
set timeout 2
set testres    0

send "echo \"nobody:x:1:1:nobody:/:/bin/sh\" >> /etc/passwd\n"

for {set i 0} {$i < $casenum} {incr i} {
   send "./[lindex $allcases $i]\n"
   sleep 2
   while 1 {
      expect {

         -re "PASSED" {
            send_log "\n############ Case [lindex $allcases $i] pass\n"
            send_user "\n########### Case [lindex $allcases $i] pass\n"
            incr testres
         }

         eof {
            break
         }
         timeout {
            break
         }
      }
   }
}



if { $testres != 12 } {
   case_fail $case_num
} else {
   all_pass
}

send_user "Ending $argv0\n"

log_file
