#!/usr/bin/expect

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

sleep 5

step "Start Sqlite testing"

set timeout 2
send "sqlite3 wishlist.db < /usr/wishlist.sql\r"
expect "root:~>"

send "sqlite3 wishlist.db \".dump\"\r"
expect "root:~>"

send "sqlite_test \"foo\"\r"

while 1 {
   expect {
      -re ".*foo <foo@test>.*" {
         send_log "\n$TITLE ............\[PASS\]\n"
         send_user "\n$TITLE ............\[PASS\]\n"
         break
      }
      timeout {
         send_log "\n$TITLE ............\[FAIL\]\n"
         send_user "\n$TITLE ............\[FAIL\]\n"
         break
      }
   }
}

exit
