#!/bin/sh

# Convert all of the busybox Config.in files to Kconfig
# files suitable for uClinux-dist integration

bdir=${1%/}

if [ -z "${bdir}" ] ; then
	bdir=$(awk '$1 == "VER" { print $NF }' Makefile)
fi

if [ ! -d "${bdir}" ] ; then
	echo "Usage: $0 <busybox dir>" 1>&2
	exit 1
fi

echo "Converting Config.in files in ${bdir} to Kconfig files"

echo "source ../user/busybox/${bdir}/Kconfig" > Kconfig

find "${bdir}" -type f -name Config.in | \
while read input ; do
	output="${input%Config.in}Kconfig"
	echo -n " Converting ${input} -> "

awk -v BDIR="${bdir}" '
BEGIN {
	cfgprefix = "USER_BUSYBOX_"
	print "###\n### DO NOT EDIT THIS FILE; IT IS AUTO-GENERATED\n### SEE config.in-to-kconfig.sh FOR MORE INFO\n###\n"
}

{
if ($1 ~ /^#/) {
	print
	next
}

if ($1 == "help") {
	print
	getline
	while ($0 ~ /^([[:space:]]|$)/) {
		print
		if (getline == 0)
			exit 0
	}
}

if ($1 == "mainmenu") {
	sub(/^mainmenu/, "comment")
	print
	next
} else if ($1 == "config") {
	print "config " cfgprefix $2
	next
} else if ($1 == "source") {
	sub(/Config.in/, "Kconfig")
	print "source ../user/busybox/" BDIR "/" $2
	next
} else if ($1 == "default" || $1 == "depends" || $1 == "select") {
	str = 0
	mod = 0
	out = "\t" $1
	for (i = 2; i <= NF; ++i) {
		if ($i ~ /^"/)
			str = 1
		if (str == 0 && \
		    $i != "y" && \
		    $i != "n" && \
		    $i != "if" && \
		    $i != "on" && \
		    $i != int($i) && \
		    $i != "(" && \
		    $i != ")" && \
		    $i != "||" && \
		    $i != "&&")
		{
			pre = ""
			pre = pre ($i ~ /^!/ ? "!" : "")
			sub(/^!/, "", $i)
			pre = pre ($i ~ /^\(/ ? "(" : "")
			sub(/^\(/, "", $i)
			pre = pre ($i ~ /^!/ ? "!" : "")
			sub(/^!/, "", $i)
			out = out " " pre cfgprefix $i
			mod = 1
		} else
			out = out " " $i
		if ($i ~ /"$/)
			str = 0
	}
	if (mod == 1) {
		print out
		next
	}
}
print
}
' "${input}" > "${output}"

	echo "${output}"
done
