# Here we have uClinux stuff for romfs/.config generation
# We also need to tweak:
#  Makefile: remove .config target
#  Makefile.custom:install: rm -rf $(CONFIG_PREFIX) first

ROOTDIR ?= ../..
.config: $(ROOTDIR)/config/.config
	sed -n -e '/CONFIG_USER_BUSYBOX_/s:CONFIG_USER_BUSYBOX_:CONFIG_:p' $< > $@
	yes "" | $(MAKE) oldconfig

.PHONY: romfs
romfs: install
	mv $(CONFIG_PREFIX)/sbin/* $(CONFIG_PREFIX)/bin/
	rmdir $(CONFIG_PREFIX)/sbin
	cp -pPR $(CONFIG_PREFIX)/* $(ROMFSDIR)/
