#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reset to uboot."
source ../reset_to_uboot.exp


set timeout 500

send -s "tftp 0x1000000 vmImage\r"
while 1 {
expect {
	
	"done" {
	set tftp_flag SUCCESS
	break
	}
	
	timeout {
	send_user "ERROR: Uboot locked up during tftp\n"	
	break
	}
}
}
    
set case_num 0

incr case_num
 
       set timeout 80
       send -s "bootm 0x1000000\r"
     
	while 1 {
  	expect {
             -re $kernel_prompt {
	    send_user "\nEnding boot_kernel_only_uimage.exp \n"  
                case_pass $case_num
	    break
	    }	      
	     
             timeout {
	     send_user "failed tftp_boot attempt\n"
                case_fail $case_num
	     exit
	     }
	   }   
    } 
  
send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"
 
log_file
