#!/usr/bin/expect

#
#Test program to test reboot.
#
source ../kernel_config.exp
source ../board_info.exp

log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reset the uboot."
source ../reset_to_uboot.exp

send_log "*********************************\r"
send_log "Start $TITLE\r"
send_log "*********************************\r"

send -s "reset\r"

for {set case_num 1} {$case_num <= $count} {incr case_num} {

    set timeout 5
    expect {
        "Hit any key" {}
        timeout {}
    }

    sleep 1
    set timeout 2
    while 1 {
        send -s "\r"
        expect {
            ">" {
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    sleep 4
    set timeout 5
    send -s "bootm $kernel_start_addr\r"
    while 1 {
        expect {
            "Linux version" {
                break
            }
        }
    }

    set timeout 30
    while 1 {
        expect {
             -re $kernel_prompt {
                case_pass $case_num
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    send_user "Wait for 1 minutes before reboot.\r"
    sleep 60

    set timeout 5
    send -s "\r\r"
    while 1 {
        expect {
            ">" {
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    send -s "reboot\r"
}

send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 
while 1 {
    expect {
        "Hit any key " {
            send "\r"
            expect ">"
            break
        }
        timeout {
            break
        }
    }
}
