#!/usr/bin/expect

#
#Test program to test reboot.
#
source ../kernel_config.exp
source ../board_info.exp

log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reset the uboot."
source ../reset_to_uboot.exp

send_log "*********************************\r"
send_log "Start $TITLE\r"
send_log "*********************************\r"

send -s "reset\r"

for {set case_num 1} {$case_num <= $count} {incr case_num} {

    set timeout 5
    expect {
        "Hit any key" {}
        timeout {}
    }

    sleep 1
    set timeout 2
    while 1 {
        send -s "\r"
        expect {
            ">" {
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    sleep 4
    set timeout 50
    send -s "bootm $kernel_start_addr\r"
    while 1 {
        expect {
            -re "\"physmap-flash.*\".*(0x\[0-9a-fA-F]+)-0x\[0-9a-fA-F]+\[\x20\t]+:\[\x20\t]+\".*\"\r\n(0x\[0-9a-fA-F]+)-0x\[0-9a-fA-F]+\[\x20\t]+:\[\x20\t]+\".*\"\r\n(0x\[0-9a-fA-F]+)-0x\[0-9a-fA-F]+\[\x20\t]+:\[\x20\t]+\".*\"\r\n" {
                set run_kernel_start_addr $expect_out(2,string)
                set run_rootfs_start_addr $expect_out(3,string)
                if { [format "%08x" [expr $mtd_base_addr + $run_kernel_start_addr]] == $kernel_start_addr && [format "%08x" [expr $mtd_base_addr + $run_rootfs_start_addr]] == $rootfs_start_addr } {
                puts "\nThe two address are equal.\nkernel_start_addr [format "%08x" [expr $mtd_base_addr + $run_kernel_start_addr]], rootfs_start_addr [format "%08x" [expr $mtd_base_addr + $run_rootfs_start_addr]] \n"
                } else {
                puts "\nThe two address are not equal.\n kernel_start_addr [format "%08x" [expr $mtd_base_addr + $run_kernel_start_addr]], rootfs_start_addr [format "%08x" [expr $mtd_base_addr + $run_rootfs_start_addr]] \n"
                case_fail $case_num 
                }
	     }
 
            -re "Trace:.*\r\n" {
             expect -re "$kernel_prompt"
             send_user "\nKernel booting up with dump info\n"
             send_log "\n$TITLE ............\[FAIL\]\n"
             exit
            }
            -re $kernel_prompt {
                case_pass $case_num
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    send_user "Wait for 1 minutes before reboot.\r"
    sleep 60

    set timeout 5
    send -s "\r\r"
    while 1 {
        expect {
            ">" {
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    send -s "reboot\r"
}

send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 
while 1 {
    expect {
        "Hit any key " {
            send "\r"
            expect ">"
            break
        }
        timeout {
            break
        }
    }
}
