#!/usr/bin/expect

#
#Test program to test reboot.
#
source ../kernel_config.exp
source ../board_info.exp

log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reset the uboot."
source ../reset_to_uboot.exp

send_log "*********************************\r"
send_log "Start $TITLE\r"
send_log "*********************************\r"

send -s "reset\r"

for {set case_num 0} {$case_num < $count} {incr case_num} {


set timeout 5
expect {
	"Hit any key" {
	}
	timeout {
	}
}

sleep 1

set timeout 2
while 1 {
   send -s "\r"
   expect {
      ">" {
         break
      }
	timeout {
                case_fail $case_num
		exit
	}
   }
}


set timeout 5
if { $board_type == "BF537-STAMP" || $board_type == "BF533-STAMP" } {
send -s "bootm 0x20020000\r"
} elseif { $board_type == "BF561-EZKIT" } {
send -s "bootm 0x20040000\r"
}
while 1 {
   expect {
      "Linux version" {
         break
      }
   }
}

set timeout 30
while 1 {
   expect {
	"> " {
                case_pass $case_num
		break
	}

         timeout {
                case_fail $case_num
		exit
         }
   }
}

send_log "Wait for 1 minutes before reboot.\r"
sleep 60

set timeout 5
send -s "\r\r"
while 1 {
   expect {
	">" {
		break
	}

         timeout {
                case_fail $case_num
		exit
         }
   }
}

send -s "reboot\r"

}

send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 
while 1 {
       expect {
         "Hit any key " {
             send "\r"
             expect ">"
             break
         }

         timeout {
             break
         }
      }
   }

