/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if alsa support is present */
/* #undef HAVE_ALSA */

/* Define to play audio */
#define HAVE_AUDIO 1

/* Define for audiofile support */
#define HAVE_AUDIOFILE 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `dlopen' function. */
/* #undef HAVE_DLOPEN */

/* Define to 1 if `dontUpSampleImplicitSBR' is member of
   `faacDecConfiguration'. */
#define HAVE_FAACDECCONFIGURATION_DONTUPSAMPLEIMPLICITSBR 1

/* Define to 1 if `downMatrix' is member of `faacDecConfiguration'. */
#define HAVE_FAACDECCONFIGURATION_DOWNMATRIX 1

/* Define to 1 if `samplerate' is member of `faacDecFrameInfo'. */
#define HAVE_FAACDECFRAMEINFO_SAMPLERATE 1

/* Define to use FAAD2 for AAC decoding */
#define HAVE_FAAD 1

/* Define if FAAD2 uses buflen in function calls */
#define HAVE_FAAD_BUFLEN_FUNCS 1

/* Define for FLAC support */
#undef HAVE_FLAC

/* Define for HTTP streaming */
#define HAVE_HTTP_INPUT 1

/* Define to use iconv */
//#define HAVE_ICONV 1

/* Define to use id3tag */
#define HAVE_ID3TAG 1

/* Define to 1 if you have the <id3tag.h> header file. */
#define HAVE_ID3TAG_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if IPv6 support present */
/* #undef HAVE_IPV6 1 */

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
#define HAVE_LANGINFO_CODESET 1

/* Define to 1 if you have the `FLAC' library (-lFLAC). */
#define HAVE_LIBFLAC 1

/* Define if locale.h is present */
#define HAVE_LOCALE 1

/* Define to 1 if you have the <machine/soundcard.h> header file. */
/* #undef HAVE_MACHINE_SOUNDCARD_H */

/* Define to use libmad */
#define HAVE_MAD 1

/* Define to 1 if you have the <mad.h> header file. */
//#define HAVE_MAD_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define for mikmod support */
//#define HAVE_MIKMOD 1

/* Define to 1 if the system has the type `mp4AudioSpecificConfig'. */
#define HAVE_MP4AUDIOSPECIFICCONFIG 1

/* Define for bundled ogg vorbis support using Tremor */
//#define HAVE_MPD_IVORBIS	1 

/* Define for ogg vorbis support */
#define HAVE_OGG 1

/* Define to output audio with OSS */
 #define HAVE_OSS 

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if sys/inttypes.h present */
/* #undef HAVE_SYS_INTTYPES_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
/* #undef HAVE_SYS_SOUNDCARD_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to configure for uClinux */
/* #undef HAVE_UCLINUX */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to configure without debugging */
/* #define NDEBUG  1 */

/* Define to disable OSS mixer support */
/* #undef NO_OSS_MIXER */

/* Name of package */
#define PACKAGE "mpd-uclinux"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "eric@petta-tech.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mpd-uclinux"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mpd-uclinux 0.11.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mpd-uclinux"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.11.5"

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to use mpd flac */
/* #undef USE_MPD_FLAC */

/* Define to use mpd libid3tag */
/* #undef USE_MPD_ID3TAG */

/* Define to use mpd libmad */
/* #undef USE_MPD_MAD */

/* Version number of package */
#define VERSION "0.11.5"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */
