#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

cd $uclinux_path/testsuites/ethernet/

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Start testing."

set case_num 0

incr case_num

set timeout 8
set flag 0
send "ifconfig eth0 $targetip\r" 
while 1 {
   sleep 3
   expect {
      ">" {
         set flag 1
         puts "ifconfig set success.\n"
         break
      }

      timeout {
            puts "Fail ifconfig. "
            break
         }
     }
}

spawn sudo ./netserver_x86
while 1 {
   expect {
      "Password:" {
         break
      }

      timeout {
            puts "Fail . "
            break
         }
     }
}
send "$password\r" 
while 1 {
   expect {
      "Starting netserver" {
         puts "netserver start success.\n"
         break
      }

      timeout {
            puts "Fail . "
            break
         }
     }
}
   set netserver_id $spawn_id
  
set spawn_id $kermit_spawn_id


sleep 3
send "cd /\r"
expect   "root:~>"
send "chmod 777 netperf_script\r"

expect   "root:~>"
send  "./netperf_script\r"
set timeout 4000
while 1 {
   expect {
      "root:~>" {
         break
      }

      timeout {
            puts "Failed ethernet test."
            break
         }
     }
}

send  "cat netperf_tcp_rr\r"
set timeout 10
while 1 {
   expect {
      -re "600.* +(\[0-9]+\.\[0-9]+)" {   
         set TransRate $expect_out(1,string)
	 expect ">"
	 puts " TransRate $expect_out(1,string)"
         break
      }

      timeout {
           break
         }
     }
}

send  "cat netperf_tcp_stream\r"
set timeout 10
while 1 {
   expect {
     -re "600.* +(\[0-9]+\.\[0-9]+)" {   
         set Throughput $expect_out(1,string)
	 expect ">"
	 puts "Throughput $expect_out(1,string)"
         break
      }

      timeout {
           break
         }
     }
}

if { $board_type == "BF537-STAMP" } {

	if { $TransRate > 4000 && $Throughput > 85 } {
	
		send_log "\nCase $case_num ...PASS\n"
	
	} else {
		send_log "\nCase $case_num ...FAIL\n"		
		send_log "$TITLE ............\[FAIL\]\n"
		exit
	}
	
} elseif { $board_type == "BF533-STAMP" } {

	if { $TransRate > 4000 && $Throughput > 55 } {
	
		send_log "\nCase $case_num ...PASS\n"
	
	} else {
		send_log "\nCase $case_num ...FAIL\n"
		send_log "$TITLE ............\[FAIL\]\n"
		exit
		
	}

}

spawn ftp $targetip 
while 1 {
    expect {
                "Name" { }
                timeout { send_user "Failed first return\n"
                        break }
        }
        send -s "root\r"
        expect {
                "Password:" { }
                timeout { send_user "Failed first return\n"
                        break }
        }
        send -s "uClinux\r"
        expect {
                "ftp>" { }
                timeout { send_user "Failed first return\n"
                        break }
        }

        send -s "get netperf_tcp_rr\r"
        expect {
                "ftp>" { }
                timeout { send_user "Failed first return\n"
                        break }
        }
	
	send -s "get netperf_tcp_stream\r"
        expect {
                "ftp>" { }
                timeout { send_user "Failed first return\n"
                        break }
        }
         
	 send -s "bye\r"
	 expect {
                "Goodbye" { break }
                timeout { send_user "Failed first return\n"
                        break }
         }
	 
   }
   
send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file



