#!/usr/bin/expect --

#
# Build Kernel for L1 application test
#
source ../kernel_config.exp
source  ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"

cd $uclinux_path/testsuites

step "Make config."
source  make_default_config.exp

cd $uclinux_path/testsuites

step "Make"

source  make_kernel.exp

cd $uclinux_path/testsuites

step "Copy linux"

source   copy_image.exp
  
send_user "Ending $argv0\n"

log_file
