#!/bin/sh
# XXX: this does not handle the "-o" option or any other crazy stuff

error() {
	echo "qmake-wrapper error: $*" 1>&2
	exit 1
}

for stagedir in \
	"${STAGEDIR:-/some/where/invalid/}" \
	"${0%/*}/../staging" \
	"${0%/*}/../.." \
	""
do
	qmake="${stagedir}/usr/bin/qmake"
	[ -x "${qmake}" ] && break
done

if [ ! -x "${qmake}" ] ; then
	error qmake not found: ${qmake}
fi
STAGEDIR=${stagedir}
specs="${STAGEDIR}/usr/share/qt/mkspecs/qws/"

targ=${0##*/}
if [ "${targ}" = "bfin-linux-uclibc-qmake" ] ; then
	specs=${specs}/linux-bfin-fdpic-g++
elif [ "${targ}" = "bfin-uclinux-qmake" ] ; then
	specs=${specs}/linux-bfin-flat-g++
else
	error unknown target: ${targ}
fi

${qmake} -spec "${specs}" "$@" || exit $?

sed -i \
	-e "s:/usr/bin/moc:${STAGEDIR}/usr/bin/moc:g" \
	-e "s:-I/usr/include:-I${STAGEDIR}/usr/include:g" \
	-e "s:-L/usr/lib:-Wl,-rpath-link,${STAGEDIR}/usr/lib -L${STAGEDIR}/usr/lib:g" \
	Makefile
