#!/usr/bin/expect
#

source ../kernel_config.exp
source ../board_info.exp

log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

set TEST_PASS               "pass"
set TEST_FAIL               "fail"

step "MTD test"

set case_num 0

incr case_num

set timeout 5
set mtd_temp_result $TEST_FAIL
set mtd_result $TEST_FAIL
#send -s "\r"
send -s "cat /proc/mtd \r"
while 1 {
    expect {

	"mtd$spi_rootfs_num" {
		set mtd_temp_result $TEST_PASS
		expect  -re $kernel_prompt
                case_pass $case_num
		break
	}

	timeout {
                case_fail $case_num
		exit
	}
    }
}

incr case_num

step "Mount MTD "	
set mtd_temp_result $TEST_FAIL
set timeout 60
send -s "mount -t jffs2 /dev/mtdblock$spi_rootfs_num /mnt\n"
while 1 {
    expect {    
         -re $kernel_prompt {
                set mtd_temp_result $TEST_PASS
                case_pass $case_num
		break
        }

        "failed" {
                case_fail $case_num
                exit
        }
                                                                                                                                                             
        timeout {
                case_fail $case_num
		exit
        }
    }
}

step "Reading MTD "	
set mtd_temp_result $TEST_FAIL
set timeout 60
send -s "ls /mnt\n"
while 1 {
    expect {    
        "home" {
		break
        }
         
        "test" {
                break
        }
                                                                                                                                                    
        timeout {
		break
        }
    }
}

expect ">"
     
incr case_num

step "Reading MTD "	
set mtd_temp_result $TEST_FAIL
set timeout 60
send -s "umount /mnt\n"
while 1 {
    expect {    
        ">" {
                set mtd_temp_result $TEST_PASS
                case_pass $case_num
		break
        }
                                                                                                                                                             
        timeout {
                case_fail $case_num
		exit
        }
    }
} 
                                                                                                                                                      
if { $mtd_temp_result!=$TEST_PASS } {
	exit
}
sleep 1

incr case_num

step "Erase MTD "
set mtd_temp_result $TEST_FAIL
set timeout 180
send -s "eraseall /dev/mtd$spi_rootfs_num\r"
while 1 {
    expect {
	
	 -re $kernel_prompt {
		set mtd_temp_result $TEST_PASS
                case_pass $case_num
		break
	}

	timeout {
                case_fail $case_num
		exit
	}
    }
}

if  { $mtd_temp_result!=$TEST_PASS } {
	exit
}

step "Make jffs2 image"

send_log " \n1)create file system directory\n"
send -s "mkdir -p rootfs\r"
expect ">"
send_log " \n2)create test file\n"
send -s "echo This is test for mtd driver > rootfs/test\r"
expect  -re $kernel_prompt
send_log " \n3)create JFFS2 image\n"
send -s "mkfs.jffs2 -r rootfs -o mtd.img\r"
expect ">"

incr case_num

step "Writing MTD"
set mtd_temp_result $TEST_FAIL
set timeout 60
send -s "cp mtd.img /dev/mtd$spi_rootfs_num\r"
while 1 {
    expect {
	
	 -re $kernel_prompt {
		set mtd_temp_result $TEST_PASS
                case_pass $case_num
		break
	}

       "error" {
                case_fail $case_num
                exit
        }
	
	timeout {
                case_fail $case_num
		exit
	}
    }
}

if  { $mtd_temp_result!=$TEST_PASS } {
        exit
}

incr case_num

step "Reading MTD "	
set mtd_temp_result $TEST_FAIL
set timeout 60
send -s "mount -t jffs2 /dev/mtdblock$spi_rootfs_num /mnt\n"
while 1 {
    expect {    
         -re $kernel_prompt {
                set mtd_temp_result $TEST_PASS
                case_pass $case_num
		break
        }

       "failed" {
                case_fail $case_num
                exit
        }

        timeout {
                case_fail $case_num
		exit
        }
    }
}
                                                                                                                                                             
if  { $mtd_temp_result!=$TEST_PASS } {
        exit
}

incr case_num

step "Verify "
set timeout 2
send -s "cmp /rootfs/test /mnt/test\r"
while 1 {
    expect {
	"differ" {
                case_fail $case_num
		exit
	}
	timeout {
		set mtd_results $TEST_PASS
                case_pass $case_num
		break
	}
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

exit
log_file
 
send_user "\nEnding snormtd_test.exp\n"
