#
# Makefile
#
# Version:	$Id: Makefile,v 1.2 2003/07/15 12:34:51 aland Exp $
#

include ../../Make.inc
.PHONY: all clean install

all: radpaths.h


radpaths.h:
	@/bin/sh ./build-radpaths-h


distclean:
	rm -f radpaths.h

clean:

install:
