#!/usr/bin/expect

log_file rtc_test_log

send_user "Starting rtc_test.exp\n"

set TITLE "RTC Test"

source  ../kernel_config.exp

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Start testing."

set timeout 5

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {         
         break
      }

      timeout { 
	send_log "$TITLE ............\[FAIL\]\n"
	exit
      }
   }
}

set case_num 0
incr case_num

set timeout 500

send -s  "./rtc_test\r" 
while 1 {
   expect {
      "RTC Tests done" {         
         send_log "\nCase $case_num ...PASS\n"
         break
      }

      timeout {
        send_log "\nCase $case_num ...FAIL\n"
	send_log "$TITLE ............\[FAIL\]\n"
	exit
         }
     }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending rtc_test.exp\n"

log_file

