#
# Makefile for mach-bf533/boards.
#

# Object file lists.

obj-$(CONFIG_BFIN533_STAMP) += stamp.o
obj-$(CONFIG_BFIN533_EZKIT) += ezkit.o
obj-$(CONFIG_GENERIC_BOARD) += generic_board.o
obj-$(CONFIG_CM_BF533)      += cm_bf533.o
