#!/usr/bin/expect

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

step "Start testing."
set case_num 0
incr case_num

sleep 5
send "\r"

send "insmod /twi_smbus_test.ko\r"
while 1 {
   expect {
      "PASS" {
         expect ">"
         case_pass $case_num
         break
      }

      timeout {
         case_fail $case_num
         exit
         }
     }
}
incr case_num
send "twi_test 0x58 0x10\r"
while 1 {
   expect {
      "PASS" {
         case_pass $case_num
         break
      }

      timeout {
         case_fail $case_num
         exit
         }
     }
}


incr case_num
send "rmmod twi_smbus_test\r"
while 1 {
   expect {
     -re ">" {         
         case_pass $case_num
         break
      }

      timeout {
         case_fail $case_num
         exit
         }
     }
}

incr case_num
send "lsmod\r" 
while 1 {
   expect {
     -re ">" {         
         case_pass $case_num
         break
      }

      timeout {
         case_fail $case_num
         exit
         }
     }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n" 

send_user "Ending $argv0\n"

log_file

