#!/usr/bin/expect

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated, 
# for it is the default value.
# set bootargs 	$bootargs_param0   
source ../reboot_kernel.exp 

step "Start testing."

set timeout 5

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {         
         break
      }

      timeout { 
                case_fail $case_num
	exit
      }
   }
}

set case_num 0
incr case_num

set timeout 50

send -s  "./traps_test #\r"
while 1 {
   expect {
     
       -re "(\[0-9]+)\r\n" {
        set case_number $expect_out(1,string)
        break
      }

      timeout {
        case_fail $case_num
        exit
         }
     }
}

set timeout 50
set pass_num 0

send -s  "./traps_test -1\r"
for { set j 0 } { $j < [ expr $case_number + 1 ] } { incr j 1 } { 
while 1 {
   expect {
      -re "$j.*:.*PASS \\(.*\\)" {
         send_log "Pass_num is $j ."
         incr pass_num  
         break
      }

      timeout {
        case_fail $case_num
	break
         }
     }
}
}

if { $pass_num == [expr $case_number + 1] } {
   send_log "\n"
   send_log "\n$TITLE ............\[PASS\]\n"
} else {
   send_log "\n"
   case_fail $case_num
}


send_user "Ending $argv0\n"

log_file

