#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

set vco [lindex $argv 0]
set sclk [lindex $argv 1]
set voltage [lindex $argv 2]

send_log "\n#### vco is $vco\n"
send_log "\n#### sclk is $sclk\n"
send_log "\n#### voltage is $voltage\n"

if { $argc < 3} {
   puts "Please input: vco sclk voltage."
   exit
}

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."

set case_num 0

incr case_num

set timeout 8

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {
         break
      }
      timeout {
         break
      }
   }
}

set timeout 500

expect "root:/bin>"
send -s  "./dpmc_test\r" 
while 1 {
   expect {
      "open success" {
         send_log "dpmc device opens.\n"
         break
      }
      timeout {
         case_fail $case_num
         exit
      }
   }
}

while 1 {
   expect {
      "Please select the VCO" {              
         break
      }
      timeout {
         send_log "dpmc VCO fail. "
         exit
      }
   }
}

send -s  "$vco\r" 
while 1 {
   expect {
      "is set to" {   
         case_pass $case_num
         break
      }
      timeout {
         case_fail $case_num
         exit
      }
   }
}

incr case_num

while 1 {
   expect {
      "Please enter the value of sclk" {              
         break
      }
      timeout {
         send_log "dpmc sclk fail. "
         exit
      }
   }
}

send -s  "$sclk\r" 
while 1 {
   expect {
      "set to" {              
         case_pass $case_num
         break
      }
      timeout {
         case_fail $case_num
         exit
      }
   }
}

incr case_num

while 1 {
   expect {
      "select any of these choices for cclk" { 
         sleep 1   
	 send -s  "1\r"       
         case_pass $case_num
         break
      }
      timeout {
         case_fail $case_num
         exit
      }
   }
}

incr case_num

set timeout 300
while 1 {
   expect {
      "select the voltage" {                   
         break
      }
      timeout {
         send_log "dpmc volt fail. "
         exit
      }
   }
}

send -s  "$voltage\r" 
while 1 {
   expect {
      "set to" {             
         case_pass $case_num
         break
      }
      timeout {
	 case_fail $case_num
         exit
      }
   }
}

all_pass

send_user "Ending $argv0\n"

log_file
