#!/usr/bin/expect
source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]



set board_type [lindex $argv 0]
send_log "\n#### board_type is $board_type\n"

if { $argc < 1} {
puts "Please input: board_type."
exit
}

if { $board_type == "BF533-STAMP" } {
    	set board_num 533
} elseif { $board_type == "BF537-STAMP" } {
	set board_num 537        
}



step "Start kermit."
source ../spawn_kermit.exp

#step "Start up kermit on port $ttydev"
# Now set up the kermit parameters.
#  I want these all contained in this file to make it easier for users.
#  This just builds up a list of commands which are sent to kermit.
#
   }
}

step "Reboot the kernel."
source ../reboot_kernel.exp


step "Start testing."

set case_num 0

incr case_num

set timeout 30

send -s "ifconfig eth0 10.100.4.50\r"
while 1 {
   sleep 3
   expect {
      ">" {
         
         puts "ifconfig set success.\n"
         break
      }

      timeout {
            puts "Fail ifconfig. "
            break
         }
     }
}

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {
         break
      }

      timeout {
            break
         }
     }
}
expect "root:/bin>"
send "./ppifcd_test -b $board_num \r" 
while 1 {
   expect {
      "Total Frame Capture Time" {         
         send_log "\nCase $case_num ...PASS\n"
         break
      }

      timeout {
        send_log "\nCase $case_num ...FAIL\n"
	send_log "$TITLE ............\[FAIL\]\n"
	exit
         }
     }
}

incr case_num

expect "root:/bin>"
send "./ppifcd_test -b $board_num -c3 -t\r" 
while 1 {
   expect {
     -re "Total Frame Capture Time.*Total Frame Capture Time.*Total Frame Capture Time" {
        
         send_log "\nCase $case_num ...PASS\n"
         break
      }

      timeout {
        send_log "\nCase $case_num ...FAIL\n"
	send_log "$TITLE ............\[FAIL\]\n"
	exit
         }
     }
}

incr case_num

expect "root:/bin>"
send "ppifcd_test -b $board_num -c3 /var/img.bmp\r" 
while 1 {
   expect {
     -re "Saved" {
         send_log "\nCase $case_num ...PASS\n"
         break
      }

      timeout {
        send_log "\nCase $case_num ...FAIL\n"
	send_log "$TITLE ............\[FAIL\]\n"
	exit
         }
     }
}

incr case_num

expect "root:/bin>"
send "time ppifcd_test -b $board_num -c100 \r" 
while 1 {
   expect {
     -re "real.*user.*sys" {
         send_log "\nCase $case_num ...PASS\n"
         break
      }

      timeout {
        send_log "\nCase $case_num ...FAIL\n"
	send_log "$TITLE ............\[FAIL\]\n"
	exit
         }
     }
}

spawn ftp 10.100.4.50
while 1 {
    expect {
                "Name" { }
                timeout { send_user "Failed first return\n"
                        break }
        }
        send -s "root\r"
        expect {
                "Password:" { }
                timeout { send_user "Failed first return\n"
                        break }
        }
        send -s "uClinux\r"
        expect {
                "ftp>" { }
                timeout { send_user "Failed first return\n"
                        break }
        }

        send -s "cd /var\r"
        expect {
                "ftp>" { }
                timeout { send_user "Failed first return\n"
                        break }
        }

        send -s "get img.bmp\r"
        expect {
                "ftp>" { }
                timeout { send_user "Failed first return\n"
                        break }
        }

	        send -s "bye\r"
         expect {
                "Goodbye" { break }
                timeout { send_user "Failed first return\n"
                        break }
         }

   }

   
send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 


