#!/bin/sh
#
# This creates a pkg-config frontend that has the form TARGET-pkg-config
# as this is the utility that autoconf scripts will automatically search
# for when cross-compiling for TARGET.  Here we setup the pkg config env
# paths so that the .pc files that are searched and used come from the
# staging directory rather than the host system.
#

prefix=$1
stagedir=$2
argv0=$(basename "$0")
subdir=$(dirname "$0")
[ -n "${subdir}" ] && subdir="${subdir}/"

if [ -z "$prefix" ] || [ -z "$stagedir" ] ; then
	echo "Usage: $argv0 <toolchain prefix> <staging dir>"
	exit 1
fi

cat << EOF > ${subdir}${prefix}pkg-config
#!/bin/sh
export PKG_CONFIG_LIBDIR="${stagedir}/usr/lib/pkgconfig"
if [ -n "\${UCLINUX_PKG_CONFIG_LIBDIR}" ] ; then
	export PKG_CONFIG_LIBDIR="\${UCLINUX_PKG_CONFIG_LIBDIR}:\${PKG_CONFIG_LIBDIR}"
fi
unset PKG_CONFIG_ALLOW_SYSTEM_CFLAGS PKG_CONFIG_ALLOW_SYSTEM_LIBS
exec pkg-config "\$@"
EOF
chmod a+rx ${subdir}${prefix}pkg-config
