#!/usr/bin/expect
#
#Test program to test reboot.
#
log_file reboot_test_log
send_user "Starting reboot_test.exp\n"

set send_slow {1 .01}

set SERIAL_PORT_BAUD_RATE   "57600"
set TITLE "Reboot Test"
set count 30

set argc [llength $argv]
if { $argc < 1} {
   puts "Usage:  $argv0 tty-device \[reboot_count\]"
   puts "   where tty-device is something like /dev/ttyS0"
   puts ""
   exit
}
# grab the user specified parameters.
set ttydev             [lindex $argv 0]
if { $argc >=2 } {
	set count             [lindex $argv 1]
}

proc step { message } {

  global step_sequence_number

  puts "\n*******************************************************************"
  puts "STEP $step_sequence_number: $message\n\n"
  send_log "\n************** STEP $step_sequence_number: $message\n\n"
  incr step_sequence_number
}

set step_sequence_number    1

step "Start kermit"

# Now set up the kermit parameters.
#  I want these all contained in this file to make it easier for users.
#  This just builds up a list of commands which are sent to kermit.
#
set kparams     [list "set line $ttydev\r"]
lappend kparams "set speed $SERIAL_PORT_BAUD_RATE\r"
lappend kparams "set carrier-watch off\r"
lappend kparams "set handshake none\r"
lappend kparams "set flow-control none\r"
lappend kparams "robust\r"
lappend kparams "set file type bin\r"
lappend kparams "set file name lit\r"
lappend kparams "set rec pack 1000\r"
lappend kparams "set send pack 1000\r"
lappend kparams "set window 5\r"
set nkparams [llength $kparams]

set timeout 3
spawn kermit
# We need to save the id because resetting the board will overwrite it.
set kermit_spawn_id $spawn_id

while 1 {
	expect {
	        "Type ?" { }
		"ermit>" { break }
		"not found" {
                   tee "ERROR: Failed to start up kermit"
                   exit
		}
		timeout {
                   tee "ERROR: Time out starting up kermit"
                   exit
		}
	}
}

for {set i 0} {$i < $nkparams} {incr i} {
    send -s [lindex $kparams $i]

    while 1 {
	  expect {
		 "ermit>" { break }

		 "\\?\[A-Z]" {
                    tee "ERROR: Failed to set up kermit parameters"
                    exit
		 }

		 timeout {
                    tee "ERROR: Time out setting up kermit parameters"
                    exit
		 }
	  }
    }
}

send -s "connect\r"
while 1 {
	expect {
		"ype the escape character*" {
		     break  }
		timeout {
		     puts "\nERROR: Can't connect to serial port\n"
		     exit }
	}
}
#
#  Ok, Kermit is running and connected to the board.
#
step "Restart the board."

send_user "Try to figure out if we are in u-boot or the kernel"
set where_are_we 0
send "version\r"
set timeout 20
expect {

    "U-Boot" {
	send_user "We are in u-boot\n"
	set where_are_we "uboot"
    }

    "Linux" {
	send_user "We are in the kernel\n"
	set where_are_we "kernel"
    }

    timeout {
	send_user "Can't tell if we are in u-boot or the kernel\n"
    }
}

if { $where_are_we == "uboot" } {
    set timeout 50
    expect ">"
    send_user "sending reset\n"
    send "reset\r"
} else {
    if { $where_are_we == "kernel" } {
	set timeout 60
	expect ">"
	send_user "sending reboot\n"
	send "reboot\r"
    } else {
	# If we don't know where we are, hit control-C and enter
	set timeout 10
	expect "*"
	expect "*"
	send_user "sending control-C\n"
	send "\3"
	sleep 1
	send "\r"
    }
}
while 1 {
       expect {
         "Hit any key " {
	     send "\r"
         }

	 ">" {
	     send_user "successful reset attempt\n"
	     break
	 }

         timeout {
	     send_user "failed reset attempt\n"
             break
         }
      }
   }
	

send -s "set bootargs root=/dev/mtdblock0 rw\r"
expect ">"
send -s "save\r"
expect ">"
send -s "reset\r"

step "Start $TITLE\r"

for {set reboot_num 0} {$reboot_num < $count} {incr reboot_num} {


set timeout 5
expect {
        "Hit any key" {
        }
        timeout {
        }
}

sleep 1

set timeout 2
while 1 {
   send -s "\r"
   expect {
      ">" {
         break
      }
        timeout {
                send_log "\rReboot $reboot_num ...FAIL\r"
                send_log "$TITLE ............\[FAIL\]\r"
                exit
        }
   }
}

set timeout 30
send -s "tftpboot\r"
while 1 {
   expect {
      "TFTP" {
      }
      ">" {
         break
      }
	timeout {
		send_log "\rReboot $reboot_num ...FAIL\r"
		send_log "$TITLE ............\[FAIL\]\r"
		exit
	}
   }
}

set timeout 5
send -s "bootelf\r"
while 1 {
   expect {
      "Linux version" {
         break
      }
   }
}

set timeout 30
while 1 {
   expect {
	"> " {
		break
	}

         timeout {
		send_log "\rReboot $reboot_num ...FAIL\r"
		send_log "$TITLE ............\[FAIL\]\r"
		exit
         }
   }
}

send_log "Wait for 1 minutes before reboot.\r"
sleep 60

set timeout 5
send -s "\r\r"
while 1 {
   expect {
	">" {
		send_log "\rReboot $reboot_num ...PASS\r"
		break
	}

         timeout {
		send_log "\rReboot $reboot_num ...FAIL\r"
		send_log "$TITLE ............\[FAIL\]\r"
		exit
         }
   }
}

send -s "reboot\r"

}

send_log "\n$TITLE ............\[PASS\]\n"

log_file

while 1 {
       expect {
         "Hit any key " {
             send "\r"
             break
         }

         timeout {
             break
         }
      }
   }


send_user "Ending reboot_test.exp\n"
