#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."

set case_num 0

incr case_num

set timeout 8
set flag 0

send "cd /bin\r" 
while 1 {
   expect {
      "bin" {
         set flag 1
         break
      }

      timeout {
                   
            break
         }
     }
}

set timeout 100

expect "root:/bin>"
send -s  "./ex1\r" 
while 1 {
   expect {
      "join b succeeded 0" {         
         send_log "Run ex1 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}

incr case_num

send -s  "./ex2\r" 
while 1 {
   expect {
      "> 9999" {         
         send_log "Run ex2 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}

incr case_num

send -s  "./ex3\r" 
while 1 {
   expect {
    -re  "It took .*tries to find the number" {         
         send_log "Run ex3 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}

incr case_num

send -s  "./ex4\r" 
while 1 {
   expect {
     -re "Thread .* freeing buffer at .*" {         
         send_log "Run ex4 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}

incr case_num

send -s  "./ex5\r" 
while 1 {
   expect {
      "> 9999" {         
         send_log "Run ex5 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}
  
incr case_num
   
send -s  "./ex6\r" 
while 1 {
   expect {
      "count = 1999" {         
         send_log "Run ex6 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}
     
incr case_num

send -s  "./ex7\r" 
while 1 {
   expect {
     -re "waiting .*count = 19" {         
         send_log "Run ex7 finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
	exit
         }
     }
}

incr case_num
set timeout 15

send -s  "./ptest\r"
while 1 {
   expect {
     -re "PASS" {
         send_log "Run ptest finished.\n"
                case_pass $case_num
         break
      }

      timeout {
                case_fail $case_num
        exit
         }
     }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 


