#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."
set timeout 8
set flag 0

expect "root:~>"
send -s "modprobe can\r" 
while 1 {
   expect {
     -re "ISA-BlackFin-CAN CAN Driver" {
         
	 puts "module insert success.\n"
         break
      }

      timeout { 
         puts "module probe failed.\n"                  
         break
         }
     }
}
expect "root:~>"
send -s "lsmod\r" 
while 1 {
   expect {
      "can" {
         
	 puts "module ls success.\n"
         break
      }

      timeout { 
         puts "module ls failed.\n"                  
         break
         }
     }
}

expect "root:~>"
send -s "can_send 10 01 02 03 04 05 06 07 08\r" 
while 1 {
   sleep 3
   expect {
      "root:~>" { 
         break
      }

      timeout {                           
         break
         }
     }
}

expect "root:~>"
send -s "can_send 10 01 02 03 04 05 06 07 08\r" 
while 1 {
   sleep 3
   expect {
      "root:~>" { 
         break
      }

      timeout {                           
         break
         }
     }
}

send -s "receive\r" 
while 1 {
   expect {
     -re "Received with ret=1.*01 02 03 04 05 06 07.*Received with ret=1.*01 02 03 04 05 06 07" { 
   
         break
      }

      timeout {                           
         break
         }
     }
}


send -s "lsmod\r" 
while 1 {
   expect {
      "root:~>" {
         break
      }

      timeout { 
         puts "module ls failed.\n"                  
         break
         }
     }
}

send_user "Ending $argv0\n"
log_file
 

