#!/usr/bin/expect

# Main entrance
source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp 

step "Start testing."
set case_num 0

incr case_num
set timeout 2
step "Build helloworld.\n"
spawn bfin-uclinux-gcc -g -o helloworld helloworld.c  -Wl,-elf2flt
while 1 {
   expect {

      "*error*" {
         send_log "\nBuild test program failed\n"
         case_fail $case_num
      }

      eof {
         send_log "\nBuild test program done.\n"
         send_user "\nBuild test program done.\n"
         break
      }

      timeout {
         break
      }
   }
}

step "\n"
spawn bfin-uclinux-flthdr -u -s 3500 helloworld
while 1 {
   expect {

      "*error*" {
         send_log "\nPut helloworld stack in l1 scratchpad failed.\n"
         case_fail $case_num
      }

      eof {
         send_log "\nPut helloworld stack in l1 scratchpad.\n"
         case_pass $case_num
         break
      }

      timeout {
         break
      }
   }
}

set spawn_id $kermit_spawn_id

send "ifconfig eth0 $targetip up\r"
while 1 {
   sleep 3
   expect {
      ">" {
         puts "ifconfig set success.\n"
         break
      }

      timeout {
            puts "Fail ifconfig. "
            break
         }
     }
}


set timeout 10
step "Copy testcase to target board\n"
spawn rcp helloworld root@$targetip:/
while 1 {
   expect {

      "*connect*" {
         send_log "\nCopy helloworld to target board failed\n"
         case_fail $case_num
      }

      eof {
         send_log "\nCopy helloworld to target board done\n"
         break
      }

      timeout {
         break
      }
   }
}

set spawn_id $kermit_spawn_id
set timeout 2
send "/helloworld\r"
while 1 {
   expect {

      -re "FAIL" {
         send_log "\nTest for helloworld stack in l1 scratchpad fail.\n"
         case_fail $case_num
      }

      -re "TEST PASS.*$kernel_prompt" {
         case_pass $case_num
         break
      }

      eof {
         break
      }
      timeout {
         break
      }
   }
}

case_pass $case_num

all_pass

send_user "Ending $argv0\n"

log_file
