dir_y                                       += blkfin-apps
dir_y                                       += blkfin-test
dir_y                                       += blkfin-drvs

dir_$(CONFIG_USER_BOA_SRC_BOA_NEW)          += boa-new
dir_$(CONFIG_USER_DAGRAB_DAGRAB)            += dagrab
dir_$(CONFIG_USER_DIRECTFBEXAMPLES)         += DirectFB-examples
dir_$(CONFIG_USER_I2C_TOOLS)                += i2c-tools
dir_$(CONFIG_USER_OPENNTPD)                 += openntpd
