dir_y                                       += blkfin-apps
dir_y                                       += blkfin-test

dir_$(CONFIG_USER_AWG)                      += ndso
dir_$(CONFIG_USER_BOA_SRC_BOA_NEW)          += boa-new
dir_$(CONFIG_USER_DAGRAB_DAGRAB)            += dagrab
dir_$(CONFIG_USER_NDSO)                     += ndso 
dir_$(CONFIG_USER_NET_AUDIO)                += net_audio
dir_$(CONFIG_USER_NET_AUDIO)                += musicpd
